authentik:
    secret_key: ENC[AES256_GCM,data:J2D7WPngD1iXgAFBWYafmhPCqCu9UMxPvlVm2hM6vMDOaITiqWSkP07cTtUpiBC+2UM=,iv:vrOJLHYlGrgr7Gc9H6An5UZIMB97u8+q5yRdkYRWXSE=,tag:qrdpH23NsnCAK/jb8Od9iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUHJnQ01SV3h5am81dElV
            VXBEOXFkYW56VnBsRDBzbHJGbDN5UjFXYkU0CmkzOVlWcStuaENmQ3U5UDloMkQ1
            cXdCdjRGaVZORTNKM05jeS9LY3BrdEkKLS0tIEVDTmZ2YzgxNFpDamcxTVdiZE9p
            b0taYzhBOHRVVVhzVEgzVGdBVU05dWsKxqcBUxH3iG2Mvj48/ai/CrK2INSd2D8a
            1yhcayggd3JsJI7tntYRC/H95+n/E8xyxnzAmacs8DF0sbf/r6FIAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T19:45:41Z"
    mac: ENC[AES256_GCM,data:+fcz7y6K5oEn5Ase8GEmAH6wih+di36MPF3tLhlgFTIXaGJZ+NrcaSEE2LPJ+nl7B6eVwRhenkGllTdi5Yl4zkXlUL4POv2lag0UpLnbiRdOT9ouWM+2YHi1qbD2IwL5eL616gguEHc5aNaZSBKqcY2sW54/yMy7lg6vasnC9Go=,iv:wRSXWDo1L/7MiP4VE1zX6dJML2+KSx/gUldlVhcqaM0=,tag:kl9nJAHrj1j1+8QXm8yD5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
