apiVersion: v1
kind: Secret
metadata:
    name: openviking-config
    namespace: artemis
type: Opaque
data:
    ov.conf: ENC[AES256_GCM,data:6ahpU/rmi6RZ/Np/7dFArAMbVVRN7wcJHgQ3x68BF6V5bN5IPa9zgLjCgddUI5FAQGPU1B0F612SShZij/qQNQxoyUfn6cBbFYrZlH1HiQqP6HEYa7P8oaWVPGoHP9wyJ2At4+K/zO5I0YUcvkCge/kZIX9seq3bkxSXDrubHa+7GPdza3dTUAvDrKrOvXjTuT/B7tuNT49bNWxsD5mfcJLZ3sxb7SAIWB94BDBLiOzjmDatYHN68WyhQ3YxGLK57to/RymYspx/BgbhJr2nSpne4UB/HuIVPZJHM9RRbpKzhg6PZanzicaMbPbbHjmFKX+ijMFXXsXjK/qcQfOigJtZQ8eMLEllYN33HnYa4PWMrVb2wEgoWj0LmmOxQTzbDIIzGYRdiHTj5oGT/81tUTnMFVTh+MThxigSc4oVZdtsLIJ3gOzYATl38qHIxLowQVWoH5FCUx96aegfeXseXD6lbjmFq6hYwTPwREHqx6aO202CtQ+bKwQWecWSet7DjAhNuJYYk6MLxpykU2mjhj22F4RHy19aLiP+3hrad8tBbrMP9tkLJiLJpxF8JrsFlad52zyobTSoTLbKOb09h9z8KKZ2gvOgtvyzL2VLxB58NbQUNT4jNG689236iQMFriWh5gnMcyCSgPXjJ4FWqHyTXStZbWTHzkOP2oDGNuxgQ+AtBn4rnSpnNRzwCetA7HpLgEzefW61ASh2aSGUEoYuvjLjF887FzspgKAwzqo9VmJalmqYYeuRwA11IwKNT/QUtc6PysYdv3D6OIcEJ4aJBAtXp5Zr839+fv7LWYQ20mlB5lCsQXCA9nHM5f028FqtYgY=,iv:0kdr3iyw09ZVqe7+OSUhiAY5dHAQGM/Siv90j12+sXs=,tag:9v6n7YsTfnje6Lq3iMA3JQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOHB2T21LdGMxMm1BejM2
            R2F1R3U5S0FxQjZ0MVd2a0hBU1ZrdTV3S3drCjlUUGM4Y0QvaTBSdlBHeEh6RDht
            QVduV0xET2ppVnpiSHczVnVpS3FFdUUKLS0tIHk0cEthdzlEdEJyYk9Jdlk3c3Ja
            b3k3Z2lmdnpsN1p1T2JReWJ6YnlkQ2MKz4APvwjOHeubWME5Y9Z0pGQAfXIC+gpr
            h9NZwpj3wY/r2DbMNJ+HsYw200E1aIsDldg+hLY68N5T9qr3uq5e5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T22:32:20Z"
    mac: ENC[AES256_GCM,data:XsoQ9LIkjcCmagcpBgrx4Wa0+F4QHDQ98sH3bJczVcZnWaM6ospIHWHTa5TkwxdS+EOyrn0rsLT7M32Ppk4uyrFNr6jOcVj5w2qkNl656RLQzsUksQ8SHnWQrqmBZB3IHge2zeHzkH2X1Wiy1GZPhZzV44lYIUx3JpCaZmynf1g=,iv:+qzuMJnWrTpVKcY4ISXbw42hbptvh/kvxaHJ3zJ/9ZI=,tag:b5MgSxmoiHW7X1aDntdR+w==,type:str]
    version: 3.13.3
