apiVersion: v1
kind: Secret
metadata:
    name: artemis-config
    namespace: artemis
type: Opaque
data:
    config.yaml: ENC[AES256_GCM,data:+QyXQdOd30tcg5MJT8iW6GwOoIsMGyLUShoUJRVYN7h/qe2iM/xo2rAbjDPpGhRrZm1MNDfhaTS8LL0KLT2fVhbqEso2q8D9CvotZ4n+YmnXincBqlMpZaER+UZbM7cLL7baa/NvJuxj8LSds5MvrcgUByScry3UIb0BCA3YTiRgeR5txNIW4QDPHj+A4HgmcN9tAcgZqwxmatbYMuZ/2oJje6Sdl58R5T7NDWILYsjvmnqp7vj2xmc2KC2gzSIwCsoU0c1P1etV9VVqKalchlm9l6X+BWJrGhmNe3CF3C87utY/IEXB9mLoMwnHhxkWDhYGCEf2D6fTasqHUHl3ZmYnOfH4TKVwJNc+tjD5pe8Kl0Kw6JxGKU+KbdLjR9I4tW/mAw85vJAIlrptSg+HNN88x7QUtybclL7HL+/jSF5+Uxz/M1k+4zZwL6U=,iv:fgqrZsO9jeZFclzswx4sw9CQQ5L2TpfyB6zdCFyRhFo=,tag:z7H4N6BJ/OL8v2if1bNmtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGKzBSVndiODJDZ2NHWUY5
            dXl5NnAzZnN6aDMxbmY5cy9mRjdyb0FqYlc0Ci9yTGFibGg0YS9kQXF2MzZ6M0Zp
            UGRjR2RLN0xaczdDSnNyNGh5MitqcFUKLS0tIEJJNlg4eHFCL1ZTekdxQWF4UDdj
            TVVYYmxKMmxZL01ScGdFY1g1NUdYbzQKLDzsdOF9jk2OgcAvz+FYAUzqiUDm654r
            vAJwaL0hEwkHr1+Aah8Iy30r9ft4iG90sey0fn0xMY4fdvdkkH+8Qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T03:54:01Z"
    mac: ENC[AES256_GCM,data:dslcF42VGejda7NguGeqDo/Ftu9xfUo9VIOOoa3YyboKz2+PwVHRwH5jz02rBkRO2SmWrABXxDuxT8AOSrRDMVuYQo9Vya5O+tDFZSvFoj72SO9CwVM7H19EETnmm1qoCKpTmrBxFed3VILAwTMa++0JDqdvA5Bu7h5vQzVLMT8=,iv:mXPn9TePRh8l+fl4DvYJ9s532w+fF2GqMHe3MpKTAWE=,tag:bFjZBtldBomnuTrJcfM+kQ==,type:str]
    version: 3.13.3
