apiVersion: v1
kind: Secret
metadata:
    name: artemis-secrets
    namespace: artemis
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:p9ohxEgmk35FWbAnYI/d8x1yBxVzNyqm/1ijHZVq33ZaRe2z1acIdibuuV6yL/+U57QIXEk0hu3sFpkfcSdFIg==,iv:Afq/dhBnrbt4UItDz8BUEHH6OrEITydjcFnFV5GRigg=,tag:xlrImBU0R86Uh5+eP2LT5A==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:+1truV+xAp6QCtKezD6LXikNKQUMfwK3ahFgyA2efpJasHAteDvNawY5,iv:AFrrsZLCBJGG5BKfGgzJ1z+NMyQ2krk58an/qGPzM/k=,tag:pxxZI8SkNM0+Jx64FAj9gw==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:IGx3lbhZOBCIrmU2daw=,iv:hBUMaMap+vk9+RqD2Y7wTLPDk8kAiXHo9H1dIAidqg4=,tag:PagEep2XnMpD9JKbMunGYA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:G0mgcD+FxNWtzcrNA5RX,iv:yBm9Y6YKapnQpFnZJ6yQySDKW6xZ8FHitNckt1ePgYQ=,tag:C1iKAxq4jfrBzue+ygFvqA==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:znzE/+k91Fih8a8WmgP96w==,iv:XnyIdyKqoh85M8uh0Am1FYWgvZepky4BJFM4HDoo6lQ=,tag:Ei7HMr7fdFowT59CIGas7A==,type:str]
    OPENVIKING_API_KEY: ENC[AES256_GCM,data:pEWRV5luW2Fj+CkReQDzfYg067tndXYK60tseP7+z1XdgHoTx5IT91Op1aDO0NR+3omiPpa9sNy22qEJ/s0LnD71f+/o9KtYqdFqXAOJ8aQYr2cb+FfTm/SvdXpK8tPRqSkL12Vz+67ov6/Y,iv:REMjeoHoX5zzWOz/iUM+yLazL5lgccCtaLmbUBTP2Ug=,tag:407ABAghktfqR+higiW9GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UDQzc1YzMnk3b2ZYVVMy
            YkpseEJndjhldTFBa3pybXVWelNNWDZjMUdrCmpVam83alFKR3ZBR095cjFWMmUy
            akZwSitRcTBudXFUYUhLL1pvNCtkbVUKLS0tIGZsUUlReDZnY0xQVDZyY1FwLzNC
            Y0NQM3MvZnRPUUp6NWpPWFlwdjQwM2MKGVwL1RasMjDiA6nnPPviSwTr8ksG/jjk
            HeT7cyiHC+WTKzs00fJjMNsIluqkTz7QBA6PLTrq5c4h9Jd1kvdeOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:40:01Z"
    mac: ENC[AES256_GCM,data:yfx2tzVHxZwdXcD7kgM/OvawBWZutpX0n/y0JLar4jtNmiCrLIqgAeXaw+sJA1sNvNiKdnJUo0TQJERmXSFauyW3z9RcJtqcYUmiDwu9YV6pf5l6d3ke0/aYREAF7vVRqbvWndDQwbd/0yXNnHl5cYgbR9CtzId8Dtx96hYgW1o=,iv:yoxg8wjfehDNLcTAaLRkO1kUXtC7TM3qgTnQVzUA+bM=,tag:cjekkKBOTDs4r3wyU20T1A==,type:str]
    version: 3.13.3
