apiVersion: v1
kind: Secret
metadata:
    name: artemis-hindsight-config
    namespace: artemis
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:NR0/ic7LSUnnWrG50ck1KLG19qM4w27xLipztUe3vF9yVtQ6tgP2nUrYvll5tjPURwry8d+4RDZgPBTYubE/tQAMi4hgaeeB13hw/E/h0UufP9GKR/Y/Qb2e90uTr8EvuhKAZruAOoGUe8lDJNbm6XoBB0IqeCHJpBkKBz5v3puOBwVX77TqGN+wf1bUqoYI12BnPfBA65GhbkqVsR+on2JkqyUTZ30z8u4FC6LBPtsT2rR3vZWDU2vDcAxQLIHweiwOepYbYJtUslP1PL/WfqjXbGSM5LdnBcEykyxiejQ+/TJmowGwpC55evDZNh64q4BI/w9bBgRoiP8+wz+g2RvrC+oCEMbK7kNzj5LDwCRfQg4RvQdcLMGLYqPWbrsFLrU10J/BY0TbDceCx4g1NfmlhZFGrakgn6iOl/LglNM7KJnsjP5b4XiVuZyDa7w7WzG5djqGcSftgoT4K6OGkgKoyHA0cjfh1sSUpIIY4xlbQwRfEa1Gm+oCWijtjjdJeqF/l3hm61CXTvO6zoFMe1DpFYCzVaqJ3XcNvp41Uzkl0NpvuqO7ENduC82ngtc+gk1N4xUAmDptX4NBINWM0d0LN5p5+/wbVDHqDmVEM36zeggsHsUQCBScZTvA6EXNa4iXO71on6oOl2N8GmgFfY+AH9QVVPUb/SQaL7LyJYBPqOwUSrCmLJReJvEj0GJPmIjdBC99V9fpRK7stnpFgLLOeI+QHRnilvMDm4634kWe9StwuvG+UkOCKef5fuEUUUoT/G9pkpjQ8JYUJogn90YvUDojAkaRKugjTVV2cHkM96ypwEIeXUNq8w7gBa2QNSMCrgATtcVfZwSKc/WSCemN7HMiiqPoq44SWxJOvXEdrtsx9BrXEfwEG+OygWgktqVTc3NlojF6Ok+GuYFeoWG/0b8VWqkXasMET8ONae/oumri35qSV4lgrpr7+ERCcgFK3FB2J/X7bHhMv4fBAPS9mHuLg6+1XrELKWqkW+VgsHD/G5pZIW7tPZuiGb7S8cl0iK71S1/yGQKVSxCWJl8r3Z8Za5M3/vvNv4HlLjb/H6rR5VrWBcZt5ZsPmaa8y/43ADM1Ip7Uh5nynQmAPO/zClkIAaGw4ervaAOhaVxHWZYIEGvnPngiPuVljWjDfYoX+lkpiw2+n5oGSyH7OW/vr+vPEOkOF8q9gM79QbqjqRYcXBCumYZKfToDKrq/9m0LT/NWHyIFmbmAHpRlsVtTcCY3sJEd5JAaMuWTSkDVaCpliLFQio+2CfdCYlc0i5oQ9cSKGBYeaw==,iv:Y5tLpQKULekkhGEns+umGmOpw+ds3QTfBQAh7S1Reag=,tag:5q+i0P7cKGWOJWyJ1yQnxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieUpBU1dBU2tZT2t3QUk3
            RTdJYmxmUTNucGwxWUI2SHBMQzVJVzVhRERZCnpkWm1CeUg4S2lkVW1ZQUpMdEJz
            L0w5eGJFeEpvZVkwL3crVmJMVXZkUWcKLS0tIEVTVG95eHRGWWdiRUY4bnFnQjlh
            YmRvZ2k5WHMwYm85eVl3a1VvL1BRaGMKcAD46KDyNHQzOyOtl2FjlgxTE/mNwtCo
            s/x9TR4GM1cgcIOWox3ARcuBMfuqvQcJBliTtk5kEZqOs+EpmBi/qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:59:13Z"
    mac: ENC[AES256_GCM,data:iaqjZ7ufRfmMPu5/705g33QtR+gvXTYXoXInRz4NG0Kwp+qM7BGN/cN4fc60e8fite7ms3M+7k4ZVj4acgExENp1nksNyuubkezdRcnD6kXWzO7jZSZMd/OlfDoKHqevW7Wi71Js9gDln241odmadyjcYBZuBG+rfPrnV5KAeKY=,iv:oLaa8Ov/R3mPhuVs6FmbKvfId27OQ+L1ju/Z96/Q3N8=,tag:1Uo27uuYVkoirtS8nbzEvA==,type:str]
    version: 3.13.3
