apiVersion: v1
data:
    API_SERVER_KEY: ENC[AES256_GCM,data:UvGEUuORp9r1VWualZqL0wrrQZyjIAh6vsVs7iY1s49GhrQj2tNOr1QweWgABCkSUGzWf0QzBdFy8FWhtMpN5obsvzP5lg+HbXCnSKhzXGxj0u3uiNt49Q==,iv:+9XZa36Fzhl+lr+r7HqupDqEqIOKKiJRJo4xkUDl5Aw=,tag:TX/K8/awMbyPWex83J3eqA==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:VKjD1xFn8DkHDbeduqkDeDUz7UVykkjz6iWUl2OGNU+3Ra6J6dUd4wDiwE5ecjPwCD///N7RxzQ=,iv:/g9h9Xbc85uBsN5uF1m/YiBQCVfdCCSsjnEDY6fRNlY=,tag:c6H8Of4KIpz+J7LM7BUnzg==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:xKmMDKcLd6g+0t9azR4yFFi1dkM=,iv:Sr4xv2Kxz4B7Uyy1x2xV/Kl90yVGLeWzyi2TxzEHDoo=,tag:bqQKkRmTj+nJV7nBw55MsA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:49NqkykptyMhW6PfBy+BmzUgFHpFXL0DLfkB4YFwY2g=,iv:RmrrXQRuV8T9I71oWU5Z0wQro5b1CKd4h9OViGpAgWQ=,tag:5Dj0Tln0fjWbQvYEcwIaFw==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:9+EqKhj3mLGUYv3ARzxp9RYFT+PZJjo/,iv:Ci71te0Uvt9RrWqCTmQxCTzoeCiaYAJ8MA7COdU1yQM=,tag:Tm8Ec0YvkH99mSlgcc7JHw==,type:str]
    HINDSIGHT_URL: ENC[AES256_GCM,data:AWGcN1ZibVjXIM9Oie9TnPPPH1ifTjKg/pzCohTwLoC4eXroe2QHLhl372DoO44XrAl9fS47BanWjV1TMQkITLGwZKdjN3MlLvK5VK5XjdTE1yWSazU16rh0Kaziz9Sq,iv:Qc0Oc35qb7V9jNCCFGfJnLmggadvFu67XiLlAF1wZSs=,tag:v5+D9iBrvrdoZKA45Qn9jw==,type:str]
kind: Secret
metadata:
    name: artemis-secrets
    namespace: artemis
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU1FsaWNCU0FmQUgzbnlz
            L3gzeWZQcVNja1pGU2pwd0tVdmFOSzlyTEhjCjlFUkpiY2luQkZiVFBMWmc4Nzhh
            WjQzZEFrNGlhS1dRV3pyYml0MGJ1cEEKLS0tIEZpUmJrUXl2bXFnTkF6WmI1Y1BH
            SXJ6S1dYanBaMnk0VEpRTnlPU0FMUkEKedTNyHjwPJH9OPcph7s12KStJ61onuCl
            trq/73el/Hhb1/UANllCPb9H1g63sjJjqObmHPomtKVl5tafguLzCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T03:38:44Z"
    mac: ENC[AES256_GCM,data:hTuqdam9nAu4VOeCp5LmYqj9usoe8hmlnXSFov+7mJeMzRKFPLBrDx14P7RVkWUDvXZEc+eaf6ezp1f2Sq7H1hB1Ove6b0db3kweDleQPR5tZrDwqJ1x+QKAq+zlUu+MSURk3DVBcRFt/bB/QqiG7nq7FAMnv3td/CYfqQYWnHE=,iv:8RiUHOuYOVsHT0R26GvXKwZfqkSppA04bLnx/B/TIw0=,tag:o0jec8YHKALdL8/TR8abyw==,type:str]
    version: 3.13.3
