apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: artemis
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:btT/rM2YLgeOm5RBMSo3S86RsGV+qWODMoeNrl3zBQ8asPdK7Sm7pNl8mkxEL+qdTv5iL4FmeJgjT0bEudw5cQ==,iv:zCyW6xHNqSzlUYyhki+gVjT3L9ss4aCiyfRa57R1kHc=,tag:TxyzT4zwYKWhkAW3gbJiGQ==,type:str]
    HINDSIGHT_CP_ACCESS_KEY: ENC[AES256_GCM,data:YHN+BpF5z9hhyy3+INO2AgUrQz/6j8WOwHoCTfYI0XaIXpVSo8bVIl/P+i8GIfZve8vngPcIkwLHiw+aDJgeEA==,iv:fVEIxR6E067MeUBAbtl9He+FtuhWif9X7KgdQsxoa8A=,tag:DhQ+rlCsAQihBIu5bDnrTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaFBZQk1TTklTT3htbUly
            WkhkVVBsb3ZUcHNrWXJQVFpBTk9PYnByL2xnCkhlclp0YzBYRjNUcURDM0xxVVdG
            azh0NXVGcXhDRERaNUhFcnlPOWx6dTgKLS0tIEZOTnNoM2s0RVp3RTJuMnR0S1Ji
            Vkh5bVI4WEFTLzJtaFdmS0hFNTZ6NXcKh/nSuhP3uvvQTGCDzK3nu6qSWogVDGCO
            yFqO6U1C3VulcTtau3Re9tAqmTce0rgzSqgS08hGvaLw5FJePZ79+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T22:32:04Z"
    mac: ENC[AES256_GCM,data:8C9Vzyxr61KrYWgeFPGcNYiGrNozr5DaUlJUQfNOitUxaT7dedd2dsp3RhmSU0I0992Fndh0N/ZmIM5z3AgrytEAP2OUlGNPN3S3kwLe7NCEajV8GpE1VlNPB8wwE03EwlNkE6Vge/5IeScyFXsaTSSNWz9kRxz5SSoBTJDXTI0=,iv:715LARyFyYQ83/RKWl1MxcC106jsiukP8tPqpjW5Z0Y=,tag:OQYRBsv16VWYP+9BS9IMag==,type:str]
    version: 3.13.3
