apiVersion: v1
kind: Secret
metadata:
    name: assistant-gateway-token
    namespace: assistant
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:ke6HCebSKtXZLrip+z5EOwVYJzE7WknpmsR23kgdIMKkE7p5lsXo1k+T1tHdcs9gcZBXUDnXw5Nfm/i06WuMVg==,iv:Ka1DubLFmZ45FbQhzqIGhQZlHjfoTedGoZknELYU6ic=,tag:yeF//8fj0gOppMAT4UshEA==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOW5GMUkyeHBqV1ZwUVNy
            WmF4UHB3MDZmSlcyTGM2cVdqU3RIRnZRWWhFCmJ3VUk0ZE5kcy9vMXk2WjQ2MUFU
            SG50eFkrdTRsOGQ0WmdkQ2JsVVF2OTAKLS0tIElYRXNIZHVaS0w3ZHZXZTN0RzVq
            UDRXMW94Zm12SUVBSVdMdkh2bzhlMncKIv8VefuJDpi+k4IdhL7MYtN/tcBmTI8d
            AF5MmQLSxkStKKOGB01yH22hdOrQgwIZaroX25SMlgQvAVBieX1N1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T20:40:02Z"
    mac: ENC[AES256_GCM,data:g0uwdgYY+Vpozj8IfX2Yh6S82oFITsjCUv5ALuiZVejOvyWji8V+mz4FAAV34LGJf7e4ppeenbCmU3hrEoKBBtzEZKoEE+h89XLxP99kRUFOaoZ0JKKLzD3EB3nfJ27N0nH4FlDyr2NBCbV2e3yFYErssG4558nECG2YemgwRzk=,iv:WeYOoeW790Azqlsb7F0TKvku5ZqCGcN9cFLQv12YwUA=,tag:flHBxAoTUZWFhgKWVXy5UQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
