apiVersion: v1
kind: Secret
metadata:
    name: assistant-secrets
    namespace: assistant
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:W2AmNcxbJ77JASC6f1OWmb6yAg3yZ/92F2ykHHaayduwW3b+PvIWFxhCU9mu1Z8pCZgcytIopb8EPzm1gfXI9NDTLzttYTpjb3oVeh1iq+nbcH4YwNe2wmyCDKmkMqgJNjqkv3ov3rwzA0Or,iv:Oseibi6p4mR8xCboG1c4SKVtFLSs/F7YU0xFwawUFmA=,tag:H3KyaziGAX1EvciGn65hgA==,type:str]
    GOOGLE_API_CLIENT_ID: ENC[AES256_GCM,data:wOia9HiJW5o90ktQNGqCRyDGQBrmIoLd4QmfkG3xwV1VMeSyaxCnrcdPlinGVpNC5tgxUDmZdPa7ZMFf1qQh64wz22ii8JaAczswibdSdYTuQM6rHvVEP3ea+S34xEk6,iv:aLle6KLgziJQ5Kwi0d8jZ5wtkYCX6P1oDUuQJ2pXPDs=,tag:PRp7h5OkPXTEWx5OgPoepw==,type:str]
    GOOGLE_API_SECRET: ENC[AES256_GCM,data:fRpuYEMhcXS3BMs1YNvpU97p9HW3DTmEX5veMC1q3aAdSbfGhPPj+Db29AZhEXJe,iv:c/5LXUbdpfN5hYemVUI2837NVeHvLnm/kP4OQcjzKEo=,tag:beMfNRMyUVP5lNNCavX9cw==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:ySxwMc/GJWqpe51E2VOt5r4e06vjAfFOWnNnp8ZqXx5UeMuvdnzmOlFI2eAat9qpp0NJedojIfHSZ96NYyq1LxuO4G4F4ybW4sTkzXmsKhRHSwX/P1QcCR68PhdD8IPfk/vfZwEipO3qCdpFaisJ29WgmOlqp/6OfsssANHuOjg3pMe3koVNmFuljN9n3Rghxuw2WtEwWP23XsA2iuwLRJpo2Xk4zKawfpuTiSvtcU3Bx4xCjyHC,iv:3CodsOk5k+CHwPr22H8uh1DFU9sQhqAjiRoMsFc/UYg=,tag:MCBPcsnFSHHRE20zhsvPsg==,type:str]
    HA_URL: ENC[AES256_GCM,data:qqJsfYRr/6aZvup0g90EpBv1pLAko5DOm6D8iHVeYtqJAZF3,iv:4OQWcVfJq+N1SubIlGWIYwJCZA2pe6+GUQwkmL2EQbI=,tag:6c7jeNfKejwTX7VXaJp/iw==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:iDZFpNANpcoTyNJMU4eDzgs39d7fGQ==,iv:+e0X7tCgU8X5af+2zSx3mRcxcvGGdVSWbiLRr6lNU8g=,tag:ez1T+0QFrRtl04a/b/wjuA==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:CgUX7R3rZdz6HraVEKMB+IYy,iv:ESTUnAJz2fITdetVBT0Fd/Ug+vSaOdYeAzfJ6XRyrMk=,tag:ybe2WHx1V/R1ibHMNWA7uw==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:aDXm0DCaKYFECHtY5kmBdQq5m/zweWx3/qP55spHsRCyOCUWnLNco7NlFoU=,iv:Q0xNhbKW0olttSwNs8h4kXjVj390A1MCGt4X4Jg71OI=,tag:9pzKehkeoGDgY112czRJ2g==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:CstW4oHlIcl7D1eZ8sKi4vurYC/gmNQB2I3WW94iCi+VIEHVlLHP,iv:o6DUaOylyKz4PDGvacBi4ZbEj0HmT5I+h3br8QALSgg=,tag:ndRxGXUvfJRr/o7r9YvaJg==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR002Nkg4NFNQc2wxTW9W
            dGlnbk5FSGZzaUFsb2pwNUFlZ05LTFlyN2tJCnlwbE9aT2ZzMnk2ZXdhZTg3M1E1
            cDI1Ky95dWtQWXBSODVJbCtOM0tuVDQKLS0tIDJpYyt0VXBVUEJmbkVSaHF1R1Rn
            NTdGNkFiUHJNNmZUVVRFZWE5ckFncGcKliPmkQpKi2T2uyuYkne/Rsiq3U2VcwKR
            m2SFeudiNtYcZoa1oJjag9eOmTRfg4Ym9nnu1/mVybaRaehqyip/9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T07:16:44Z"
    mac: ENC[AES256_GCM,data:Dd1ZPubnZVWUSZPyZFr5j3jpyBap8iiMKLB2p0r4aRUUwnFFCJJ4ZVbIwjZS0qq+G+5ffs3jo3EcxYuqe/RYJ1XIX2NiNhGNiY1KVzkFu9dbE2APPmvGVIXJn3kyvqFYag+I56k30sIUG8Xlg2Oj/c3EG/CFtrrtyPUnkA2d478=,iv:koNoKNc6P+CpbNTbBPhjTRKs0OUs18d2YxFY3049ZKs=,tag:IC2vsRlNgYvvEoQClwP9qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
