apiVersion: v1
kind: Secret
metadata:
    name: assistant-secrets
    namespace: assistant
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:HWJSwGRy2rUB99w9fX61f/FBmNvj5uYYW52/vpVryePdK86TDx4eklkLmpZSqb9MW8WNU9FS+OwuSslJPLJZBp22/xPbQbPopLbsieV91IJXxdwPcxjSOMySfC8F9tuNcwUFlqQOQ7ovIUHA,iv:LA7BamyG7rGjifUC49gyChXrVPbiRZPiDbTFvyENxzg=,tag:+0pzgC2n8PcOLWOMA1Wjsw==,type:str]
    GOOGLE_API_CLIENT_ID: ENC[AES256_GCM,data:pifCKkP99+W0aeDdFyPp6Yoo0X5f47wboulDwYLJli/Z1jMcbNNTjtvryLT/avw5xYOIvwGSpd1e29AkPhnTcdURfi/641ySf+NNOYvi/7dIvfdoxm1JvRNVlWAUtkMV,iv:bKudrc1UbNGtzhkmYEziWC3DO80IgEPhy6kz/uyYLZw=,tag:KYeCJJR+uxIJbZiE9SrJpA==,type:str]
    GOOGLE_API_SECRET: ENC[AES256_GCM,data:2TyerlWg2GDw/3b9NzUoGRR++TFC/n8oZAX7sDfV6BAl1PkM82CwaUC2jJale/EF,iv:GfQL4wqquG8JeUJof0yMqwWC3WqLMtONWPvOSDZdkTA=,tag:a2iv/Dviygfsi5MNI6hAvw==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:GXdN+PYte+I97st7LjLMAkBf7Vq9pV25rgr3mPsrwxMYW9mXL3jSrxHdHT8JadQaURZy16DtXdcImPq8C5U0qmoVVjh//Ks1D56ihL+TGFk3YCIvePTo3KNHxOGabskD7pTpfomWI1Ddy2RVzRVqE5Q7EAVfyEWWH0OBYPVW6Qt5/Rl6KkuLXq3rW2IMa+TyO/uuOl+OftLMsg6yvS7vWdgniKjuTQ4AyRdVnVzc8x/7laWoEYy5,iv:Ji5VmsclZgq8209Tt2Mt6/GwSjYbEVtfrjjJKPm8xII=,tag:PsXGDQgXQqjHPbKwGNL+Rg==,type:str]
    HA_URL: ENC[AES256_GCM,data:IqPMMrlLdzKF8I1hqL+1+NoNML3yuJwVwHhSygJDo0Roda9h,iv:q+1/aQPiP0Hg2iAon7uuCOOemLAWqjWTtkMoyTV5PuE=,tag:JA4SdvJI7fD7qUh7/2A6eg==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:mIJEmX6mm7yeLwEE8zywknM/E6FJlQ==,iv:BgGUoBCFdxpaiYmaKki642ucJ5uhqwpgSn5yuu7b57k=,tag:q8sH2q8IvU+SsqoQY/j8WA==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:dcUCNjRKVLCmhJEmXwvyiOw2,iv:Dx9d3tZyjl5JoKxSYmh648tTRCdFCx42uoX9DBvDKXM=,tag:F/E+stLKpdVPF6eXVXYGaw==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:fBm+CS3bZY/E4nnasA80QbbAahW+iTzG24IEbUogCRiwRXxSCnjinSKTOSs=,iv:ur+mvemO5de6Ih6khEUFugKu4clZLcPaexMeqpUK0cM=,tag:JGHS9aqOIxjaGrGGP9sUZg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:Pd/qjBUN9sjNAMVOhbPssPAOC9KqOzPwFqBWJxnYozybSoppHZzC,iv:OKfP7FeLR9qS0KncdroFe19+YxTvKL0dJardHx8A0jU=,tag:nbdkB0FxHRID1ULzdBzM0g==,type:str]
    GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:cPgWcoshSjMasBLQ4TGq,iv:qTqfh0w3hLiyTP2wYKCzamqFUgnCLu9llcByOOAj/iM=,tag:laLuWCooLQieVzZdC4stRg==,type:str]
    GOG_KEYRING_BACKEND: ENC[AES256_GCM,data:9iMqXA==,iv:ToI5otZUZqwBerNgZjT3MkUBPuc0cha1pKgHqTzMNAY=,tag:pl/NpskTT1KKiyrE+cGdEA==,type:str]
    GOG_ACCOUNT: ENC[AES256_GCM,data:3Yt4zFkfE1K+AhL9mT90AH8ZgZFy1Tw=,iv:6LDzS3kZ3U8tL3PIsS3RnW7jXQCkwyMqcS4n+kF/QQw=,tag:v7pr7kWF9R6mHgeReHM1IQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERDMzTGwzSXJRK2lMUHRQ
            YnhqQkdud2tQNW4zSCswWSt5YkJXSEduMlRvCitQQmtlN1l2MTJIc1N3U0p5R0V3
            TGIzRnVtbmZiZkJXb0xCZGI3cVlYSUEKLS0tIHBYaE5ZaTI0REhoNDdNbDRERENw
            anNrRVVSTHlrRFJOaHNNRXF6WWwyUnMK8klTxhiGbQMvn84cr+4eCwXYokSFM1rL
            tKi489spedJbtbgQ326lWDameYDAe6c9A4IV4u0iV24tS4zGF2wDIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T21:14:41Z"
    mac: ENC[AES256_GCM,data:xI7/WuJoO2RaCqeJdUenktokIwxWSDm3Zo9V/b6ShQHQJPP0/vvIdSsXJbxBBhLqH52cUA6nsia9vuUP5oboXMw3oqEMfZS6dOuD+I/Zsq7k8D6xhvbW65jesfZAebkTf7VfiVBsqL483AlIOG7W9cFXc4yyLgkO05GC3ZJbQQ0=,iv:Z4hziU1WbifP0HXaoOn+yb0ZFCFjUm8OmJoIfjJowck=,tag:g+9egR6I2u8vMzcHT0BSzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
