apiVersion: v1
kind: Secret
metadata:
    name: assistant-himalaya-config
    namespace: assistant
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:EKb0T50+c89ZSF1U4oOV+AQNwFjo2aP/3E/ZMpIW+5fq6b+fvM9fgAiofePfH0JFX8Vwrz1uXQUJpNhl2mO9c+43kUzg0Fovr9hbNGRHPdX3Y/Z2CQpXHXivdwL4fxrV8o7qqjTi8/nlHmG166J/EVW750aX7IICZT9Bw1slTRrRt4SXSW0bA4BvVQXU68P4DMo1EY+Ix+1JVY19oIhmovXrr8v5Wuv2QBXo9pt2nIBko//bYeibQ643qlFIZIxFAc1znPVlsrSp1VB02AVeAdd2YkkJIxkzZ+ejq8rIghqQ/wAyVZ2WZ/MYf5Q0ds3V8PBTp+aPSquFL7Hoc4wWI4qAPvFMQ51RdpunS/wq0fHIz5OX7EaidrSiPxfn8FUXhIBmcQEaaitVUZqwEQfQbI/GcfmiWD0dm89D2CB7VDCd40maOiKBEfD+qStrHfUezrZHwaG3XKowoiPN0XF/nQYnw0EP4SyyfUDRx6ufs+mCO+W14vR6CYoTeYZBSuiTnm52ZEaw1xdLEDhZYp/3eMmARg3RgHnL8UJT1Kv4iYEAq9PwzKkRZXAOvJ5bZNUUlnz63n27kszo46NWZmrqf9whBB+gy+nFSFkosmPkzA==,iv:M0HOlwabWHNlOJlXompH67EpBi/J7pJ5KC/Sm9u0ulA=,tag:L7GNePrfS6wUopnHrjyL6g==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSEYzdUdLREg4bkw3UUw4
            bjZJbXV6RnUxUVljakNXM2F3bjQ0bUhoc0E0Ck5BRDE5L05nczVHN3ZJeVMyakNU
            WE4wRmFBZHluRTF6RjhmbDh3K0o4M2cKLS0tIDU2bHpxNXdFYkJ6dkNVSlJpQzVB
            SVZGTXU0MTAxRitTMDJ3cjFBRXZKaDAKZ5ciep/xKYPSaSxvyCl5Hc5YgGOmTmCu
            IIJZ3mX+/uwKTmQpE/NiRosTHfoZjH6EfdtkBScFHMtSA2gO6hYMSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T22:48:00Z"
    mac: ENC[AES256_GCM,data:LA9kcjSgu1PbCV5KbFSRVz8cHVIzc0uu/Qbgc+hzOf3YWmPWk9/2Jova/DQ5SGOZL3zR0/J23VNJBNJgjknS0nNn4NNGE+t6Rjx22xhhZZEwNX0cE7Sq7IFonLE/QGaQl1/+gB+dPL43UM+4lQniF3Wyoe/hCMRhkp4PsKUpht4=,iv:bByQVi0krJNvtcX/yPZII8UvCtxODWmdoDWoYNn2INY=,tag:QHPSFPyBH+iXf8y7kAX1sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
