apiVersion: v1
kind: Secret
metadata:
    name: assistant-secrets
    namespace: assistant
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:AeFGYWb9Jpd6C2+yDrVXk3+JKJqYqkk29EUm4MPz7DplXJG4dNZNj/y2+BRid/Os34kgB1yGF++SyJgsI+7xHeKN1ONGcqXjnSx+ydN4w8Zz2Vjmq9JZNjhwSBLgfSqb9+lKGrSKIXc71rKT,iv:pRAmB9vTUBxNeE60ef2Nr4Aco7TjjS3BJYTkgF4qzXE=,tag:oxFhOLfK0tlxY6EyZo+vxQ==,type:str]
    GOOGLE_API_CLIENT_ID: ENC[AES256_GCM,data:1PkydhLT1DRW96x9ZbVr+l95iCLnH5WRlFPKvRIW+p+SY2F4dE/a4IUuoFGhn4iq414R9iYrvAKYxV4i8jEq71B117d101uQwzrmbUTqkBiKM4sUfBtnsa3TmXM6niL3,iv:TY+oUN5GnH4zVsABAXEaAs1lcVnXYRaiV20qUg6pEQ0=,tag:XmDr5BoNlAO2AGWw4Y2jtg==,type:str]
    GOOGLE_API_SECRET: ENC[AES256_GCM,data:95F63q52hkrDguemxvf6qJozXn/ep54oeWhb4XmdLbSRMee1+US2FeOLjbT0prC7,iv:ULuVV4t0vGTiJizwIaK52S0a46UeSRJxSungxVwM3wE=,tag:9pknyYHBDEyvKM7XlWtDCA==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:ufZnFWKaYlyGSksFg2qxA/XYtmKIN6Qppux2jsR+qFbBNG8XCXiUnbIfUDsGQ/70XnWvQ3VBCQoqzZsgBlqV+L3tDCkCgFbwvMIsqtaM4j2dRaiAneoNdwPk0mJ28koAUfj70kR6HYufC6D+XEPqhs1p01qDfxu1unouKjC/FYr6iFBLFEtl81TDgH0JdDQ2mErjK7PTep5OXAaGIsJOr1WcMGoeSO3ga9kWMGdiarX3+KZ2CDMK,iv:BcCGd6Wop66f80iCshKxMho7sqmI6Zf4ZPorjQs3SOg=,tag:ppFxkub76xR0iImodBpObQ==,type:str]
    HA_URL: ENC[AES256_GCM,data:p0Wj/FgphX7RS8Limd/YxQRy5mf4aki0hs/MGQbfY6Vmw2u4,iv:Y68Jt0Zkt1uoy133zqjbytmAs9F0SBdB3wASITVGBMg=,tag:oZvR8AUodY8ZbcixMkfPBA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:hUJ+XEZDoq6jy26yHMpg,iv:4b2L6yqCs2ggZjM0sGDmutAhTe32Gyo5YHr7aRWHnTs=,tag:PuCmV8e6nQwg/8Vdc+ch4A==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:KBgJwKUewhuZaS2iRr9VL1ip,iv:4AoeaIntG3Z9V8vejVksoiQtzDXrB6zrLe6K2fkdOQY=,tag:GDuezuOMgIxRZpGnyOmJKg==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:v7Hlg+vDXfCHbUuWeMg2DxU9sih515bq/jAvxElr3eXHPaoejDRSmjHQX+Y=,iv:jHbhPC0t4goRTnXwJr3Ipwo/pvpA0v/ZoVRXoBoX0Ug=,tag:zlVu19ckJiBsT5P7l8t20Q==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:8vZMdheELrjGqbQM7fbPiXcyw2J0N72n+++K7yy5ZIqladDV54bt,iv:NPX49iBme/PMJ/Dad7gdEH67VCCSwRhd0KCBC1nUPXA=,tag:M+DbuAY4dODF90tMrDdckg==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxck9JUmFLS291MlR4VGxv
            eFRITDJua1k1KzZBTG9uNk9OdlJxKzdlRGlVCm41amd3ejhlc0ZjMzExbVNRdERv
            ZDRETjdTQjR2OVE0ZVpjYzJmUCsrYk0KLS0tIGlTTnlhVkRDaXJPaVZ1ejlPbzlZ
            K1NLZ1p6SjNYTlFOVDNqc2QveHh2dnMKl6ajNBTpjU0/bdr05jSlZmjw+OYHLeGo
            OXlDm0G3A6lwdsMX0god9iNeUFzMCkDorz1tJuCXreOvehISHTOmHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T06:41:08Z"
    mac: ENC[AES256_GCM,data:BaoM7s42VuCyeJN+Xk/02T9lSt3FixG7yNSEzdiAe8F+t6DDaAnygcgEQsvb/1Qpta4LcBiLKrIpnn7LCihpMzIktoHWDdcRcAQ3c4XA67Ya9WG64flz0nDxmoCRNsGkUoCL+Mqs0DwbzIi0/dpzCp2qSPTDLcJ9v17ZNH6U8Os=,iv:P3NGgEdcMRO57tvu87yqKW3MueLA7F6pqhfNv0XbKfs=,tag:NwuirtOurLAJwfSxpg1eTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
