apiVersion: v1
kind: Secret
metadata:
    name: dude-secrets
    namespace: hermes
type: Opaque
stringData:
    HA_URL: ENC[AES256_GCM,data:9NmG4Aq5V0WVvsHqEiRoxY6jGHjFn7O/BiKCAufEwU0=,iv:ZNX4IPdPODQG4nuu7Wd0yhDENSn8WlWdg0A6aOpQSv0=,tag:51LYglJQtHLNc07Y8ntXAQ==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:9A1Xi4FDeBFU0QIGk9IFcZukZ4ceThYugvOOz0TCIzvr+UGGSPJvV2VHFqKQGWMMCUPxmZRj3/SKnHbCKgMS+jle7Bt+E96tZUGjnFlK+jZwAITdZpyoT5O+2jGW2DSJVaNrqhlmPAT+XESYwOs+Y2BGpBGlnC92wjfvc8SHlXjY0CUSXsIzHQ01piGUZzAU3/4ycH5ksmYHGW2cGYtyhiZfGXVPL/rZKp3qkJAx5aONL88PBaqX,iv:K98YwXsQDp1fBzmMRCQQv8vdIb6Ye2ibPVlFsJrOgqk=,tag:cveJ7M71R1iR0/Bm1p/j3g==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:ogqYziAzpYUWQzj8q8Cyzuz7kCcy2JBsvrGoFoebiaLKfs2TB+U=,iv:Lb/4NIMRTO6JfcxtDBlR/DLn/d4Ogy6KgcgowW6J40E=,tag:oyVCKpzIGfQeGuErhLKKwQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:/tEnqWc1+cV8kh/DpVKC87HhXiL/jdjgHh90X1cx,iv:kX2h1pLUVd9F1YsGIRfBwWRerftyZUHOujXfd/z7ttk=,tag:jC0ViTtoK8VuJ5HY5TfR/Q==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:Gw6DzUduyalGkjU/YfPb4khYq6fZVA==,iv:XD/DM/WdRZZA9mevnbxsP5LDVIaTFukehGuxa4sawQc=,tag:6p8L8NJDLYv8Uf8yi331/Q==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:5lEtUMPovGEwvpAoXg==,iv:S3YK0FyR9iExP/uZzLH5Ab3OkHgT46nTTMm3+utFHps=,tag:9qoBjRW0gMSmI8mWrI4r0Q==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:IV2LiMmRAnmTiE/QVFns0o7GfM2IYUipFazQ9Qw2Xu7XfwTwoMGPgJVXqb0s5ONuk+ZQuiAf8lozttJh4G7RLm8/6oKIMqWJDg==,iv:AhMhl1Mo7VsMasi5awHPZrAymXbIABP88CHLzvO5ifk=,tag:6yqww1tQUqAj7QBMNdHgNA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:X9IBbs8KXrBL+87HLhbml1YCVpuJ+UlepbBlPcIG0aMh+uNqWH1ffLIZ3sjAGwPUYFRxpIaD9jaqHrhXJvrVzbjTCRiCyLXcDkVX0+R9K6tqARjnW/pPJwtU0dJQHE7P4MN9NRXj+Vix0paq,iv:UGmAsRewpoPIECnvna46F2HibI8Zg69AkcrU+02pilM=,tag:1dT7/vqdmBGgI+IPt51PMA==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:iwyeGEvOORyQlGXUlELFirjW3Ig+y2T8xK+J/GOr/D4O5lOFedzdbfyYbqZ1DQAqsM07e3VwU6eF40TAdrErFw==,iv:vK9Cb6NgfD8R/Pyhpk/pKoJXtrflRZwT1SFKieXsnYI=,tag:5/7BUZr3bgh1Si3FiLQqVQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbVVObDM4WnROQ1AvSGFT
            ZUZxeDNzdmZOUWw3NU5SN1Vwb2dCc2FiSnpRCjUzeGVORUdpZ2ZveXNROE9FTStS
            ZkFOYzVsRmk1bSt2L0VBd0ZNNEJYTGsKLS0tIEhpUmFkK3Yxc1VxL3FlUWtmUy95
            aHErZHlqOERtTlgxK3hEZWE1OUFYUHMKzwj0F36pNS+C7Y0SgW+kJnlo8/cm87jh
            y+1YNDpSuqhRvst2GpIReebzcavTpCGOWp1wVxhea9xC9z2P8iS6kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T18:34:13Z"
    mac: ENC[AES256_GCM,data:WZ2Gx5J7s7Vwt+zozCAz6rJ8fLsraOZt9M1rIUhV0TTqTLH9pNC/OOOmzXJnpcXmakBPp2BkrkjieJu8ieCtBiA2gac3gB53LmuivqBTkWtRbtWR3ydSAKNjsVB+uK9sGUF1h9CWpnfu96UYOoqzZSY4+2F3GQLJHEqfmtFFvSE=,iv:ro44XXywsLdiNUn2sLC47h7mIK3k6owiVWd/FANbZIA=,tag:ELx27DQBl3k1wXDxGWgeQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
