apiVersion: v1
kind: Secret
metadata:
    name: go2rtc-secrets
    namespace: go2rtc
type: Opaque
data:
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:x5/MEzsF4FuMkc2oZVO3VMr6g/wfaAul,iv:GGpOZi3n+ARuPglrs4qnj/Ak8s2B7+KbOyM0dsY96PQ=,tag:9xgN8MEkHj1M2rJ6F9pVLQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuekVIbWtyWklIc0MyT2xD
            SXExaGltZ0FQbTJCd3RDUzA2d0owMkdKNXg4CmgybW4vZFNlQVk3MWM4SG1ITDZL
            VzVVK3V0OTlPc3BFWDZ5V01Ta05iRm8KLS0tIHJvd003Z2hGVENZUjl3U3Y1cmVF
            WG0yakNqYVlKUmVPVERPNnRUS1FCME0KN1KVlP444BPqP/87dbeG7Qbh7p5bt59U
            p0zZG3+inzgB8hTa0LfaQnIex/HVulp5WwIo7FzBoyUFxaUPzvZhbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T05:51:17Z"
    mac: ENC[AES256_GCM,data:gb9FXz5y1wjSvLRHX5oKuePjswWDlDVM4Q2u5JAvmV5I2bFdNBXKW3cDk0izFvjHfUi/6KJWJX4dSGAcCz2NRdswCHoaZYhgXKSCj0ylSS/VwpRRFRZ7k+pmJJa/M7+syVWWQwWtqGMm0G5uc+kCrzoU18Mv2AEUeoPg7sfe7P8=,iv:2stR9hs6zIrUXWPYOf1ej5yXOQIGVfMRicCSeNpyYyg=,tag:FaqqJKjwvfGSHevR498hOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
