apiVersion: v1
kind: Secret
metadata:
    name: grout-secrets
    namespace: pseudovision
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vyTuEtTYvlGcVquxJHl+6MbJwlPZZkO1/5++xiYfahc=,iv:eq+3n7MKvM9INIrUVNZMOWGJTWF6mw+Q95LxVquiFZA=,tag:5thNpFzMYdvHKyc8BlBuJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMkJiZmJuYzh0dkQrbVFE
            VkMvVEpPL2crUDRsa1B1VFlDM0MzODZaSnhnCkFReTd1cXVxZU9tZE9rbzRDZEhE
            dUFCMS9lcnQ5QUtpbkRPaWFXdWhJRFUKLS0tIHFGQ2w5OEVXalNKdmIyZlphdndw
            NmVVayttZUU5aGl4bXFMeXNFTXhwcW8K/ujM/lp7F+XvZaBS6vZ8KpgU3o8QovpB
            he85wbFHYdnM49yofuqjvCfRqNBNYSfZbdLOnEO7tRmLh7k03h5uGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T19:24:03Z"
    mac: ENC[AES256_GCM,data:vTgoTHpshdLMBi8t1p5kFM3hJnbkN6Eqy3fwc5YJFh1rXJvifjKHJ/X0JjePsyAKadEV18R9U0mb1fyqFKmv9dvxQvezig6KRI3HDIPT52pSm9nZo7RIMLvtetLSARz7ph0rt8JNjaw8id9ybaH5p3RHQvVUsSbHRO2iHVCd5D0=,iv:LYDnp7+DjpSePi0KMCJ3fw9rYdbVqmMjUaN7jXMAPok=,tag:6gGO+bCbKh4tAKw+kYob/w==,type:str]
    version: 3.13.1
