apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:qistahWrQF8XhWXgHuUPBrGLi1WvAtgfXLjqYIto5Puv2+Y8Ix44x1OAnUziM0GzLelECwsy9bFFdlaI3Sc=,iv:Av0OzIAYQhDg8ZLTuy9Dn6qAItoLyHkU7hHhA0WjIOE=,tag:kJ/KwoTYoxf5Sq6OzsEU0w==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: hermes
    name: tailscale-auth-token
    namespace: hermes
type: Opaque
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM3VaQXdLL1h4V3VRWDVS
            aUlQTzRNbmNkcXlmUE51R09mSTZ0VDFKK1h3CmlndnVrczRPTkUyUGZiWlpyMTJa
            c3pKUUxkS2w2dXhsckI3Z1NaOUEyUkUKLS0tIGFPRHdXeFhTZkcrZWRENWp1Y3hR
            TVI3eVBDRzZWVFA4N2EwcThSYXRwYkkKSZQ4kDnBXirLsX6+MAYL3aJYH11BaEjO
            kSA1hjYfR4YK2JEWhEufbLlb+58cyPC6HecwsSU74Gweea8sGY0vaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T23:22:44Z"
    mac: ENC[AES256_GCM,data:8E20NZ3qdFf4iwX+WSQurut1Ak+0h7VPVWFzDmRtfEfI9eQpdUirWvbeKhaPtNPktzvu0GIdkW/ZctVzLw86rIynmhCFkdfPnu54T4pvve/hRpo4Brl1yQdk7hB5XFVn8lKWimZ3SntP2M4Cd1XhPOVKoO5tYVtD+FNwQvE5rpU=,iv:O0CnjnmAt09rfcnc8ZsqTnimKh2luDdwdPcF5I95rag=,tag:cBlv7+9kT8dtq2r/duvY0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
