apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:0Ma5wLECJZ+w4IO/IyrnU9u0qXr2ItoHFRcP9dotdLbBJX1J/I96JFJZOd5Whx0FD1dW8yKQXGcs5mgdJ3VaIY3e0c2PJp6Y/zI3lQGVs2eK//3LBxa7YuAcwRiYCZ9iWbFw8/22DB0Ubw+w,iv:b05+XR96gG8bqqvMYx9idNaGEnO/mbkyUBORd4/a0Qk=,tag:F8JwMaTT3qaS3TnZHaqXrQ==,type:str]
    MATRIX_TOKEN: ENC[AES256_GCM,data:MTYjLExpvCFUvG/tAnKP8rMRQwAzoA7kShMZoaGDkQgH2Uwab0Ifgg==,iv:siKFK9XB7eqUIR0VoAX8uDPdN17ULM9iMqAQwKqW/HE=,tag:aVUjSr7p2nL5vspRt/7Ryg==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:UP2uQh4ec20l8sowIusY,iv:JtRVuky0Wzg0fq6etVSWf4Q5ckBjSZ1Z0PiQ3O+YFWw=,tag:33fvOVK7qMx+Zwdkswk6zQ==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:mhDNZxoqpFxFBicb92WgDNt7eOpUHjQoOVHtpi1CKH3joX9gZSsibi0tYcoG3PTxBqk86bSMlggzSHCIhF6iV2v0k8UFEEzGuyJv7TEINS06NhvLsNHPad6Qx23QAwX9EtoQi+jEs0Q/1KKg21sBH4cty+OX1GmQ6EnTv+haQLAM8W2Js6xaZvZ67dOWoQdH41IkZg/D8uRnZra/JSVjOdmwu/MJ4syB/PyfSQzl76SYuQCGwCgKatva08shEVoy74SSgYw/23gYmk8Lz3rr7OMJIDuL7WY5Y3fSmFPUGQUnHoobR6ZS1dQbyFrjK6snMN1kmQ==,iv:A8tnEmMLvpyYb5NOxwgGRlbNFWBmx/a26QASP/MObLw=,tag:SqNOlJ6C5rQ8fV/QrA9z2g==,type:str]
    HA_URL: ENC[AES256_GCM,data:KvntTYjiOq7Z+mtYGR+9MJq6/bPcjR3Csx9j,iv:IBiWP6c+uzN67ccyHR2svCzAticYdO7eHdoFXwFJt90=,tag:u6rZxoh4casA2sEg5/v1Vg==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:fF25wx9UpvXFLdDbVH0=,iv:Mdd+c8jujMEz32IwHqw8oUVa0UnJq/HqhqdwgYVly/4=,tag:Cbo2IB+c0AlSP+bMXKHlBw==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:O41aZMm0/WNb/YXmXUT6MTu6DPI=,iv:OFj0qHQVhUT5QeDrsfZgS/zlpv+2xfljZrSw4a4KvKk=,tag:3y5ZYJTvi4JNgyV6LUfazw==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTzkzNTd2dVRFZFNlQTV3
            WExneHZRck85UU5Id3laNm45Z0lzaVVLclRjCitPYVM5Q3hDaEl3YWRJN2tPUi9G
            aWM2dWtZRi85UUl2ZGdoTEl3bFZsNFUKLS0tIFhHU2FpT041MmNQK05UelF3VW5r
            dHFYWi9EN1d3bUJNU3JZWW5vM1NvK2MKAQmYoZTQASliv1rKnB0bLMFbAdGY1Q6k
            v6qy0L0fXgQcFFInuvE6OF3Zi1JxqqpgrybguN8OAMJUhNAiPlO11g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T07:50:23Z"
    mac: ENC[AES256_GCM,data:YoS7sZ5MuZHS6C1bVk0KeFpsO4vtiAexTv3NsI5CTQ8wz32iZQhehVSyZTvYN/BVkNq5D2NFyHYqviCn6C0UtOHy3oR6YyN3ZSsZdWpoCDZ4XnIivxEWCyqAmyAYWIA9Cq1GhaY6+YZzVswbPnCXUs6TAi3h2rx3ECA0BW1BLWw=,iv:oXKsVshjf+Rd0PAE9d6zczGFD8lk3C6s4NHz7SMsnaQ=,tag:huT1RUxX5NA+W1MkDM5w5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
