apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth-token
    namespace: hermes
    labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: hermes
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:yzwPMwkmQkYhU8Rt7cRrJIc+mTcIUPwMrIRS/huZ0WWXQ1jAGXK4iMI5H68SrZ+iYeOlMb4GqozT0CSbWQ==,iv:lGxyIhe/I88mXv0gnXcQUmczaILPdq7kBGupoe8sAaY=,tag:VS2NYlJJtEfH2HX2ZDhbkQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOVZXVWZ3WUhnREV4UkMv
            aWJ2OEpoVlB3a0crbDY1UVI4dWFKbXRGaGhNCmdGc1UwQ2syM2VOVGJLUFB4dFQ1
            N0NGcE9DY1NEVDdFSkFZaUdjL2xhNDgKLS0tIGVZM3FHSkN2NVJRUUVxVldnOXli
            eGVFQVRNcktIbVg2M1VSOGVGMW1PVlUKN5IUpmJgBP6t30BE16pNKzqNdf8xrlCO
            CvPEjKVb15kDY2tfmKNI3mx+S4kciMrbxGQB9siHqQqb64bZiV+vtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T20:57:18Z"
    mac: ENC[AES256_GCM,data:OMcaO21Z6FSYQqk3I1z+nkpyhFEpWKvjQQ7wK1LG1m9r7Vulx3j5TEMD1yCT710WCDePQqd3PPj3fvtKvfu41f/Q0Q9jGj8xlp/gII3X3G6bw88Rarv87wQeiFB1y0HT/x+K9YHsMgIq9UcCPvpRa/YBF/bRDu7qPmWJtMdvMDo=,iv:1zKCW0zdNENF63SdJufP1109Fpwkdc4NH0ZWTk8YnZw=,tag:Fk+lyyNwZC4YBue/8C6PPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
