apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:ioaxZvc05zG032zTHeu4hSiU5MgkFgRE+oh39BMYF3fnfl/t0FBDlITinWTjVBHMh+l47ywxtM+DCo2mNAQ=,iv:DTXc1r5ABII9Ch3mg0IRrHfNSeZb51vmHNb5QB5tjkE=,tag:mOF0gmQRqPWfTOSRYe2pBQ==,type:str]
kind: Secret
metadata:
    name: tailscale-auth-token
    namespace: hermes
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRDNONHJsbWxnalpoeDNm
            WklWNUIwT2VnU2tkVjBhZXB3THk2bFVzRFY0Ck5EcEZCa1luMS9LSzltVDI5aVRX
            c0RxWWV0azVOVjc0WWNTbnBNbnM3c1UKLS0tIGdLUmEvMWRiYW9KQitGV1JUWWhp
            d0h5V1QvK0c4aTJCa3lPSGVhaW4vU2sK2a/IHUZSHJsvtnFjr4S/rLO8phfLIEbB
            ZfzfgMmbwUbAcCHJn0n8l3WRPuHlSO9xHLHHBNvn8uEOsgqM/AlB6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T16:58:12Z"
    mac: ENC[AES256_GCM,data:dd0dP09XSrFD9nhnjX4+TItoecBWnRlIZNhQqSHpAGhPLpXrGWs8CtzkbAB5ikPMg7QWm/sFxTk4Yd3wv5CBbEdpAkUJ91YEn2WmdRtXn8dg7mLt5Kzzo4chgrYKp0tb/wZ1vk8H8PTVPDzibIFm82noYRiS2WSnVHFgrxEoK0I=,iv:XehKEbiOwzjzOBGdMj+1VPWunfYGOCDdn5A7aJPm9cY=,tag:qUt16l3JEeF7PKfT7sbKCQ==,type:str]
    version: 3.13.3
