apiVersion: v1
kind: Secret
metadata:
    name: hermes-terminal-secrets
    namespace: hermes
type: Opaque
stringData:
    ssh_host_ecdsa_key: ENC[AES256_GCM,data:p+xcF9bxbrBhytBtIOQZCqGc5Ta/Dy83kfw1RVJ5o+clgdEc1Yy5ZLFQduFhir3juEiwXs3G/tuYsSA1Yqiz5ySQv7tAr66P1CT4Q6jfvnPZuVg/SUqzs7Y6WnwECEzS/y/iC9wsmDFBfNA+qScjxvbzLAIaC3Bu04eKgN6b8+DTZYFVoFhkYcWwpkUpLeE0sVNFf3tw+S0HpdtuZLE8p4lxfu6atYDyNwZu8JuVIhJNnplYq3FrUgb0uYewGMDTSipBFN6hrBChXCW/Pskda+lmC8i13KhUlae/I2yHH/BhNxYF0Y4Il08HvUyncCnbrokPm77SOq3DNad9MuD9RAbV44rps3nHT3Q84vSEDgkhnYQdxjOmNcrX5F0wntbMR6E0d1BNK8VW+ZzX2o10csS/JMLTBvwFJju5U8D0V1/JGBYYj3py+/YyQaUh+93GPLFSboZD7FWjWaWQ6edz4zrsBEPSaqHB7AGVog/1RA9VGZOS07KyoQlL3AxAFr2mh4EBAwcEEacTMSNulwJA+LFIOCmcHv5UAZRamw7+LRuOb3YNGpfyZtRdrylqnUqpr7ggIsUcQLxZ80OUR8wO1wCCvlxLA+w14aWIry3ptPg+BQtI2Qy1DeMB6OS0zkX7DE8MwJuhVzXAQrbMx7OpPbvkuaMCnV8C,iv:/9F6rjdv/+PdJkPI41aHZOqZUW33eqPY8Pd7mHPF9Lw=,tag:wpFntOJVJXKPuyDNjKwFCQ==,type:str]
    ssh_host_ecdsa_key.pub: ENC[AES256_GCM,data:6Z0Sy7tj9cOYzunuzK6N4hf+5jm0daDPga4uIwo09YX6WhpYO7jQfWxaBydS7ZYW+c2HTWxN69/i9ULlouoHnyCvNdE7pGgYMZxUa03mKN0GxeH0Db1Rgr3e2KWYIWOA56MabTVGuyjRWI5QJ7k8HcouxJY2QWeUbB7LF5NxLiabzS5rxubPChg/Wmj5wYntyyMzk85VK9Xp6G/zg78ERg==,iv:OVLuZMeR9EVxq12S5Q48ESKOjvo+NdEXVIQ/V8up3Ms=,tag:0CDrDE4NeDj1PQPzKMoA5w==,type:str]
    ssh_host_ed25519_key: ENC[AES256_GCM,data:DUySszvLfK/MbwsizYULXOzZKGoijqitd+xNxHMnhrY3oHzEXsUxrF0s3qxykKG+qY07Pg6z0WYells60DKN4QlxjDGG6k54dNcKFSO7bh+8V8Ncq7Tq8P91VhgEJztQLJE39WP7Koe2rmSN3TcQFUtGixXDUvuIlY1xXlt4IpPvrz9xBpic8AYNKDPYJkY2alThiczx/zohv6YHcNjZKSAQhK3wDfe/cjsmpxJB+50ONQtFoV+LgEZFis2sR5CgVfwks9BVuMBUcRkZuBLyDmcrOjDRhp/qP+28/lbGOL0drBktl9CYXP+S12T77A+9Gy/0Vx4YyF1mLJ9FhGmvGtlAk+na/hj/ubY2bulFI9MtNHGRKx7pipCYTuEWfZegcPjgINRBhO6G1fgJPQsYhAbKO0CwskBO/x/paNM1zWKWhnt9G+Foh9LOWfz79QSm6RdKNJ7Og8WIbpTIMU4sdnlTDge0ir6Kibz3dl1kTG6oRLoYLLSY4Y57F3bVR1leSEoXHo3f/ZsiPcjwJl0=,iv:dSWPAY+LfC/U+zvdRz/3h065CnuikOE7kBn6hOus9Hs=,tag:s9mB3uNPM+0ftbeSq2loMQ==,type:str]
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:qVS+4tMkCgzlNl27AwCNlfBReGS5OzZdiG2EICzf3N3VknYZB+Lfgu25MQFMecRiV5gYOXxNdx3xF3PeDtafiEllj6Pm4PfCor7Vax0ALQg=,iv:9T5tYyxgHoVArD+C0qIp83tdYK12hWhzOW3VatU3eRI=,tag:ETplhrvxA0Yd+1amtrpqtA==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdGwvWGl0Wm1rVHcvZUo2
            cFZ1YXpzYUtwOXh1MytrRHJpSWdIMCtCZ1hvCkxSVHZDeFUxM3dvRlIrSkNCMWI4
            czFteWFIa3dQRmphZ3ZIcjdoaGlEY2sKLS0tIHg4SE5FdG5BRDd2bEFwMndDT3gw
            VXlSRC9IWUNrZUZEVWFvbzJKWEdxNm8Kt3aZ3mV2H+SB4YZRAHMmbake+0bDdQLj
            Ka3LjqNiFQNtJUmYTvE1gf8ELP2dX1vSRpc+xrAZsMTRbTgmB3SvFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T02:03:37Z"
    mac: ENC[AES256_GCM,data:dCYffIKm4+2NMzFAgMg/2FIcq2dtvEI1tTBCjBkvlLDF7lSnKYEP8+JIY5EANi+9FW7hQlrTujw7AmIAwhcdaUrH4fYQNtFTBJ0cQeyYW5kFZabQ9aLFpMqYvq1yqedPJYpiEgILBaax9jI0u7zvt2HUNkv8BmVEIuf3W0zqcAk=,iv:PwjS6E3zhn97F0IjQ5Cre4DR7FjyA6Pc6Q9XeYjYVdA=,tag:zheXWG1NtihJAMQL5yqsbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
