apiVersion: v1
kind: Secret
metadata:
    name: hermes-terminal-secrets
    namespace: hermes
type: Opaque
stringData:
    ssh_host_ecdsa_key: ENC[AES256_GCM,data:thqYJh+cFGUA/nRXA+fdcGqH/PZVGm4bOhyI9zocN9ZK1kbg/kSq48PIvzPfd0ygQ2VZ/BPssklq7nrBV2v8Krih6vqBSu++92jvyOnXja/J5qqyTCn6pAoMf5fSvXlQpnctNjz7wcczckfZg/iTzbmuhduArPPrPB6y34flC4iknM1JSzb0ThoGus6paFsa06eF6DrGuxbuQANwSCBY3ca9AWKC9AGzNopv7j6y95rt9WQAiLOUvnK5082eOLkpPYrJanD2z0wAcJEuQtFz7nnPUDMNudGz9ofA7nip5xQdRL4kaqHAj7RsT2Ho/fqRSdlI87GTBnBhugjLHN4Du4hUM2iDA2CrEtdaITnRfoiIPe0h37OpF99gMQPjJ5h7aZHDQXiss6wNcBSmjnuPvt6X+eUhzHdPdK5ibM9Rr/A7/EKvLyWBYlDQox+9gwMq2FOg0BnVZ4G9WyvJwhaJBwbd0hgAlwDpkCq2warugYOj/KLVUdMMJ5pM0hz38/RESaQQTkkRPiO95Qxg2deTYjabjvl8vIq6bHyWciJYQcaaNo+L0PJ2I/RyL17IvOtN2hECEHTnczyhGW3bs0/6Y+xvqAAjhE18eBR9KNIu2AwlrOim4jmUtin8/v/c6k9IQDU2aXqSulJ6KXp8sBTZYnfw0n0brsU1,iv:iJ1kF1UGaTq67ufj5u5kJaACsa7M4BHRR0aTzZAIJQM=,tag:olsZKSrW3JwHWc9mBaxcsg==,type:str]
    ssh_host_ecdsa_key.pub: ENC[AES256_GCM,data:vXOA0O1kkrO7uA2Ok28fMDjRc5WlU8+5kthCoYa0hRMJEnMN90D6E2ejRmK0H6aZkiZjq9+NA+iCtPS/VKDfmx2wYzLsL5qbzTe+fcIBUgS4hy7zaD8bGKU/01cXeA3KMpCkr7F9SUFc2TdM/HPPUPxy/x4AnJbkSIe0Fp4EE0T+q3pqajJd8sLp6Dk+hXhxTEXdxiC1ie9mzcLdoKXIRQ==,iv:6EklxS8F/F0gwATvm3QZI2aiYQVzICMBmMYY4KrXyHQ=,tag:KrCp/itMKHPuJaD7zDJDBg==,type:str]
    ssh_host_ed25519_key: ENC[AES256_GCM,data:oAYIndscD+y0C6S5cTAI6HceTs91YHlwlPggRQPqPw3vos+DddcfRh4yMluAeF13PdSGPhg62CF9OuukSZeYNHCu97THeMUn3JEL+vzGNWtIBvfFaRoLYLV/EyowIkFff/qnvUeX2AJAoH6joQWf+VaYVEp50U1WXThZ132Bw5mMmkx2JtEGcM7/ZF0gaEp/fQKUwFFWz5BjfIXpWkRkk+mn5m3zpEwMkHt2quI9GyDRJa5usPi6+WR9wQGfA4I2iTcfV2IbiflySXKMhyNiJdtBaIzpaPjaJpkdA/ah9vvYW2It/cV3dMAAmwDX6vsWVJV4XfuD63sXuLLwANvzRWhhbdR/8eTUZDiZfodszj0D6JiG14casyCI/TUk+MneTnlhdl+mT77Dl5faQS0X3G8lU0bHY8Jt+RbQZTKj9gXebc/WLsYd+osHQmf/vVhmY3J+H13UTumFb2Qm9OZGIeUCgUS72PnNCxHYdt+fNjeOpVWIS6UB3hD4Yqg0hVATfKg9XyLE2jnrOsSnriE=,iv:kh/r+OTVpt13NuI38I/85VD9zTDQPRSmjD8n2g8y+5Y=,tag:Yux/FbuBgEgSqUY1xci5pA==,type:str]
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:YeWV4syl6a6dbrQ942Mvr39d8xKZwG9PUaCKQQjWagYtmXVSU/sFB8T5ONhobNImwCa9G5SOy9Kdx1Iu2PvaX980ChTPveDS/6ZPydroY0M=,iv:8p8Ik5+rNK9JTCtBIr7gn9JjN1j6pUNsNNmERW8RV8U=,tag:71m5lN5Amoan70FxA9Pf8A==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SGFleXU1UGYrYjFEb20r
            cWhvOWxYMjYxVTV1b1BBQTdhSnJxUndDN3cwCkdqMHlURTl1NW9WSXAyeHpjaXk5
            Q0Y1VVdmc25oWU9qa2RjcFhiZWkxY2MKLS0tIDVUUzl2eGtmeGVFYitBYTFMVUJp
            a1E2aGdHeFlPc25aUVdHaE9lekljVXMKVK0ha+m9jt5ML17OZTsaBjc4zzkaFI9S
            C6UmUUU4aWAch3A8zFvOFNE9SLzI1ckJmfgmidw7I37sI7floR84iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T05:11:38Z"
    mac: ENC[AES256_GCM,data:PwrwNhRHGqkScsWHURC6p4DA3WaZizWWxk8WG+0hMzRUuvmVyhSy/KDEHCA174qeqw46PyHoH8l9rRvAw5EKU5sh7vIHAh6+3NCTXb66O3ZdjCy76ezyuAg/oR3l5WOcyEXmLJO5SMe356D1EJszgzssFosPx8HOvNoXhngqlnY=,iv:pa7WC6c8qzbjOzQ55JBVbS6dWtL4NDlm16BO5zeDJ0c=,tag:RewM6wuBPjMtcZEu88e66Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
