apiVersion: v1
kind: Secret
metadata:
    name: hermes-google-auth
    namespace: hermes
type: Opaque
data:
    client.json: ENC[AES256_GCM,data:jv/nixv4jcmPyPwBMFbMaE/yyNK2Y+b3X8f9iRYSVpkwxQs4Rdkd8fr0Oc6/TWgi9z4eTz2unpoizqcnGNyvTD64Q5/47J3xRqGRiZvGeP/MD9vkMDql1NUmwnrdGyHxa/yzlm+6tbYMToAoPLfYZMRYTC7ntcXWXyuTRmzLajsBa2vQgn4D6zTESfc6rgoJjcv4MeMV36u1UznvDNow3QoCU+04OJ9SHZ1yzW5mAdNFQpKyQ2aqu2lpZ/95oRmtdDH6sk8Rr6Sl7quqWeKeP9s3nPGTgZch9+2j0kfABikl/dNyHeOA1+oEA1qtB5VnRKMWGPz8jFljsDIbbZv7ev4aPAkcbumYRkjg8VHbxeP5NdZ06Evv/a8ZPhnyVtR+G+Ytwg+E9cz62RCmt8aKaquqU5tFMbrvB8gCBDzoS1K5pt3cjYDlhN5rwCSj8JT7bMUFH6kKCi+fpbBcpyin9eEtvSL1gCLq3rDJL2ijziO5TNxXuYqPBGJmDV/duGnBNiAJm4UomC6LS1N0MIKXJxVUrMQ+ww9RQKSHjTPGdAdLiPivF57u3opvaCDmlvigQsSmQmD4k/ZamjhskeBsFJzF6E3aX+2hOod2LUfZmSdNq5EvWVgvYH0A/cvW6vnZqgFhR9jpajgfph+3fuNwts0pQhziv8wcgFxi6qBp5btxJ9JDmSTDuE0LgF7b3MpyzjbTJvn+C18N7irImjV1z22SJ2RY++26BelwFXk3K0UQj/W9HCbQl2ZVyGCGq7NSrbs8cdHAvUzsPiboGvghmg11L+XAHJJLkWTDdqWJP2+25p4zN2R2akFXmPqaZCuvm94DEUttdYYP6Xo8M34fLLLRnm/61zeqlvBeak2cTWY+31DNVzfX/F2iZVNsFVHw/Mb4JkGbDSdasjeJPwN5vAOklY5qbD/5EmZs14sGovKxw/sPMfrwN8qNMaSC3dqv4Nu7KL6HVXTqdoghtEzej/0rodaaEFTGVeA12dO5AtZHSmBT0w/ujNdqFbTOegPfoROozWlnl3+Jg7MeWE1UVWLG//cjL7p2ATamHlTxbeZAz+uXveILW1sWMgVWUKNtrPaydsKESHpsk6xCrCdGrFwq5/y4Gt+pRCeawCUQUKTcWtmLZRmGl720B7GFi1S6n6Bjphoxh30NxsJSkoMwGQ==,iv:n/c/1DLmf4YCxkUvE76KUWFoVryVm/xBj93mqIijaHY=,tag:yYC3cVJL0R4spv75ETaNbQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeTI2SEZrSVcyRkFxdyth
            Z3cxeWVQUENtVWVGNUx4a3A3UFJPQXBLZGtBCkxHKy94eEpwUC9lNUJjTEJ5SXpV
            Yi8vMmpWZGFuMytQV0E2R0xJR1JudEUKLS0tIG9YYklZSDlZRGlwSC9rVkNlaXZH
            UWZJbDdkV3lFeUZhcGZ1ZHllNnZhaFEKSdw890QJvfbQkgfFKkYI3Vt9Z8DEgagi
            DG0R8Isl37D5252SduUTCirMrNxzjIUdfNWQlBfEQHJujNH5Eh92Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T19:37:54Z"
    mac: ENC[AES256_GCM,data:sETahGtf2ktDzzRRmJwzCYMb+9mwx+6Dq7MLK6TFXgD8a+nc7blXVHNJTXr4n6exxS9Xe5mEg4BOz3jFJ/8ZPrBadWiDa/WCrWKPRAMdvAJrDMM/QkQfkDUatzI6JdRNjJk1zcGBYGtqgonyKdwhmt+7/ppXxTEqfsLpc791xCE=,iv:hMBmOmuei22uZlQ1+WVlHTkIs9YLcvSonvFx9642wPE=,tag:OIJQpx471/CBD++t5YkqLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
