apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:9mSmFar7LwNwgrD8JyipZ1S2u5fTJ2fQWm+vGfs5fkBcyKq/j8dTUKXIkOTksdWmaKXNouLtdQWp0X0dsALiSqfD10H0I7igMW1334u9Hf1PREYboPzY2Bcn0/dGzAEA/taLBZYV+HtUjl+c,iv:yL+uYnNkSi3Zn+iW0s2+VLCLT4ZPmPrdeUuMqPY3IQo=,tag:51JM+BWRVUJfiA3Nq3+VuA==,type:str]
    MATRIX_TOKEN: ENC[AES256_GCM,data:BwyESNoor7vqlnWtaQIL3LQf5+zGPwqcWCx7LI5T4UnZ/k/Py7cdOw==,iv:go0m1fbPu1PH0Hq6eaCubxREVx/tYBDS/KaiOh6GzBM=,tag:/BkBknvFHqic9REULlVFzQ==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:bw8yFoZM7LPD/P/E/Snb,iv:q2rKcLk34GHhqKvNnmwaHI+1XdbjGopPwr0J23Akg50=,tag:mdqEcU7v5AGSgmCPc5eUpw==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:P5Z1QJEMWx3WARnnsVjD,iv:dtjRzaBgpyKt/b6yeJlJFuMYx/OvYJu8LIIgZfG7nW4=,tag:GMB6rjDP3lKafTWkPSVT3w==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:/4az/N84ZAZ5fN50kQ3+fZXxjRElZ6T3vvKsF/JdMTENY586WMNMr+wexJoUsLtfuYo2Nnwhcu1pOsD9BBCdTt9ueuhxsfqsfwuNTrhoYuDretKRsznCyCyWIdGvKZlp9TUXAswbMVma6w//B22L9GJdWXQcNF6ig1wFqmST6Ss4KuyL9t8ZkzDMhvyZ7CvoQo824mZggKi+JQeuO5puid2Ms04Z7Wd9Ei1BwbBvFsn4wa/EXngGxuk2roIcXSQ2ReS+lXb8zOAunHGzAY/vpzCrQkQYYjcJbpQuiPEHpk+Prugky/sI6wBJflFecHmQCADEag==,iv:tuUhnqHCxGMCl5Hs+Ab8MGMUY31aIysDLPeok706Wug=,tag:h4AzD4so4aa/ab6pZr1fKw==,type:str]
    HA_URL: ENC[AES256_GCM,data:UcL+7o6WM1GtYsSzNQDVpEcnMGYLVaKeBwhN,iv:du8CNOqdW/gyr25Je/dSg/JpIud42yH5G7FWySH7x+g=,tag:dafNn5GlsUN8gzt+51U1KQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:QZHvODEy3FC3OkPga5Y=,iv:1BM7ovWqmS4Ikjgd3/eTAliDiqsgi9HZu5IXlBnPptI=,tag:WUBQi58QRg7UrVTH7FgOmg==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:v6wpmmyz0lNLZhLWF6Wy0ykhSjE=,iv:EW8DMmuDT4ensArX3JznCKrDkBKYxxwhp8D5VWiVMNg=,tag:Ieiq913GXknS7wIhX4walQ==,type:str]
    TERMINAL_SSH_KEY: ENC[AES256_GCM,data:F5jfzfA7j8Iyc1cP7TQQQ/l22Jnc//GyA9gA511HDon9yv87t4KH6gzuw/Uyredy9+e+zDFmqKsFdz/U+gb6rxuuMaw+LU29bcMZUN6lpcW7/RK4wffCtvLXkifGiogwMWciNXNVO3k6uhEStpcpkDZOJN5HsQIC2HoBZfQgTESkm1Xk7EYB4mPHu2mVluW2sLw0teIuEclaQfLz6L92DAna3LpnUnbUvgZAIwFGMeTLy8oBpT62xcz+VyOTcc+udePEyUZ1liSl965mXXajsADtmPVbzO+c6T/Dm8ws5AAmJsZsmxdIy3Sx4FYs7fddnszcmFwG+VK/fubMbQ+NOHAgvszsRggO5xN0kWLYm7k52gMfl9/rg7h6Oez+o+qI6z/6GAYmbLFpS92Fey6ZpEOLagwm3Rjjgi5IGApqVx5uu3/1ma40QIqzWvfXqSwNK/RwEc0jOOATzYAJdN6h9qXzMFl6QpaZv4q1H8Bw0AkdZnaP86KCN+6d8u3lYC9rg9zTBB2ekiiH7KVqyYIftnqaSxz++HGH6yFpZGcnep0aDUhf9ZJT4ne14cKB8re1a3hR8iNTMN/6wHO0VvECl1f/sgvdhEvf0fGWntkV9LzYv/KxzNXg8zg5acYLYmkc23RVbOWAl3WuSg9xe/5QG3zH/kK6iTxdbg==,iv:K/xZxw4ZnarjzgWQ26Vo9N+3Xl3EEEw0pTQZsJNDbVI=,tag:uiZyuCASFAod2CoRNO5i1A==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aGEzL3U3Qk96MXRtUVFs
            a2orbDVidTJhYy9CTzMwb0xWbXJaUHBzMG1vCjVqSldHaHlrcVhjbFlwL3AzQVpW
            SGw0ZVFaWGFHRVRpaU5MZ3dDZFVvdDAKLS0tIHpYdHhwdDN3WElVOTNPdThqSytO
            WUJFNW56ZWFtbEV6M3ZaeGlxWGcvWlUKrZ+3x6Rym4RmbPdADzRjqX67VHNujA+w
            4KFihB/gA0WlmOAb8P0ZjZTe5xoQp43WQLIFzx3S55/n2isv6vbI6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T16:08:40Z"
    mac: ENC[AES256_GCM,data:wyC+Mtc9jX0bu5Ss9URupxhrEI+egheeg8Jssa8Wzj4qpwG86pfn+VR3mEe3ptdYnEmvSZMW7ndWUc45nqxSVy8i+vYA+x8Q3rpqxw4KZzHhPAgij7ZMXHPIxy1RNKtM/KJNBGLMuSI1Nc/mZCU+h3KN8izS7tvxC6rh6x62GN4=,iv:FguKrqa4+pKvTvNsQTJR0cnheeIeZS9t9DI3TN7xqcI=,tag:25boOMw8k+2oeh85XsDgKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
