apiVersion: v1
kind: Secret
metadata:
    name: hermes-terminal-secrets
    namespace: hermes
type: Opaque
stringData:
    ssh_host_ecdsa_key: ENC[AES256_GCM,data:d1ccFSB8zyVT+PHb85X7ScT0ZiT44/E6hneBsZJzO7ei2IrBH90TNEe9l7iFDVP1ShPeXKMRkzy8bQxe/BQ8N1OHGNecFEv4majsQFCPsxkiBcLy6e6hiR1foZIvgZQ6PzCeicvrJlAzWgrrZXt/dgLo1kQnoDVIgXmZTHSxQUwzaigyaTblKXZ6YwPCPb1/Kbreb+lm99KC/XU8ixLhx/0IG579yWRG+H4mcLttLfCEOc72IBFYZDrMdtf320r69NwdEH71ht0XATNJIhTTusK8/UIZoSWG6f4pU7LpeqZYbVSNw3jFWNPMiHZrmADTQ6YSCF93hGbQ3gnnCc9fTq7gxX+NIvNwSpcHLlq6Mhujr72KHxU0ARIwWmuKOewEjIQo/DPc67W58HsgYUhl/9gdFqAhGmNcW4qyvmzvQjcKnnmEsFU/RZAEqunhQkp40qFci+Dkkbi13d4O/ZhBq/NpHBDqz30HDUEBXRI9XHrtPrh6mlufwNJvfuipdFlBn/xaPrel0Hbj/GJHLuUYUofAoD4W8vjY8GXdcqUdG4CUnoeuuMtqUfq2Uk+Cbf1Mknmbb4RXmHn2vgwZsOti+hh5VENe85/HSPZEvs+0G+Hr0GePAE+eGP25Zyd6uJwNhEffe8/7fMa+4JQUd9r5F7nNoPPxVyFa/g==,iv:iKN0uteMctXGy0psMfIIKR3gyz9XzGf31SaueVuyS50=,tag:bgHSYw1LCmCt8/HInGzong==,type:str]
    ssh_host_ecdsa_key.pub: ENC[AES256_GCM,data:Q3w40FqXg9aW0MJn1OAbB+KIzbpfzWIwW8u2NqMKs1Fcq38hKWlssgFkW92px14pbSZlZQoUb9YECwQGmKdCo/Y5T1mQWEFPQenE5i8BFfi/YmTi/RXSbl/XLue4aYa901EZZ1OrtfYfJ5F0VpxwGArAoOLtZ2YEozjci9NuZX2L3O9JfMUiujcAXYstrBUvW52uQuRkSwNx7+F910QeIGI=,iv:tdKKFupnUjem9S7vQ6JIX4p+vQ2BFRf6gowdSFSBbZY=,tag:bVYZY4n1e8auApMeC+YZKA==,type:str]
    ssh_host_ed25519_key: ENC[AES256_GCM,data:Z2FvTFiX/TLiERrkaWKLCqg1RCcG1xx6IRSZDJq2/A5yV3HUpYUDKh8S701y+ooKFDCNzEsLPd/LcBkCmEUPkgcU4i6vboRGHvaJzBeCk6+azBwb3ZK1Oub1UKdFv9Ysc+O7cZlsgLbWm0t6sn7+MMv5ShqHp8qyCpLvwWu9ZB+foiTUUOCBq7OY7NmL6gNt65L1ap6vAeUhi4q7G+A/S8AxTJIJYcXlURpWslcFndDTY1wzStuTv81xrejoKzcvdaAeRJc4a86Pr41FYxcuDheq/XSz5sPN5ixCyooQa05zGRn33tm9bCrBgmEEkt38vbmWfDmT8Vr+Me5qrKhjgW1dd3/RkLKuBPiipU8z/SRyn5kubEIyIdwKrSdBcXBSFyL1ZvvydBsi9LLvpxWIV4CN397+OeE8xNliqfaj0ndPPxGSgbqO1+C2bVNXl5YTkEe5Uban97ekxdpYIt8aWwg4JyTcoKLgSBcNAaaRLYmbwxI5duU8ZMkbAzCx9qJDBVkKxkpLGTPRot26oRQK,iv:yuZ1O8LKmKI4QwIijJ7+BQ1Z8WdoGOt0bgHoTcOtOFY=,tag:fTNzrxA2l3B9vsiB2Uk6pw==,type:str]
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:0V3L4EA744gsI9N3ZNEm5YUwYJVzMSSed4mLLJSaHQYrL81qT+jAvTrPElXcKtVA1PQBFPqxoDqm3kRDo9YOsoIYGy/K1Ftcpv2ZzisgZFVz,iv:K6bSNO59BounG8MSs1VZnmAU8XcNMbXypNFDXn1TMDY=,tag:4iZ4eLtz0bDmcrixAXyGeg==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYk1uSzYxbU82bWdOa1B0
            MDk1Y05reDNpemV1Z3pDOHcrYVpIay93b2lNClRjNmFEMnNkenFXWC81SC9iRU9Y
            MzMzRVVSZFpyanVhaC9FMDJxbGlLU2cKLS0tIE1TUmh5N3J2NlFnYTJFUjNzbzZv
            MUN1NGZZSzNQZlViVFc4OStvd2xLTDAKi7w2SVbW3FKeDQemsOckPVDElsnwLHuj
            RQaSnnWsw8PI5pMiBsz19HNTEGqyi9PE19ZCHRRnLYyCjnKDwwfjEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T16:08:50Z"
    mac: ENC[AES256_GCM,data:J5TIQ4W7fxdU2tLJs/T+q3spr+b/Etq4JjAB+NzulkTw8jps/bl5D+SajdsYvUMVj1o+H6lrOVo2u20FvzR0VqUkXjiorc2iv5frr5NBoDEZz3tcqoa7V7Y2Vt2p7UlfFVVHgjTn5HBEJQ9enPy3yE4VmbeGrOBET3fBDxchZZc=,iv:xayMvsaKDnimB0WhvUugwiqAZnY9edcT8UJ8TwRkzt4=,tag:5hfZSbOylo9X10ia8vjIyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
