apiVersion: v1
kind: Secret
metadata:
    name: artemis-api-key
    namespace: hermes
type: Opaque
stringData:
    ARTEMIS_API_SERVER_KEY: ENC[AES256_GCM,data:NOHvpRF+d5dQqiaNUvFcGscExQI7O/ALOQvMTntxC8zGUB6+YdZsgj9F15gZDe5kJ7iDfwdlaKbts40BMyeSsg==,iv:gds6EXXzLqadpu0KjoVapZGwT6O6MG1rRSYSaDTXFWU=,tag:whm9esMOue3oqUVdhaFmJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOclZDRWZuSUgxMTRpTjVD
            SzB4QktkNkkwSlQ5RCtBamxzREVQRVBneEI0Cis3QzR3V1kzMEtVQkVnR3VLZXBN
            UDMyaU1ZMkpsdnpBd2F2RFRidVQxSjQKLS0tIEZzcnNJQ2cxckE4dDRWc29Bc2NK
            OXRMbmdFWnczRWt6VHI3VHRLOWhJZDgKUgbln4nKnqC5PixH+UFe70W9IrdLO+Ko
            AvpjUyDVLGYJxWsVGokKsBJPJ3NqWUT3p4TaoCa105OuC7cJhl7g0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:46:38Z"
    mac: ENC[AES256_GCM,data:tIOSxq7YFsiFSh08Mi7urF7QmlXbWcX+dpYKYxkjuimwlC0dhLxeIih/8tVcM7g+MJ+4uX8Bn+PSG2NzrO8eVzAZ1IuJAdsxQ66IsH5xxGw3GL8BR/MPiLeoF18HmG6ksw/iitIx1hh9SEsdae/5pFi1GQIgZU9hrt0ZlcixCqI=,iv:Mh0W3zKMMhd8IBmXzaukkN9LKHUKdyexXThB/iyBAnM=,tag:6WrtFAP36QQHP1tYyaamGg==,type:str]
    version: 3.13.3
