apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: hindsight
type: Opaque
stringData:
    HINDSIGHT_API_LLM_BASE_URL: ENC[AES256_GCM,data:MuSJsApYjysmWe+z/+lyTOAwRlLPhlT3LkNa3A==,iv:YxMOAiD4dsvv6BhFTEYX7h2+eSra/VntdWkJZgO86oM=,tag:M0FpJ8edYNzBkul88g7rRA==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:vl3fPq6goW+ePED2snubUmv3BoeOUy40m8e93zeaIXURS3pFr0tlCz/PmvcLjBfpCjI8ylD8XFIluJ/+e/G5b+M58UoHMhTrPg==,iv:hdYzLY6wuHO/aJ53L2RTTH5IY2kDxTAXDlGjAazOW1c=,tag:rxqSF2wg+HPRcwOwR5LLAA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CcURNBBzUpzCv8FUIRCSQF4K2JjcW3ttRrH4f8Bo,iv:nZCzi0ShG3Z+Utg07BpBuIcR5VnXJRSrDHsgm4KFVhI=,tag:FvxPIRVXfGlMIFrMqCoX+g==,type:str]
    HINDSIGHT_CP_ACCESS_KEY: ENC[AES256_GCM,data:n4EjJ+v5Go8x9LQZz9djRlYSNgQ/3yUYwnXPazRuEoJe33nAz9/yTJ03YzuYlCMLffVFLBqm4EDDevLuoX7dhA==,iv:Oq9oQyDi4vYpcfVmT5MilSNcWA0XZVn5Q/3fM6eZm+g=,tag:eK1R3FA5UXRD5pBG2ZAXpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TDhiSnBsMjAzVFprcHFw
            ckFTUkl4cFRzSTZJOXo1eGVFbW5LYzd1VGcwCjRBVEJtN280eU9yZlFvNXQzbldW
            ZENPWlBoRzdwUXI4QkljUHNsK3I2WDQKLS0tIG4vUkxjamdHelBva0pvK2hCckFH
            ejQ4ZUl1Q0lGd1FYYUZ2L3ZJNTdsVDAKm6pm3Eq0/CajX7K4wJfCnDChBSni09tw
            DRfTSU1GBmR9N/SICN4ywn/1RBEP2UyeIzkf5MD/mclwwOpFeHW3aA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T06:42:44Z"
    mac: ENC[AES256_GCM,data:Xl+voUrvU8fN/Yrrdsq2TUJqoI8VrIZCEGuMcDkbCeA6+PCUbNEecnGOkqh7cKW+9+vz0wIhqa0ZbaslN1TJsWbfBlu6DCYewKjet0hIdcFTFrEx+im+YO9euRUuLaFUsbH3fNyUjJtUoCXfDbP/Fq/oeczA+2k3rDpzSOh8fb0=,iv:a8N+fjE8BAep3Ihw1MNjIyqNVgv5okBt39tTpY4hE8M=,tag:H21+9DXvNKhxy0k0RGqzgw==,type:str]
    version: 3.13.1
