apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: hindsight
type: Opaque
data:
    HINDSIGHT_API_LLM_BASE_URL: ENC[AES256_GCM,data:OLNbzk0/qoaoTysSKP8vck3k1M4QbQTdZBC9cA==,iv:ORy3nfaQQNm6nIXrGfptKb3L/tGl2LzFtz7dXIK3FgY=,tag:DlC4dkkxfCzbKIEFgZJ7+Q==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:lT2QRzZGqJ1mMT3hdlXEYTKbs5/k5fJH3FbrXeqlF6UpjNUVpU1uJM8lk9iYZC+i5ECzaD1FhMLE3sMCDwaB7UXyTCG4CeG4yQ==,iv:Q7zB+RFps5DdwVzu3yzMQ9WtBOfbZzHwpaqjmguaptA=,tag:B7HaPxjgTwzEFCMcljk/eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdS9BUW0wZCtobWE2eW9L
            Tzk5YVo1SUp3aDhDTzZ4M3padC84SGE2TWhnCkpMcDRGTzJtaUZmNmlMNlFsbG53
            ZCtja0Z1TjJNeFY0aW83RElySU8vVnMKLS0tIDBNRk1uZHBhYm5wenUycWxSU1Qx
            R3NERElCelc5K3lpUWt6RTJBaEExalkKwkFI1EgB0s/Py9lJ1QXVnlV+T3VB1+ue
            Y80NwjrWgokYKduwV4mHltS8DnDKzk5Y+mwoxrFxw+7t90LBSXGlyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T05:29:51Z"
    mac: ENC[AES256_GCM,data:Y6I6+YKT9if9EgHeYUlsuOro4kUins+kXnH2XcWaHKbXvMcYnai0Qv1pqR2ruvkmqc3yzhEcx1QAi3HvxJUrgqb48waWVn2EpcG91s6xoW0AiVcGXotqBhJ0t+HA2+QReHf+LI3R18CvbirD9zQJyD1iwmdUZhsAitBjXGWT3jw=,iv:aljv4UrbVZA4PlTYF5yNDwcgBAS1ilJUP6/srsABEtc=,tag:DaCbnExT8EN7IQIUUvEvHg==,type:str]
    version: 3.13.1
