apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: hindsight
type: Opaque
stringData:
    HINDSIGHT_API_LLM_BASE_URL: ENC[AES256_GCM,data:tC0nIBEh1xN65+si/aG53lr311lCKQOrq+KAPA==,iv:RmjOJx6MjRCmQMgn7SRH71/htjQK1pThLEMKc3QwHoI=,tag:FPRzVa/A4UVXY/XOEYxFqQ==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:cuuDlBw/nysj897APlZk6S5rN+uJeWvkfF1vhTjJV8yNRyKLtQSjQOXWu8msT57F0lsIw3YV0GZfsL+p/CkvfqUGuvJmTaIXCg==,iv:toO09qPTS6Cso0EJ/CS6S6Kq8AJTjfCqSMWUz3EIiRE=,tag:lUWxlpbiwASvcKaOGprLTQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7fvUB9IleCQ2Bx0c+oTlMtf/FntdGi89NIiGWQQg,iv:CX3I1CMSq5GQLtvy3Lj5/nvKK8dhapT2wgtKVuCxYD0=,tag:Rxu5JemkcVgUGaat2eKjlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURGZIWEQzUHpvSW5lWTFs
            cnJjaFpueWR6YjZscTJ5YVJDRGR1cDlaL0FBCkhJdFFlRjRIVk9tdTFzVDlTMXR3
            ZWxUVDFxeEdVSktBQ3dybVJTM20vVE0KLS0tIGw2Sk5YV3ZHVjdBdkgyVHk1Snlu
            Ym52azI1ZGpiejNEUjhGYVNrNUQ0UXcKORJoJKZujKGc+Yx31W66zvDKz2iRArWF
            9+xtiwc34MXNcibOzZYPrwtw8fhNwTX6K0UkeBe4VVQlRdnviMnRxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T05:50:47Z"
    mac: ENC[AES256_GCM,data:uJXfo+Ev/izDjljDpCU1f4NArg8lHG0HR8eKwRMuSnkYHMTAaP3rHg4+ttQRif8UYnLL0+xOX133KxHg8Gy9FKnsdP0XxZgM82KSHp60wJ6WGyB6/GsC7tsD6TNPFU8NGkU8zB7RfYqoI2t4HIzdSkgRb5LEcV5CMbu40UQvdKM=,iv:i2/lHThDmrZ7qrg/nNuJYQsDNOL+aOXADzbUnslXCYM=,tag:A5iVbGklUOGB/DyIZrQAXA==,type:str]
    version: 3.13.1
