apiVersion: v1
data:
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:hhor3rllQvdqJZc+YVgaojBpJLSESwH1nrxpyh6+kIBoRBbtGNTjGmv0dbk=,iv:+dAEWp5WJaCa5nHsa1ipOfmPMjKycTJsnY65set4oUI=,tag:T12xrtLtAUCNl5yCFaBChw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:wR50LS2MnsHk5ALnhgRxnfVsEkYq7+4/cWBUs2dqS+tGE0OsHzFzCC4HQfA=,iv:iQ7bkvmc+2mGtvRHuWZNV7erZ3aTb584CY6aj6B9jnM=,tag:azb6yMPJzBe5aAzGVWIGgg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:T0927RtjqJXiqAtbV3xX5jLwRFvaJsFFGUQXwpUnnXCIfZ16cVjcV6+MAMU=,iv:AXRKOltXdrwFye2/1W1/Hsf/RYLLoJT7cG3wpU0/zwA=,tag:Diz4+XISOk98migWxEaqsA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:OPEn4l6ngTZ7uxkq,iv:I4PLo3jAKQ10RzVXMfnXCLmTjHyagwasTuxJ77HyGXU=,tag:CDrS7kSZZGPchPDiBhBavg==,type:str]
    MONGODB_PASSWORD: ENC[AES256_GCM,data:WyMhR2bXOh21XHteHGRVzaVt1YHCmvf65iw5aUQDI77f8x9wvdPuMT1qszU=,iv:FUaoDfPtWx7usnVKImCRZ/NY94QNwfZlXQTkme2rkLg=,tag:VO8HPUbR48wlg4xc5Lishg==,type:str]
    MONGODB_USERNAME: ENC[AES256_GCM,data:NwqOQxzJCTx0HpkF,iv:qJ53Rrq++lowQMVRClo/EjUGgXgOqAJjz7dt6Dh1ZUc=,tag:mPAvCeO/aqIvX2lfGDvdLw==,type:str]
    OPENID_BUTTON_LABEL: ENC[AES256_GCM,data:O8/EuvkqBuhjrz2J,iv:jHBEfuFTL5WCRBtO3scadNgyk+v1Gds6nxVDxAjeV6c=,tag:14NbyoCxojErz7XI8EmZlA==,type:str]
    OPENID_CALLBACK_URL: ENC[AES256_GCM,data:XqYXbdfpxFXMRt8G2IgL+W50Yr7j7XW0r9uQongUk7A=,iv:TCUQxyuL5wn5rAgATjEU7TCbJbn5lHwZJKSE9bIx28M=,tag:4f6ZfpmclDD0FLqaYDxUiQ==,type:str]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:DwCMvS9J7ynRhkTCueiYrdzJBNOAqpkMwroUZ7MM3ZEzxGqz47hYOaltkfXbTkzzhju+ZPDfes4=,iv:B7uTInsuAkjqLIYY3WAMsX33bpm4AFHe3M2SlMQZxMU=,tag:x+WB+sFumayAAQ4uYPS5JQ==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:eYDdD8HgJkSRJFNd5JadORbgssQnkGPwYHvoEdWKbL1ms/QjfyABL2DmVLAORqN7Mjpc4+GXG9JUpsT8J+8Hi+iNj8xKtHh4QdLZubLQgGblfO0X2Pg4MBV9QLBSsYCwkdK8dSRLx/M8EEcqq45xAp55Bbt32evd7xSxS9PWqNZwFKtKOeWLtcJnajcr68yYIBXbGtjcHhlTl2L1jjng89c3790aXz7xMwt7gw==,iv:XejFrjyP030Tsz1mpFRqAEV6Q4OPMFybkRf21mb6nm8=,tag:270mekIJK5eSfnPl5paWww==,type:str]
    OPENID_IMAGE_URL: ENC[AES256_GCM,data:r1D2lajzkgRD1VNGBItoKMESOrpR8zwSHb75QsFalUmcODnLci2UvUlRs8cKx4Y5lakpcmZLJkjsiGIoHzmnFaG8DpTz/0frD/brqRnpERY=,iv:nf7lFoQuBlVIDa9cueMctCXtRMg33Ww9oVFurGeOlvA=,tag:lxN8KSscnUf2TiRXlo/QKw==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:pXMwaGsYSQzLqw132xYVRbvRGBjXGGQIRJpBo2ExjCUyhmiB2+9DBsHNMItEYPN459S+lMHlzbMYfV8ex82QewxFvsY4PRYR8RT9yFnGm4nx+GFYR+I6etxBTPhbEQEzMxotjemaKYsu94nBKt/vreoSm0/lfdQBY2VM4A==,iv:SdgHX28nI/T7qHLv5ip3rBl++ROTxmSMxVY7h8G7OlQ=,tag:4pCs9KoLI/jU0mi3+n2RTg==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:TceDyqcIn46RnwhnkK98tCq184WnQkGdmhFHiQ==,iv:7v97CO4EYFXLalusPH7B8cg2ho4+qo62NYMEbC+lzGE=,tag:FWVb6d0LBFG1wmFr9sZEtw==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:0iEHUxftZhBcFpWzYpokYDkMaJmu2mjfldmhlzSm83ZgWgvrkk1wkNkuQjg=,iv:dcrYQNzXHRu3y39GFzLk+IJ0vRrCl4ZopJm9/UQXtSs=,tag:agPAB2mqYXov3PT1p4NQ6A==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:eAP+pi9Wg0vb7j1s,iv:x7U8jBPoXUxNCi8/dBdMeQO6pEtxhKzBj+Ugl9rgbm8=,tag:VgRqd2HSwih10OudnMdzSg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QZdq6T0QM3jwVzmnCIkRZsA9X0ahnUheCLWuDyM5oP2vcUPh9vaH3/DNKyI=,iv:iYat4AEJMv2DOkDRadlp62Gh9cx4yy3j7zq8vHZVG+Y=,tag:A8CgTfyRxgBYd2PxDe/l9Q==,type:str]
    OPENVIKING_API_KEY: ENC[AES256_GCM,data:quk+TgNHwKPlXVAHX3Mqt3LOZEF++rXhW/m/4MaZ1cnqKB6kJ4P+9+6CKtNl1ERawWZc6M+GYc39yRUmmZoe7w6nSyZdDGpp5kf3xWMvYVa9klkRqUQn5xZH4eHp6w7tKhqpn6SJsO3ANQiN+vzYqQSO+RlJmgitK0yJwHzAJo+nFvl4Y8qRT5+YEE7zpdCjuwgmk9HfJC9GR+Q/nvKHXSnPBi0=,iv:JNXs4AhaMFmkOPjgAUtSJS/fLKmUYm466wR1yUFuq44=,tag:QraHLsiI7yHPlYWXwE+rJQ==,type:str]
kind: Secret
metadata:
    name: librechat-private
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSjZwQWxPTjNLejZIRmp5
            L1MvdFNIb05CeXh3b2J2WGpIMkZyMTArZ3lBCkd6dE5qbEtNYWYwTE56bFZVVHFv
            bDVLNEVzdUJwMWhNdWN0bzZ4czV6cFEKLS0tIDdkbjVhS0hiMzFIUmxxQ3Z3NEhw
            SUxFN0krYlFYa2FFR25IQWFaMi9QdkEKdeTjZ8upg2FKNPr4Q5EmprAvRMF8uPql
            k/kgpSbLuKw9vj44lCyDV9YyQfo74sPJpaRr1S/N6eb+eKKTjoUqMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T06:53:29Z"
    mac: ENC[AES256_GCM,data:MaBK9ntujLXE7OzvDPa9EBTRvGOdVw16VPEBvVsr/M4V2OxdWRxhvA69JwbllpSjS4rVC6L3HRFa4hdwqs2m3TNH81gopMx/MKsoqzNynrAzt03+5n1xgO7wVIuVXcyfVnUVbZyzs6vxpyAVzOY+TzQvokJrly/pjoMOFftUTsg=,iv:WXXn52/5JTE9IlKcCYKLc9bMeKIPZoddcRrNSaJrqXM=,tag:6DIyKfuZne00+aQwTn+sZQ==,type:str]
    version: 3.13.3
