apiVersion: v1
kind: Secret
metadata:
    name: librechat-private-hindsight-secrets
    namespace: librechat-private
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ypq93MW0yxreayNI0jHqBbo1vIUE2uuIFqiL0dGb+4JlWSAWY7tRWt7bqlEYoDBWeC27OGEXyXt6/0WWoQ57qA==,iv:aj9OggxpsVJMNzrUylaR5T6Xk44IorxryDOuaawS0lo=,tag:qyQFc5fwzKIq/06MLZFPYw==,type:str]
    HINDSIGHT_CP_ACCESS_KEY: ENC[AES256_GCM,data:xLpw1hAWmvizpFqru/NEHDs8sWxr9tC15aMp+zw0Du2jvXuGdZXgrpD7mkpGOfFT6Xk0A6ozixVO4K1tCKVqKA==,iv:D9IX3OBTvK6iVqqEQMd1hH0OuwT5aMbtffWmuD3YmRU=,tag:6P2ad4xBoJF+S6y/A3cp3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeTEyVTJzaEJHczVlZWor
            R3pjMThpVlJ4UlAzVEg5RlVMd2p1WVA5dGpNCmdlUTE1amZZT3pRK2paTzVUa3Vn
            SUo3WkNjVHdWeU5JeHV0WlZ3Y3FsL2MKLS0tIHJ3MGhnek1ESlI2Mm1EWG8ra2NS
            UHV5QTZLeEttMmh1QjFER3o2a0QyOFkKqZNRBeOEsftn1+k4r9qFUQi7hxxlrCHA
            L6r4XCAwjbSoo2r0xGD+rJIxe2SGHwEojq1TDsd32LE0zolEOY69fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T06:33:10Z"
    mac: ENC[AES256_GCM,data:+6JDhyZr3j4//bQ5MTbG6WTINWC293EEyO1tUYTxwYjUuKsZQT5DzgLJQpQEXZdTrMcUAtJpapv90SSN02r9fUvotSELN5FLkv1noHc2GACdraSDbtyMBT6Vn2Mcu8imIlrO8CtXKt2pzgNbUf1tjyZSVaBtKJ54zkZR0f8RtcY=,iv:NolDFUP0mlHDFiAz8J6+IxZf51IuqaTgV/2T4tiRxYk=,tag:8tDPpIkpzect5uhO7So99Q==,type:str]
    version: 3.13.3
