apiVersion: v1
kind: Secret
metadata:
    name: marquee-secrets
    namespace: arr
type: Opaque
data:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:Gjz4b93ghyHJpgfHPlwYcqv6ynwdUN9snv7L7FxIWgGOzA0M8Uv1YUbwmaQ=,iv:HOtC0JDse6N/sh6uCpb+MTUWUNkr3X+3zrTKuc6/jzk=,tag:lGjYrAXwM+oh/i7EYtCFcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VWRXRFMrSzRYaXJEUjNl
            d0RMU210c1lGVXZURVlLbU5US1VHaVcrS0JJCkJZMFhBU2gvRE9SQUlkaTRzV21W
            eC8wcnQrc2IvRE9STmQ5bFpHM3VCM3MKLS0tIHNVQzFSaW9FWWI4bGd2aUR4M1Vo
            bFNIMzVmQTlRZ3hBMXBSMWoreU8rNXcKEivR2XuaAmva6PhSlGnrgwsFRdXuSigG
            2KNRZK6nhu/jdFPN08jtHBblvmkHvLcCDqWHPVUA5NfEA2W9C77/9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T06:11:47Z"
    mac: ENC[AES256_GCM,data:raLbtQ0E+cWi022GrfE78TgWijN3CPmJkJDBsdTmUTJKtehT/fXtFHOPE4dZHQZbf0rNYzwxPYaMkB78U1/IDBwcJN8+L0qR749/uWEah6/DIy0Swh/LMcEyyHoHbUHd8xSxuvnbtc/BBWCBABK77H92wGtV5vPF4N8qC7vAoe8=,iv:p6icVBPKmikvRx0wUTTcd5Z/TajouViDucn9sjXB28M=,tag:UFYWtjwfVn4Xls6Gf9xujw==,type:str]
    version: 3.13.1
