apiVersion: v1
kind: Secret
metadata:
    name: marquee-secrets
    namespace: arr
type: Opaque
data:
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:pgdjAYVYsZ+46tmEe2BfjDCkLtotEUU2iza8wIDqAOBmtwwsLL1QW0igudQ=,iv:Zu3vjFp+hi5307gjGP+u5qEFBZSZnJiksban1YiHEfk=,tag:AvSBz2ioueBCtk9Hld/TQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cFlDUXBsZml2WHJ1SnpU
            K243RlRZMzMvdE43Nmp5YkFtRTlRQ2ZwRGpjCmNBSWNIOFovYjRPRnErRjJpY2NP
            bjV5N1JJRDRSUDJyK2xwalVUS1EzYnMKLS0tIHZwdzF6SWNlQmNyNXZNWXlEUzJR
            N3VRaytwb0c4MDR5OS9XaDc1T1N3TFkKLF4wrkk+Hwu8lxWctTLDb4eayAlbPYBl
            Y9psQ5T7RQC1XzSNxMY5KPh9/WFvPGGL3gnIX9DdHVVsYWiHtilnOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T06:17:02Z"
    mac: ENC[AES256_GCM,data:wEFiMSwe5P7xsUdR+xyqTCysS0PeC6ITp0YH78NnAPliimPGyBLasqdm6I0s6kwq5tJB6+I3KTW9xwJPFlon7OjDB4yJIBlHwfrR6RgCv9UIqugOWiw7IgtQkSYVi0dhXSyumDBNyd72iflY8cHma8zGJhNxTkoO7L4V8zoPVFc=,iv:yMfBh4o1593cJohzE+OzWl2LsY93eoWOpq2Iuw8qRIg=,tag:QxvkOLuwjnquz2QCzC3A0A==,type:str]
    version: 3.13.1
