apiVersion: v1
kind: Secret
metadata:
    name: icecast-secrets
    namespace: mopidy
type: Opaque
data:
    ICECAST_SOURCE_PASSWORD: ENC[AES256_GCM,data:/n1SyNZbvLxcpjDBHNq1N1D4xnXvJXAh,iv:ILODz2GhoATNHdOvunCCYy1Vz0zl5DWqzXjKw9jy4b8=,tag:H2IqFzf62aMMRTaqMNAG7g==,type:str]
    ICECAST_ADMIN_PASSWORD: ENC[AES256_GCM,data:cBKfzgZdeUtmtA6iwGvS7huX+eW61WBg,iv:Ak1hUB+hP2ZjJiXz9raPtXzwt6AObOF4UtwLV2LLRyQ=,tag:WIa1+D3YaHyx6PTVVxdbgw==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjenh2dXRxNFBpWWVlNkF3
            VGlQZmE3UlBLWklscERyMlAxSmcybEpiM3prCk4wcmJmVCtOUWRWSjZ3MkNwT3dz
            NTZRTHVKTjVvN2w2dW1hK3c2Vk9NM28KLS0tIHRuNGU1ZE5TOGRNS1dDTDJYNVAw
            UC9KQUhoL3MrMU92V2szVUtYYUpQWk0KApCHupVqk+tmFQIOsKZpHOi2nt+/Y4/4
            jTeZtF/AZacBDc9sHFLvpbp0XQS+UlXMEEUvvUl7VkbQyu1I3/iZIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T19:16:39Z"
    mac: ENC[AES256_GCM,data:ZQF0A+DicRq1WFPzwT75YJI6zF28U2yWYm68tXL1FMLLHn+3iFjK/IwnPTRUHYT4DAzTMWtPEgBtq/crk2OpoRDKfdOWpJsmnPiByLVVqVK7K3SW8ULcvDwW1fG7E/tq0IXFmrnzdX8jYXnfVO9aQmHXUJm/O9R3cvx8N+R3BoY=,iv:CrPXmsAF1GC9NZHgufHPuTW/OrKt3Hbk/X/7GIl7bXw=,tag:SwubXJp2HdoVNvh4nUlzuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
