apiVersion: v1
data:
    token: ENC[AES256_GCM,data:3oj1IFLQ9vNlL2bmYQf9Sx0J9Q8WeLucWBLZSQWP2+atcMJF3Scm5MWM/fy0IWn8s1ltBzjWaek=,iv:Mp2gKZa8JzQr66NCeDMN7bnqWAC9Cda247zQNdC8pnk=,tag:zPRViZkyA6qGIAiSYHzJJA==,type:str]
    user: ENC[AES256_GCM,data:KZq9BIzYC/BY8p9HSnCC2A==,iv:xpN1wYoM3r1NZmVOv+gn9UOr43n3eg+O1odMuDgIN/M=,tag:T13q9/JLL49nfr5F/JWRjA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: name-api-production-token
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtcu5zqsxdpv2p5gvyrn335kc5hf8qng6ydp09nnwyecm37rsy9s50tg7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb1ptVUYzSWlwS3cwSVg0
            Qjd0Z0NMb3h5b1NLaU9TK2paTWlsU3FNNWtjClpKQ2FzeWdSYVRHTDVlR08rYml5
            cTc0SjVEWUVZLzVPb0hQNG9uM2pKTjgKLS0tIFR3ck4xRDg4N2FWWVE4dFd1b2NM
            VjVNVXQvQlVUbG5TVkJFWWRKSll6Y3cKTj3Hp6qkj+BMBPcP6NpsTauZPxMDbXza
            t8DA1lTcZwo5ps4vkUUwobm9zFw5tXJPViwmCnBXr2anAWo2W4neEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-03T18:25:30Z"
    mac: ENC[AES256_GCM,data:/WZrF4naCwnf1QSQ34ajSxOZei9rRPI3YyyEiRW6Vay7ldUmQebgcK99fau9JjhXSS3wG6sXmmW+WXRpAYWxD1riwm5Z2Nc4PSFR9M9twhGHpcmTxbR/4LE2cTPJQXgwzXL91nz4DVWz1eZybW1JXdmwoMnT3LPjIflaQkRGDCE=,iv:tZpkBjHw0dBnZ+8Ptj01MebaX89RkkXYwp3G+SYe4zI=,tag:aazpADWo/NSgrqCk9WM3pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
