apiVersion: v1
metadata:
    name: nanoclaw-secret-files
    namespace: nanoclaw
kind: Secret
data:
    openclaw_ecdsa: ENC[AES256_GCM,data:xocy6ioWhJX1Ojoxwr3b8fln8v3Kf3fjKTMzyqiLqLwGBUT13fO7Z+RClleNxf24nSm4TdpUPaOU+EV9IdNMVdTeBQKrC9NEzzikw63Yzpi7QSGKVvsvrjsRrWTGbs/F8v5y14UYvP4BY1noRQFq0ZUsVU7/0IIAXnsf2uZejfbrIlg6uk/sgb1IT+eHGqaztz+YeN018bOrXpuftEerRP0WRLADJGX1RU/c+8zbl/UbZbdi6F+L2wNIg5/nhmppEp/wZdn/dhxrT9pjDPgnQaN9tD9Q/Pnvih1rbqLy2tgQyPo28Rv2h6OyJgNiGiyAr6YRgQzffS2ffmSOm/DHk8GW7ayEoFpK9+iw+XKm7nFWiG4+GzP/tGoW89j02fXzM5bb2zxRtAWkKXSXOvnUGkdlVxL/HQi4NWUPwkvN/6dQAIvAyb6nfHoZNhGxVUT7aenqhv2mKLqwDxQLYVezqMZbW6cfmJsREncMYW1XpPDorOBYCjr5UcZQ/tbfgK5mA1WQIpVW8dyOtACeiQ2fthPvrarYdNwGLibF7W6wK0ptBCifAOJ08b6udeQcTLdt+Bn4jkHOBJ6mqOhOozeIOnqCsczDAz0cZOeZ6DirSuNyizJ8FJii0FWwX6hIeTaQzFPrFe0amO+P8m9VfOJXaxOdehmZL1SwOyRvucW1htghI8Frqur6PgjIV8gaST3d1A15IrexcpEsbZ8LCq78ymRgp8WsooBCpdzRCKFfL1rL1c72qLppmUGBkQdnzEMHBKR7YEvbRhKzQZakCmZDkGZEDuTWh05IZd5I31pQWHENABp145h5LVuzmqfu3eunKmtV5MI7YD1VoHhBaph78XptGlbcLKTVVWZUOqH57m819L87mWUGLNaxIFDigVcl231i7A==,iv:JwpRWbL5bbPCgeGf+wY4ao7aQbwgBZkBKuZqLzck15k=,tag:mfiNMY5Y2dZtrUvsuZeKXw==,type:str]
    openclaw_ecdsa.pub: ENC[AES256_GCM,data:XxSCqlXmEBdrKre4V1KbuZUUcRaf6uUk/d3bMWlMiLGyM+IgEOqt2v7bnKBaQhr8UYDD/KV+V02oN9ixZUYUpK4ztA7yFEQLsY9nDyR0XXq5r7K51ITEZTRIRwBSFwnsO820TJdxYnKfYm3HNk4t0kayJmEh6+BINDHyPdb4P15OAoKiU1XSA+LswyJkqD92p+yi0Ye+LE443qXBra+CY3ihgMa8Py9d0lh6yV637jIZHBulzeOgcmXiYtT836XHwVz/dugvZE8y/GgTe8Ly8w9qPoxU1f32,iv:+hp4KQJaI2JYuuL2LKekEPYvhBW7UDdJJFP4sRCUVBw=,tag:LqsIKxKtfR1sX3E+8F8fYw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUk5DMkJSZTNyb0loQndI
            QXFUOFpBMjluKzdkUGpNU0k2SjVPNW9zTTJjCm15aUxIQWRka29LWlJDR3BiV0Np
            WnF4WWNTVThoRUJBSFJmR0RWdkxQcDQKLS0tIC9KSGw2ZzMwNmYyeWpFMkhKakx6
            MWJrZXpMNkVZbDllZ3ZrSUI5cnJiSjAK0Q4xnHFTt05OAyY1ST4xymGbS5z8gXnM
            0b6+jzeLKjEnzx+xQTsVPe7b/B4TihpBTQGmyWuc49e9T4ZWMrhEKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:19:12Z"
    mac: ENC[AES256_GCM,data:TAIDOVHcq9Iuk0+0W+iEI6NYt9SZI3brBwoJ00b2UpR0ZxCMXvB3Bz1reFF2DmXPjQ6R1/rfYoucQsBmYJo2CDGBzPxSOQUoNMtWMlSTA1MMTeny9AmnUCPz9rwHHzqPTMvh3rCUEipj8+0t8SRPa3FVcWNVdB3reSQXfhd0sG8=,iv:TL6Is2/D12fGbRnOrsYHfY47XhNkYAvbbUUiUCpj7wA=,tag:4wWnIKtfnmtLoDnxADFxLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
