apiVersion: v1
metadata:
    name: nanoclaw-secret-files
    namespace: nanoclaw
kind: Secret
data:
    nanoclaw_ecdsa: ENC[AES256_GCM,data:Ys/xcQhtXfZphxG4J12kdCUbeB2r33gzCSmo1xSqD+ZyYn2E98CcUoMlmndgMLBuiP1c0wDYjEfYPKIKkLjnQZingmJKoNcnXMvKqDa5icooVtRy8VXG6mMgxj+i1KkL+dh8Ed8fXC8n32O/RSLiDq1lwEdMnjAFZILxZotxJ5vLf3cMLXkCmfwtMdvtwVdj0BSNHSCNSrQvP+GfN0mFG/OwFsZ5hYI3KtN59jJF9PgD/ePsedV4sSHLfOf2wbVr2uc/8uZJdXR7Sl+7xqz9bMr+3Vpuw1GdO3/Y/kFTyxODZxIivimOribwdSpUKKgQl1TCKA0BjTcWyNAsfR4CpDOhUR0GaZcTeUhF0YEsp94BQJAx+PDNSaP3Ft3VBdty7g8dW7qXrVkc5I/nrrSPR2w2fZ2qrzqp54OolyxS52H9ZjQu8pJBhFKAd8bcEM9CTFdStz9Vzay7iwh9nXPYiGvohu232tjJ4+X6IXQQpOtBI1aNH71IpT62B7DaacT6+OoEqUNnx27VegrtxV+3/LnVqcphep9iYfMMAh91ftWuPi+41tuVgEyppMge7xQk7EPdYyAUSUs9CK/B0CPdZ7sJWk+8G10km+oK72bBtFv5+LzFDzGcWw5c9n0/6hKtnA57e1UbH9Yjx+c2XUM2RSwz8A6qMS/ZF43LlYFJJnxvrrjF/XITiwrsG5uFZlKkN6zYAw4iGz1riLMJKBL8z2Z5wfIzczwQyG3J46ezjghnDRpM1kiHUfRQ7FecisQq6yv2i1f63fC/TMnf8Nsup/djC82mHY63PZj/B5mUJ8zDxqQ+PBGJ4nv93ySWmBF88M3QeUIwYcH8z8YEYqglbRBvmft54BYVRLBT1ZCm4WW/7jZHh7wtASlWhn8KButFd1VQHQ==,iv:iQ2kKwUzaxGGK3fr2YSD1ODJkWE7VBmoS1j1nJyJow4=,tag:L76GeLaUf4QMcXJVX3XM0A==,type:str]
    nanoclaw_ecdsa.pub: ENC[AES256_GCM,data:GTzmfK8EonyrfEe48LcVrCiS3kmiimVgdWeseugnPlRokElsZVokjovYKCWs7U1aBcHCK+IDybLnrWm6ni80FnM+/Z7hducTkZKndnNvSmfNDKcuToiQzOsFgPQFs0YsJWI0lk6F4Wg7Yy5PgKZr/2ZyliE9z0I3FsbebexJTcGGuQHKPQv4C9Zi7xs8VueZ362GhW77n+URUt6eZMNj7wwpW+rTOzz7Q/Y07DDush58ZXJQQ5pgpY2SvCwHCDGa4drugQuTfAjxYy0zrkjttmu0dqJcmbLM,iv:hmxLM41Jp+09j/9cma91vv9MGaNV5GFK5f7uxITLzcU=,tag:8JQgLWr61qNM1/Rma8gMfw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQkFrVEY3WnlLbkgvdkw3
            Vm44blJra2lrQkxpOVZ1TGUrOU5qbkRTbWdFClZySS9jUXd0RDdqK2JZMGt3bTdB
            dUpaSkdsNU9RK3IvcXQ2QUdzYklmbEkKLS0tIFpnSzRReXIweUlhR0I2THlyT3Fn
            TzlSaktpTGNpRmhkOUhCOGQzZzlwZlEK3zIQfky597mHzu2S1+IUs/sDIgzlzUbN
            cbmkwT8iDZ1RxH91ClnJbLxO1XQG/hF+S/XJtAUOGl8Pky3joWPoDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:48:50Z"
    mac: ENC[AES256_GCM,data:qzdaVafljImrZ//W9/TU3ZM4DC6B/7BY0Ecs6ubGBLXHamUBtbiAolQ9IdK312t9JP1xNpZda/9q3eB4i1/kPKmNx1Mb6Q+BEyVXwEu0pAqam2aNaTZ4UrvBJZx79kN2PPJVKdQNLI2AspYB54RuOH54zeeJerplBY9dFK5Td+A=,iv:Mh+pSbzczwyq+bIikmAUV8z1a1atYlXCLD3rrJ494Yw=,tag:WWU3DlU3k2f/sDBGl00HyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
