apiVersion: v1
kind: Secret
metadata:
    name: artemis-api-key
    namespace: ollama
type: Opaque
stringData:
    ARTEMIS_API_SERVER_KEY: ENC[AES256_GCM,data:jJHFOuEJY431JyJmVpMd04AHCK6/fEUaKRy7Jebd8UrCARyypKLtfO7hY8JNXFyPFMmoOidh1BRXm+OZb3JZEA==,iv:NcfAl33j8ahxtExEn0vWsNpDYDvNrd8K36HTEqhzL58=,tag:81u325aqSVSSMLt5a5bQdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWlJxM0hkblB0VW1BMGI4
            end6QlpIbG5uejRLaWdXRWtaRG4yY3pEMlFBClRiOGgxcklDZW9LMWRhM1ZWOVYx
            bytCVEZDckg1QVY5Qm9Ld3N3TWFSS2sKLS0tIE4zSGhHTkd2bkdvTTVkWVMxNkla
            dHdpTW10NytJcDJITWVUc2dpS0k0Y2sKmpoAZFuJbGe/MZP9TJYx/oMdfgF9mnsh
            bLqypY1uGyBs+e+k0c8eVtrrY4IgVtde+dfUzdyAUpFiVOz2Np82Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:48:08Z"
    mac: ENC[AES256_GCM,data:ENgDdiAcdvwLs6wCOyyB+Alcv0AOV9lepPYgW3TBQB/LL1Jsbt1guTjbkP7wGEYEtEALZ3Rwu9/i1UfARS4HpFXvjqU2mEopho9C+JEkrK1PKR3wIhrURhfJtq9nn0gKFUd1sxhI+9VU7cemVyR3tSO3jqyJrsYnROiVwBuWCqg=,iv:5qnYkMrmPoHA5tYJXUbLyU9d9RUL7O0S4Y905PS37xQ=,tag:T5H+IxuR2kwSWv3sfcBYZA==,type:str]
    version: 3.13.3
