apiVersion: v1
data:
    ollama-models.txt: ENC[AES256_GCM,data:VEREBCKMdIkOxBk5CpGZPLsfoPS1yHnNjv7GpAIjMKSXR7ura+Us2IGcnnqd3A2eu+JH7dIFYjzGru5mU4fn+RjQS+WmW1TEDC71lEamcrqBYICJI/RrF6Y8XcL+2dJKCYrd6bQsCD3lc/xyJTiljqo6/JC29D0Xtj3AZmGQ9Q1nwTEaQjRA3UETOrhqyqgKPdWoHA6VixY0lrz6uPMMVHsPyNgxFjw4XN4PzNsLUM8IOeFFtwU0Wk0ASCEzilgoUYaUyt0qPZZgMLyfRfZP6JLs9YPIS08FhuAfegDGSPY=,iv:shRr6NPd2JOPHmGTpncKWWpGVBvmrT1XNLBdfjSmY6c=,tag:sCUOW64L3hkzbX2HWg3C6g==,type:str]
kind: Secret
metadata:
    name: ollama-private-utility-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU2htbE1aN014T2FmM3N3
            SnFzTzFKb2hXZ3B6WjRsSDJSeXZ0ZzZCc2hJCnk3eHFJUDVQQ3htSkEyNXg4bHBY
            cVBUSEN4SENOVGx5dzZsazRvZnpoZ2cKLS0tIGZXSFJjZDB3V3dXMjQ2MWovQ3Jn
            RjlFbDRKQVFsZ1lYU2l5ek94UkI3NWMKvLY81RC7yUONUsF36+s43ogB4Iee+6w7
            xq09UhAHfQa5utLWIOEJHLJUOERbFdU3URj1DyvX9T5J17hn7qIr/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T20:33:25Z"
    mac: ENC[AES256_GCM,data:tpvMCb+QM+LCcSsCy89zSudn+dk0rdtl1pJMrdxenvWGTLyp74Uxl3WBTQpABb+RiLa/1F08rDf2ATFVBfxlnRl+bV7YSdWbIxgJ7kys1bJXUbOOFpgCLBTlvyvhcFGryGwN57BJK3zie2KDzK99Vb4zzywCZS6ZNZaW5MqN7Ps=,iv:MHODDiAJnUCWO4d/QPFwbHd6K1qJVda6P1H30OXwJl0=,tag:2jjWJA8sVdxMScpeYP69dA==,type:str]
    version: 3.13.3
