apiVersion: v1
data:
    ollama-models.txt: ENC[AES256_GCM,data:aQtfupVKsDLCPzxBLAuxtV6L2zs7b8uzaVEe4fBP6JxPbh1XgHQVP3SZQRtrQIc0O7QUKx6q5zEmlZOVOQvcnlrowTdA0Rbfg6UhPIrg2aBr6qC62wBGaZQHKk38W8tjSM0lCNtjXbUZxILGS5SqgOHklItHQsmuwRMXMwQw9/YUSKiux4AY32vVPjBoNSSHjmoaslMt8J753g7eDM3fOZupddiUjZULVZ9Eeij7vq8FGu1YK6DtEmKryKhjyO53KWbMSU+SoFeVaGYKU/zJS/dY5EE/E0jXFTDi/mlrbyd2oo6M1kmKELX/BwNl+GLrhggZh/TpCuTGLPp/aOYLfpOD2jJUD/HXTuzNu2omukc=,iv:0c36CBYnjNrB9uByBhGDsiHZ+Lslta9cu/s1JmyM0M4=,tag:r81FW55Nc6zWwHQlaP3SmQ==,type:str]
kind: Secret
metadata:
    name: ollama-private-narrative-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdXFVUGJETmI4amxvOTlv
            TmJncHpPeVViNHNobXZtR0FKTVJrcVdSREdBCjhyM2VPcjgzNSs1RnZtcmV4QjJm
            amJUSEFUbVlLSEZkbXF0Wm9xVWJxcEEKLS0tIGxNMWpwaHZ2L1VaSmpXK2FjMEJN
            RUhYY0tkRDlGZW5rd1N0QVhRV0FkWkkKw3dSI6HbJRM07fUXZgVJn/9X7wxDFviF
            SM5FpqTDfXv5/RdMUSue/8Rwcd1LTYTD7Xf3HPtnl5BFl8SMni6C9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T22:52:27Z"
    mac: ENC[AES256_GCM,data:OdWWHQXmDNvn3QChutR3/9mu9N20EKOnlz3eEUGlMFUWDL/ikByzRMKJkr/m65A3wbbTW+8qSxyL/QW271WV7i9UeCf7eNYxv0zBbRoC+mgJtdQmWPb7MnSipz3jSD4WfNvaUGLLrq8RJ6nWoh+MTqWNcwhts+hWfl2XWVdPfH8=,iv:NmvLMFxmMDhDD7CXBvf/Qj2o6tPk1CZQ7AtftzTEjio=,tag:V0PvsEF0YU+Taw1qamGJog==,type:str]
    version: 3.13.3
