apiVersion: v1
data:
    ollama-models.txt: ENC[AES256_GCM,data:HVvI38yl1EwpuMveXSo7+oAz2Nl1a/JH3prxaaff1gFmEmfjfkiPm6ygyZs8+CTXF7TvvzHWmFQ6YcmKRwC3Xg2KpaTejI2mixKA6Xc3pyJTfh9MfMjmyROhc2rgLqXQUeSO8zTNj6T7ufDH11wi8iLhMulQVs5AkMCODLXwSVRv9dn02jO7AY89auskEvPvMXxln6xWvGoa3VoQIYQwAl0i1BcicsykD8Y1Mjsoowvdq6az6xh8DsFapaCOFoPDAGjwftHFeKPSglayA8QYpnTo4v1uaKZqinGm/uA5wB2wbLXrlHBIge/DnRSqdheNyDVIJnPvAjA=,iv:d/XruHCf9NuoxdPg5cZRIA0Vs4jwQA1EkSQMV8naba8=,tag:VqFha5bt/MPRBJVd+1rnSQ==,type:str]
kind: Secret
metadata:
    name: ollama-private-utility-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTkwxeWlnUFlHMFh6NUYx
            amh2b0VGSDdMcUp4TllIc3NmMkhrTHBiZm1zCjkvY1psMHhqeWtLMUlsTWl5OE1T
            ZU1VZUxybm1YMXBhOTFlcTk4QUN3aUkKLS0tIGNSNTJSSkhaZXpWYnZYWW1MM2p1
            R3VtcmF0TmdVS29oa2I5elZsLzdXdEEKK7tNKYElWdNUf1gTkAvE8rUmYM4ExDGx
            Qv7d4OqxF+rAmdewGxQQCZd6/OY8dGl2NhoyK9QmHu+jSg3cZzJXwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T21:36:26Z"
    mac: ENC[AES256_GCM,data:D00jqOURSzmyC0G8biBqKbbdBHDQL3nVo4jgs7xPiiZjzdjVqn1F+l9HYB0tHTFNa5RnC2DXK/Du2weJfg2XBnGRyK9kQM6BEdrZ1KnlZGETPlRCl1zdiOyiRoazZpiWp7AYgPaKXqVVcuAd9CvM5LtxQ5D3ntueB25aUElw0dk=,iv:nttyBZx+hfMTckFFXxgrIPAmTVQpYUSbscecqC68hk0=,tag:ZFDZ2tFsld/qcyZQVSNCug==,type:str]
    version: 3.13.3
