apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: ollama
type: Opaque
stringData:
    HERMES_API_SERVER_KEY: ENC[AES256_GCM,data:Ho6JH5Mfz56iArNso5ZAheRqnVk=,iv:Uy2exBBCluON51PMV2w/+KaKDQI2msg5bjG8xpbzfsE=,tag:w+GQGVhftM3qhDLqJ0if2A==,type:str]
    YUNDI_API_SERVER_KEY: ENC[AES256_GCM,data:276PQdgZxXL5Bu/BQZW7cHn3LA+OgJMMGM8kqQRf06PqRC9MoVpHbIOsDgC0KM9LEfvmW1fdAmKP1RGa1M/2Cw==,iv:fCClxj2zmQjNoB0LT7lnQX/Mb27kVP3xPBzn8x1+C+8=,tag:0GeUqbnU8Anw7xZGET7aTQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTGZkMmJtbXYwc1VaY2E0
            NmVGYndWRjBzRHF0QXlWN3BBeVJVYUVKeGdzCjd0di9DZjl4ZWRreVFyZm5xRTZ4
            cW5GRHR0Vys2THRBVnRBSVplaEt4eDgKLS0tIGJrVkluWCtiUzZxSzNDS05UeFFx
            WW5FVk1OdU5IYTFpZXROZjNYR2hxU0EK0+1vyixDqOam5ye2UPbqt1hk63MhU7fp
            v2FUSK3WlJfvkELy6Emonx8rnAlxzet+NtB9yZvojgVhg/QVOMZk7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T16:38:41Z"
    mac: ENC[AES256_GCM,data:0vKY5BQ4XAVx6JsnN9RmnIBOFEtUfOFYU+ZkfdBeJYiEpyzMqNxk1ilaxMYd2/ceDvIFXok1sfnyVwjmYVk+12EIE9Bv9a0gOHJbtH5P6TaeU9W4iw8/LYke4e2ba7sR+zDKTPtIwzxjHqwDZuIzhrhPxwAemLiiHSH+otj0qSQ=,iv:Yc7vhOvnEm6P/8fmzSPPgjdC7Rnb7nnhhDhHmoNnT38=,tag:DuNixFPD/VpDfMowq1K9iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
