apiVersion: v1
data:
    ollama-models.txt: ENC[AES256_GCM,data:EvCZWyo1j2bT7H5sk8kzCXlIl3xI1Ef3T722bCIkM3czLLseMwDULDdcuIK+D/r7RAVml5nAzMtqifS7FtWD+dWXNvlBjGkqWWTtSHFi7rQlHwY9nq4W3j1jUHZ0ZqdSvA1nFI1QsGReHMZsRDFol2h301i2yz1YVcjtuBeS7wu7vwjXlAGQYsG03SrbPXvpalUf0mq1VydkFwYfgYBbZScVoqUk2MO3N8Mxdkk7p4ITQQdDCLv7HZcKC9ombgiF+Teu4JwAKS1XTQCbI339XwKvcNycGbXq5YIUYtE/ME6LkSMKSGqMSHEFRCcCxhTQh+Lj8/IwLyhq/ckXTimQgVPVVckdQlQNhfgC0O0dQwvTwSF6N05cMBnapIY=,iv:VcGeTkOmdOm2mk2xRyIpmGd3PUbTQ9V1fHXr1vtGiQQ=,tag:/QQs79BnXbrsjo8Hlj8Zag==,type:str]
kind: Secret
metadata:
    name: ollama-private-narrative-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCblpVaDRwWnVDSXVzeEEv
            UCtVRlZzcC9LdDhTaXQyZ2dMV0thdURrVlRJClY4aDJkQkVBOWEwMTQxT0h4UEpS
            K2JJUm5HTkFUa3o5K012cFBXdGVIMlUKLS0tIDFlcDd2aXpUWUwzYUI5MUEzTzdE
            ZytnQVErbUNrSmNYVk9JUHUrUXBsVHcKb0iTP7XNeNOhQDPV1BZMadDheJDcNADk
            KZBsLOtwLrQwP9gPV7IgHhBaz7nIRehOdrkI5ARqibZO2t1kRb1Icg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T20:33:10Z"
    mac: ENC[AES256_GCM,data:rDiJIUuajFJW8nGq66YXojqbF54Dm1Tnn+RewRt9PG5W6LAgbTWpK7UzXF7XsdVEvgDrSB47V3ceAY/QKU/18azkDHrk2hKwmuHftdy2gzLZSrwD85kpl13geF1lyEkB5NuNCmh8zhLc+gglzJ06/aM3kxoJSgyZEWsNEiDnhIw=,iv:eajqW9+r5flr3La6TsgOQkWhf0k6HnezZ6gY1FB/y08=,tag:lxnKmoeK4M6lGERYQYbwmg==,type:str]
    version: 3.13.3
