apiVersion: v1
data:
    ollama-models.txt: ENC[AES256_GCM,data:yCN9KFvrdJ6JQ+9PWDC6r+eZnqrN0i6jNCzyjm/YYasG5cf+g/2ymP1hHCbOhxPa3MM2+dlGlVY2rQC2tMH2gxKdGLiCLLWBoeBdXN7JqYIK74QwI1VZLH7/osSHOW7imWz+qvkwlcUQ/40hku7matx7PF6XFlp+52nEZMJ2XFKnl65mKMEzZDsJVmmsdKhltuJefZegf8S3wsdfQIozevNxtxKGp/OJ44diNA==,iv:+umiHDeRwCyMxtTHAQ7znB7gFtosDUgdQ4e79HGdY5I=,tag:SVwDhmaKCEFcOxIauIlWGA==,type:str]
kind: Secret
metadata:
    name: ollama-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVUJMbmh3Qk91NVNtWGZv
            MnJGemdQTEkyTnI0SFhGUGZXUmJLc1dPWkVRCjNHU1Q4UXJpV1M4cStoNEpWQ2hS
            azRMam12SmxTQm1idTRINnFNN2x3dFkKLS0tIDFubEo4VkdScjFYT2xhenBFb2Rq
            TWI1aWVwaVpCeXhGUHlkT3BPd25FQXMKqn2N1ksVu7i1gY/biwlJyGhZvxoj+XHB
            RavUPtup1t524VzXy+uuSa2PT5886W8pkSIMVqpkeIwd4EkMQ2h5zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T23:17:09Z"
    mac: ENC[AES256_GCM,data:FlnPwh8WK6UxZMCC5fj7NuDclaHwQDEEX+sj7S20utVZGMTW1pT4t7QzVNfghZKB8SXcg9ORjj731WBbtqfAdKTpJFtCo6eAfNV3NR3IWJL98jUtMYifEYgwsocVzBv7z31Rof4LBDeFIzErcb6wmvL07UOosFMGUmwYT4Q9oTE=,iv:ccsjMV+EW+IJyRWMsAcIOCNhhp0dOWp1Vm6+vGnIiUA=,tag:rSfqKAHNX9t2hfadvS/aMQ==,type:str]
    version: 3.13.3
