apiVersion: v1
data:
    ollama-models.txt: ENC[AES256_GCM,data:hTPDbwL6V33vhSBwDr/jrGeIr22NmY3U+Pg7GaYqq+0GzbrJBCvjFW9uQ/b8Tj2Slqa5YvG538lvKWXeTwrvJfArgANkdB1BXEnSbzH/jDFPSXw1dVTCaaflmPLrE+zbltVivXqIJUzdzFfUtcKTsi7LVhQrplDFV9uS5csO52AvFHc2Ysov75P895GXI2ZxFK+0gzaiEG91qe3BHkxgReZ8bItjRp3eHpOLj5tEDxbtgiO3cDkVE+BUr6AfoQW+ShQMB/gJ2iqCb+4fA/1ZWzaRO7wJtmiL4BZ5GM9quvV/xx6kRhIWmQWi38ymWVM6XPiHJlbgKqdfKQ3FhnsURBjq3t2Jvz3a6Bq750fDvDp+9Vv5N/KjQK/zE5MGSOlpykOFMG8QCCe1bLdChV8Yc7NcOxXxFSIh/p5HpBdqt0zWQgctQknMHn/KGh/7J6ylF6rPCw==,iv:JmC6Xdo+JBphjN8u5dzjg8/JC8Psrjy6MwxuBb+Lbys=,tag:Og60FsMMArqynHHKcyCt1A==,type:str]
kind: Secret
metadata:
    name: ollama-private-narrative-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeFlxTXNROHNRTi92Y3gx
            TnlvSkJ2MnluM05uS1JiTXRnZDMxVFJycmpFCnFNNzZ1MzBqOVpYZzIvaVFuSGc3
            MzVkZVZwSFdKaU5kdk44V2JBWFZNWk0KLS0tIHVYSTBLUG9pbktEQ1pqVFFLZFlo
            b1drWnZad0QwSWorN2owdkU1MUlFL28KZAOjJYdWNEnr4zJP5YNTC5edSVeT/aBU
            CZwar/+xK95jJ0ND1sq4v2oHZSV5RaKu4K12Vdzq6jnKl+V8LEjueg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T21:36:33Z"
    mac: ENC[AES256_GCM,data:xKf0hfLEE19CSWg739s8T+Z62x/gEAG++QhnfkTBJtTfUw1tSs+UEwXNl2YLV0Aza30dQ04TP5qvNdNWZqbXsT5k/+2VyXmSz/RN7kzwfPZwunejKOq3Id+apdbpVgl3l61KaNW/0poL8cAuirHv5p5zBA9arTq9GYAqCSy8GCE=,iv:uu92r5cWFRrrB9P1kgxJoqf7Vgy3BWFx0Wq2Vb8Ignw=,tag:G1Nezx1zIPyhEt0Mxr0Nyg==,type:str]
    version: 3.13.3
