apiVersion: v1
data:
    ollama-models.json: ENC[AES256_GCM,data:GqUep1I49bMcZxfiGHRtEQnJZhTLJs+0fxnMNzXomlRIU/hmRStG5tXn1K3gfcpUduFPi9M3MVRXopmgnga+eyQrWkgSE7jHQAKK3ZvSUE23Eynl5ZEV1kkG6rKtZ/8umB88rSMX9NUmOlus7eiTTmPVxka/8y+98G6MsaUu5c1r53a0nBUY9RFMyItRf9IqFXj47wTAAjKW5pw73oMQ8vwbJ1PJiJlVDOwOMtoHYA8FfyPcZO85FUez8IIsZkhAhArt8E1Vrl4H9QVQdDiY4nuwTgZhB/VlrlP0w33bFv0EomQr2iCidQdDOZB90og/cUCv4zWkYFwd11b8V4u+YQxNXJM5aWp+A1eSo6K//SSdkI1gV8odxCTP8EFeYJCE6BX8GekLhDVJqkgBV4xLeMXZtY+QZjv3fZ4EBa9YoE4hlMkMOkGPL0rSEBBCsVBnUFzDLUzRSO+Tqpk6kDJWOsnH9QXsAQ6Zbe+osgBK8KzmN1QNjhVClM+f92ItB5AiB5mdU2zI3XoGtK6eE7QASqIBwWzmIO23g9aB49O9IDl5VofhDhncUPnr/wRZpooYCCyfBxjJ/MhVc142KzjSCpBQpE4uI8j7is/XvjEZrgsi6iWNflq5SZpa0RIm43RoyxywjkuTTlyz8hNLDl39YDwghkj7eTP1STyuUl1x6aB2fDJ2a3ps+58bcuSNTBjKy8yVpypnb0PsVvGpuEQ6P3A2/J1ZuAtgJOHGolDUXXYEWLtPDRjIRPQQrdv5xxdbFu8Jq++hn7XSO8/dLtcz9wb0lrY+W+k52tadQsy6xBP8PahVD0HDULWb4O+EG2vSXRTXPA==,iv:yWa8gYspAXtsS6ndYV61uRqMQwe/hWAA2v9xDQlpKWI=,tag:YRQl+n85Ttj9czLiBSTXrw==,type:str]
kind: Secret
metadata:
    name: ollama-private-utility-models
    namespace: ollama
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNWFYV3Rra2xHZlBhTHpP
            NHE2THBaSGlLR0FxTTk5YkFGcDQraWhjVTJFCmtUSmJtQUhldUpabXFxMWVabmtY
            NWRaaVhRckVGT0RqUGVxZUxQaHUwV3MKLS0tIGxvMEhWVlBaS1ZkWWlrNkQxNHZL
            b0lubTBLdlpsdTY4WUVGSlM4SWQzUmsKC3+QezbMcm4r4F/tWBUWNNpbuGBIxwlu
            XzwUb8L/5Fykz8E+iDPR8urXjRzSw1za0HxMCNYz2s0GfgSQ5+fLBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T02:23:26Z"
    mac: ENC[AES256_GCM,data:aVJC5UPqzG2ySZWfDx+FkQM+gucbW7XWtlK3VfACWhhMSHb9AL6LQ5KawglkQw/XyoXN3YJfot5PBF0ml/jFy5zi/oCGEW59auguhGpNpwYrbmDUII3akQB1JwfWqHVeFP5mbaTq6nqU51KUNLEbyW6JF1AQG9CMV6+44clzDK0=,iv:o8F57xwH3qgOFcE+9Ri7BMGT0UrsdXln9fICdX4KdWA=,tag:GkeZEuuMj5NV6epa/9cbhQ==,type:str]
    version: 3.13.3
