apiVersion: v1
kind: Secret
metadata:
    name: ollama-models
    namespace: ollama
type: Opaque
data:
    ollama-models.txt: ENC[AES256_GCM,data:Uv0lKLClYy2rzgqjvHzbDsJ1d2M/weapZy5Q7hPh7Ue7/4HQBYIrmKtN720K7CK9OUdlRS/3J1uw4zLWAlfCyEW7jqjKPQMzcnq9OWSzu2EGWiS+gXDtAtpwvchuzl+q4EArpEJUjao0npJmZcF1O3ecwOjCR9phEU/gAK5QDF63cgoS2PNyyOGpqQNaHB2m1hQFKK7tyyLkxtsU0+5JXM8LexWY35SpmgpWf5eyh8Y0X9TGH6+8WWGMeVIm+/pllec5Vp6c9T9BDkAxLfI1qxK+6RLwL9PsGKLfjrCQmeGzobjGr9d74AktvXjh7PKRsZMNnlsYlxPoTiUzzVzUTecO4Gx/kv2AyhiMSvZ/pQurHgNLnRX2utcY29TZoTrMhoN/qYvw+++E3czClcoboZaf5+l8oQwqj1ASmIXAAXdlWljJWgXeVT4KAnzNyl5Jl9004q4yhLYZSPQQwDC3K6zqzB1MwA/0SL1bAGiZfg67miZr,iv:AcAUEN0XqDU7OxQZas0zEesE65aKviDdf47hQaWGi3E=,tag:97FDjChBszRHouUM8iHjdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OGs1U0JPbkFXOGRleGRS
            ODEvRmNTVjZrZk95VkhVTi9jY01FNUx4cHdJCndJVHd3NjRHQklwVWNZd0pBcDBF
            Z1FaTUVhSFE0dkc1cmNGRlNSQXhucUkKLS0tIEtGcFgyR0lHUzhBdkpGWWlnbEhC
            cjYzMTRZOGdZUFEwT0ZrNnhWZnBwd0kKpasQwtVgUPxvU6Rbj1Cin/s9XIB24Rc6
            DBIokw+F0ty/aToXHl6VWIWZkyVDolLJfJ6u0C+9Dtiu1BT1CO55hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T19:23:26Z"
    mac: ENC[AES256_GCM,data:btV1Zno1rdtpA+VgVC9vdYsNxdHuaow/D66j04BreUpqQhYdsS6XDPT94ietRhyabczHtZDPsqFYjsG2e4Cdk3K1FvXVUj1zboHuIzynVrE0yxeK3Cmhym8XGbLpkjiZQwW9WwgZReEXCbRqH0wjpBN1ep289VrNI79XpqYIWbY=,iv:zPs/tVNUxUieuegAOG8UPlfJP5nzFnsDhPdih3fas9Y=,tag:74NrS9g5AUcfhup2urIrDA==,type:str]
    version: 3.13.1
