apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret-files
    namespace: openclaw
type: Opaque
stringData:
    openclaw_ecdsa: ENC[AES256_GCM,data:ipYETaHwMtOY0qSiGVysEwByehMTjy21XJ9R+/usCsVm2BUSAzu5nTX556vkC3YtaUsJz+NnRxgmJC8gPRyRLDasYfGcAg8mhDUD81gSCEiQSXr4dywXVGQ58ZWlI6AD5+7cWf1kuKaaCd+V1998o2c3nIqjVQOyXDenIDhrgjgeYRr43UKieMC/s22Et0Bv2UroJB8+xTZ8gOPxp+/+BLHqohPFWTI5PBsIOPRRHzHVgNcDwQpFR63dQ/TAk0xhNBe58pWYZyBtWHIE9nFEvCWegX74J1O3tkwR8GNFbabS41+MWd/AI10igtPYw2VzPlcQUAV36XNKk9fhqbN2jvD6oJGrbw+rxWyBxj6C0QYDtimJIoY5wI8izraS2cP2aRy+krB3H95kDxmlr3vU4vFxFuHQ+KTg7u0NUSg14sQefunO832vdMJMtmXHEncHC3c3xpT8ZHZq8fLrJ4pLJJuBf8VRYLPiCcH5z912J28h4iIEr9LBuCpmgB2Q7r70pOfGTobS7TQoYOzH3oB/T5XKUohs+vN3vyjX9JYed41UMITVPnVqYyC35uWwcf17cLyixbgG1Rt6WxeCnZu184KvkgHq5DdE+kQ2ASKNXKzACnCIaR1cuHGiIWka51zgrIy/fjxHCLMdETxl06HR0fefKK/98Ij5XA==,iv:bX3LT3FV9DMkqGQALrmXTy0lnvmOMWLZdinLqS8E0hg=,tag:bg6xCXn6kJnS8yLWCJVGTg==,type:str]
    openclaw_ecdsa.pub: ENC[AES256_GCM,data:aH2hX67MWYxTj4uE/LW12N1/Kc3a4Cb4/BO1rvs7WScSCcOeyjIDyf8a44fW9iQJ8Hf33bFNVMewEbFDbunmFqZZuv1dI8/nOqbQsh6kpr6MZimI2c08GkWiBykDhWF1RJR6SRKghcUS2HJFYGWGU3eWMEkIs/x1HVeT6m4tENVyCX3DDsXakn7maTq8wvWnYrqu/TWcmHSQI2+z0hJhR/c=,iv:5jDIfb5Omhepi/bCVsf4qLSu9XZO6X5254kjZirpCEQ=,tag:WTRBFWQa0atvLypV8xBoyA==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRG9WQU5pVHd4ZGhXa1NJ
            WXYwbGtuMjQ5ekczNXdneFNSSW8yUXdwSlQ4CitrdXBYeklVL0w1SFpBQldQQzQx
            alZabkFuMmRaL1h3RStnU2Q4SWNzdkEKLS0tIHN4ejdValp3MS9vbXIwMkdQcE94
            cllqNmZDZmxCbWpQVmZhR3RjcDBEbTgKO3ZFoGSbB3IEFHmFVmw9v9BfK+6qOzC9
            xvfjtfh/aNeDYlTXHTmjfkEr4sLx17On2G6esWx1ERT++sCvmnFIoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T22:28:42Z"
    mac: ENC[AES256_GCM,data:+QuF/6x1we2h1z1UMG4b4XiJwt/QFeHn/RJUMKPjGlNw5TDmECKWGqEkuGkLDJ6asLhlDC1zQ7fzYgcMbZ9O6hw8+KmNPJzUQijS7xUWnNOURFhr2OZYDOWjRyXBso1jivFbLRAgbF/AtHSSLJgcvQ75qKD/NmEG9ZKsbYEAdRA=,iv:ivzQFd9UQxQ1Y2xjrvFAQUVhtwUyPCD+aKfQCwhA8Ng=,tag:wqUw7sERbnst39WFtgYKXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
