apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:8mXoeYrC1HXvokyeFwVk/G4F59PrfSKcOJCF9P+VYbPaWLlh5xa+c169D1zseUQ3Z8Y8wtXk86SdnwY9Ammir5LOvcdN97Fxa/7IjmUiJlNuvzerpRwnihsYCJZMbPFDxqNz0pEFS2Pcbkj5,iv:mriAFKPCgyyBvFdU4OcjBNIEmpdlF6eTf0DuVmTuqmc=,tag:1G7i07LsdU3EAX7+SBK7vA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Niw5WPPHzJZdMO7TnH659F0aYpYDRIo6FLMIwlzkg2go0FsqpLLmbgL6HW98zU6dTEq74Ue0kYqZ5M/5zLyNLvZ0I16Ec+xqb7zceKvnRSAXV2rX9OexbnFwlBQkWEOua/w95FfPETkgQoknqB4WGCkX51zfgM8PTzfu4JNQmz9pUTbrrIYTxCupycVzIB5TBr5HPi98ABTMzgTvl4LaNBIg8IA=,iv:7Hv49flzPOm8GKHqMg9ra7OHRmdKe0fGYkd1b8L3Nrw=,tag:rPRbOujfoWxM4tDLhO23eg==,type:str]
    HA_URL: ENC[AES256_GCM,data:o2gZiWKqwIEPO+DDI7ivL35TXUflWo32OKyQ,iv:ISDri7x75tOWmyRaBFjaCuAdx15xUO5EEjz9lSG6Tes=,tag:2xdC1UFYpZR87YHWUugwDw==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:XtMWAbdz+Mw/1ZZfMBJd8xROH7PQNxS0k4XIM4gagTCiGLrmEg2FGOpARFlIVOXNC4vKFTNckC8yUwycu2QmD9IpC7kPQev9JMuI5sUMbmN6JN6Fyq54HyZ0K/Gl4mqwVRUNsIgy8+x6NYUHKnldj26Eqw59SIFdzBZBxmrHK6Z52nbLMRsb0d0vw5DdoSsoaTbDObg9xElaGRT35ZXnhmX7Fm0F9mERseIvwA285b1cvkJWyAA4,iv:zNYJd2UEgTPBpRAVDRwoBYUSpSS+DlXXB3rHCqtU0v0=,tag:cYSRqshd+6boNXecDY1qMg==,type:str]
    GOOGLE_API_SECRET: ENC[AES256_GCM,data:XulKPtmBu7Fd+9hAl1GJU/nbc2Mla2e0iW9f3dyFz8sx5ydwJyThZeSmqLyQYEI2+/mc0f42GJoTkGCC1bANVZ08MotASuqS,iv:1mfXZDKt5W4XU3SNjjj/ETyHg09i/NjT39HPAPM9Qoo=,tag:rz76ezdY1GMyJ5LDKpL/TQ==,type:str]
    GOOGLE_API_CLIENT_ID: ENC[AES256_GCM,data:7VpY4SGI16mAM066FUMYOephhmL5+E2wUsYEtrEUckoqbl8=,iv:XvkyMxewcfrVoXI2N2oqdKJ2B8VGwf84hVDmJGItLws=,tag:jNLnzXyXAxCkKGmF45ZMxg==,type:str]
    GOG_KEYRING_BACKEND: ENC[AES256_GCM,data:xGhTaQ==,iv:z2VbKoHfQrD30Phz/8wq2QPh1P969+LZPEsE96pAP2c=,tag:pBW/Ij8eaXx+XzLvsxaLnQ==,type:str]
    GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:LWES4KPAzKUgiaGk648C4I2v01M=,iv:ABxS4Z3jGSa4af11acun3Ox+BtUjwSHobvYI804puvI=,tag:p6ptV8vCU08PsWfP/m/zhA==,type:str]
    GOG_ACCOUNT: ENC[AES256_GCM,data:I2brdIBJRphLQmnn7ZqhoA==,iv:p2r9DaybfDK+vNfsTfRYJl9nH1aj7QrvVr32x9TxANI=,tag:0NJlvwvcTUhf8cAnFzGQxw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:eqcRnsB75Hep3PMBw8BscqgZalFcPxoCjYLBfrSiA3h0bl33I2/Nii4JZ4t45c8tgeyrlzkSvtJOWnHoV6Q51xC6r1db3MJW1JOj8sE0ppYq7rF9Beoy02od8x+U,iv:GVL2IEvs6NhlF6CToGuUYljhOnK1E5qBWsuBrChaWck=,tag:a8dMV0MVI6TrJjWx1MHAMw==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSzU3VlZGU2xaL0FFUUhJ
            endYV0RSckswakNXUURwd3dlVWtoTHR2aVJJClZHL2lER2JaMFFNWmFlZEUwelh5
            bm5lVlllZ0pRSnU0YzdGQ2xBSVptb0EKLS0tIFRDR0VIVC9TV1VweG5oVVNSQmJ0
            RTJZeXFXV3FNL0ZlZlVCMTJaSzNpRncKRqGRAi/F/HW5W3dZQ22Lhtn4aakw3QXF
            o836ZZNT8eE6RfNwNV9f9XMMPimNpVqBKAKv2+H1eUBUMo3IOkzhew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T22:59:05Z"
    mac: ENC[AES256_GCM,data:DIFJw1PorzvjOeaG5ZMEp6T1nEguX7Y5eDd3NRhfpzYRIIX/u5q7nVjPnpGXvyfsJiUu7PIU4arKVNV2/j43XXf61xCZUQxqqGoNwS2gluvbS3fGpM3ZolXaMG7ZhNKPPgQYep7lNQf3Y3ZXtLfW9TscK46F6C0bcv/KaYpb5Eg=,iv:3ksUVSfZk6z0g0EkOp7cYXrx7Z20QvISS4Dk3KBceaw=,tag:NAzHnoUcIpV86itbYOoGeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
