apiVersion: v1
kind: Secret
metadata:
    name: pseudovision-secrets
    namespace: arr
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2fMnsFVbOnKQJHBdUVd5jdAdU7pMDQH5+g==,iv:F9UPZBlPPohcVR4JSXHCM+hyjavShWq7nY7UoIeCcXs=,tag:1CzrVNRnWa05KDt7fJ+9aQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L2doTXJTMExvRytKL3lL
            TXZjWWhDRnhNbWp5K0JMTFlvV3J3bWJVRUNZCmtmZGxMT09LN1I3dHRNZFZxZSt5
            czBQa2poRHpoeU1VUEhNWU03ZmRseEkKLS0tIEZKQlhhaDdFVlNuVkhJL1BDWjBS
            RTFYbnN5aCtGSnBGYno1L2RVZnBqVVEKxXWYQ4u3LhyXNRsqyDFVOtgvtFcyvETe
            /U7sYzM9Kk7gM4yFfMnyaAccUrh65ec+51yrXU0LObOlmaNtzDlnIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T03:42:10Z"
    mac: ENC[AES256_GCM,data:gV1OTDtsaFmni/hq4FmmMFAW5YP/eseHl1mQoW3TOjxe3kyhEIGsjX/cNBLv8XVOJykjMkN8zUv2w3BH8eWD0EA3Wd3uB/8TO0S55gADT/AQfMAxNFJhnpajzku9RDwRKy67xameILLC2I38ShqqKxJsPvznmYkpNQS0v5pJKDk=,iv:7aFETmjO8dTTMdEM9P5E3Z50Jr6WutICZKqaYWVvikk=,tag:IOtKb4hwz+himAuwWchrlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
