apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-tailnet-secret
    namespace: arr
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:CTjp6A6vfuNHWprg9pN6bcLfse584uSxqBdZfVT6eIp4CSfKu/X1AXhH+acxyTu3XWybj5O1f8glpWO17SM=,iv:GVq1ziMpxdEe6uJcb21hb+GNnPhv6MObBXKZdbvTAso=,tag:feI0lnQnw+NLNANH2eAk1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzNvS1hZYjdJa21XZHM2
            VkpSdnRsa3RJdU4wbVV2ODIvQjQySHlIb1RZClZnYkRZdWRUNU05dDljOFJQRGsy
            YVpVeW5GbWsrQ2FKd1IzU3M0OG1UbVEKLS0tIEVkWU9heVNXMnpFUWdLcVJLQmpC
            UmpseVVEdHZlZ0VIL3ZEWnZNaUZ1T1kKI7ZPPJHjcJZ63+lJichCekYX0Pt/82SA
            ZG9N9bRMr815bEm584r9Qc50RzIzPdoaxPZpIQiOwLlY1nN//LgE1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T19:30:37Z"
    mac: ENC[AES256_GCM,data:uwGUQsWYswsOOkueYLMYYL3NnTyPskO50fLvb/TCO/qfEPpAyg9uof0YlT+q8oPwDh/8QoCtQI2fyr6WXb5LB8NmqtltYrLyCxRrsW/V80nmvJGLKkebxSA51+Aa6IhXZ78JmoFewtFvKnKaWZ4W9jtRckTmERdJdG5Tf1a+Iy4=,iv:PImaUEwcEtOqsebNq5y9q1gQ6eFzDZrRdI2kq+Ob9Cw=,tag:uG4Em68Glbr/dPcjKFc+Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
