apiVersion: v1
kind: Secret
metadata:
    name: ollama-private-models
    namespace: ollama
data:
    ollama-models.txt: ENC[AES256_GCM,data:CrSmbKTC9SdHdnyhBNicBuhP381/GWyMDaES7PnbK9AnuwYYiN0N4/KdzxEedcpT2BDoa3COrRCHBeuUYr/KuXlCLNugTtmEkHsYfx+uhk11t+ljrTgk6NOzWmkKh1EKLN0x7HdhSwbHQmDnTXtvlPPlfwIiyAjRi1uUJlbgHpIgk3vpTnNjLEZd+0xno3dJK0oHoa2ZUohkA3S0HtCoqzg4pFDg51Rt5/+dFI+TfxDdk9y01A/EJvGaDzx4AANVPyzDp2KJ+1yWb22fnaujtDlEZrZcyfK3MSddmRZuBBr3F/ai+y0X0H9VqgWN86mTMKymsNjFxQjFOMzCNCYlD8YVQijv9FxWB5i+KwRRucHwyN2ELvR7BpZuOcOQaLjLtJWG1pBfG2d7SZDSxx9+351HDqbWs9zlTMX7w2IzoHIHU4VeUhrjtV9cJ4+hzrOEQgP+bwyZu6o0b+dH3uwLX6V6UBEbL9tYfdsL6E5DfOqpkPuGZNVkig==,iv:PSsEtVMDZtbCSpaOfIyUVKilWuURwZ1hlc3tgnoYiII=,tag:061UZzL5zBjbfjibv+jthw==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVGF5NjU4eFZuaVFuc1I5
            VjJPTFBoL0RBdHdveEEwNnZGOUVENGsxUFZVCjhtNGVYYWR0dzVHNlBscFFJdXhS
            aHMySGh3TG85QWdKTHRYNEtVRHhad0UKLS0tIGkwTGdTN05kVkJGYVp2MmZXTlZi
            YjZPS1VENWMrb3d0cVVQbXh2TzhyblkKVqDtvtlqiLQJcYnYDfUwWKd/SwL0trzg
            HRyCSDRc7bDW04l399VEvH16UEVMgl/T4SSE9j+pCZ4KcPSJQPXfwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T05:19:30Z"
    mac: ENC[AES256_GCM,data:FPqb+Azm6xh7a0I1VS18KgjcqU0sb3OYeuo8htmiKZ9JphASZKe0hdP4FaPj3KHqRqDyNGYRURgYHanuYU70FrVktRxSD7TgBEOU75ea87/QBXu1rmJfMWCy4M9CkFXU0v1gitKBaTjjWTxB8uhf5KhgIBBxVWVTEtECC4YQRvk=,iv:CZblSw6/E94LKCDsSeTmA0oq9BcxH5XXnZx3QnCyjPw=,tag:v7zBmAYUuEaoNKk7T9RIXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
