apiVersion: v1
kind: Secret
metadata:
    name: tunarr-scheduler-secrets
    namespace: arr
type: Opaque
data:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:VslRWbiDne+nLIlRys674ZJ336Pv1hX8pa0Ff7vYSwthbd/fakncqKrADgg=,iv:/lDJeMoWCqyJjVJycB6ZLAy6HKKNiqhkDv/j8+RpBAw=,tag:TmDqzPX6NZGQ987CPxxADQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:X/IA8swarOhBhdzXBNof2qIticGojCQOwT8g8SKrjNCgwH5blbdG4stOJmtuLRI3glOkbh213+VMB/zkmykaflLzXz9KBiN3cqZzYuPCfPYL/5dBtVuTTgGSYlFqps/CVdVvIHtiUXQ0dnKlVDyYe7mz/uzuyqnX3yiMPwB4c5sYrLQOr5sbiwZxrP3ltWtmCbEYzVpjL0slOB1sKZTThJGNYLmmtzLGN00h75dXAzxsmps+RGLvKxvLR57yNNzsmVkoyUEu7djougWezMTIpvbWHXZExzHMuUw+6Q==,iv:IydZIzS1K6z69PA3aMNOZgor5qZk5asHE8Ye+8i7MNQ=,tag:g+JxDpqN4z18rMSl+z2+MA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bJUYjm3+IA14v86bttMKe4IObL/bBZKzRiREmQ==,iv:uRJkejfa8OzVeNwMAMwS3UdEWq5kJ7skDFa57zTmYOY=,tag:DQmDQe6CpJPzOI42ZKbjWg==,type:str]
    FREESOUND_API_KEY: ENC[AES256_GCM,data:xWPw4feujoUsyGgLuF47ftkgGpjG+iBNu71xm/EFYeCWf+gp4q+RDqZNMxFnZVuTmfd1ejIHnxk=,iv:ES82YqBrvOowlwfgvDu5ufbNB5XfvO5D6CKwjzIaTzQ=,tag:Z5G9xVjQA+GFlTTIuXuRyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cmFmUUlEZVFIQjJZYUkw
            V0Zjck04SDgvekJmTUxlaDhHTTgrNGw1VmkwCnpmV09YYVBlYU9tY1lrZWFiTWtm
            aUltbHA3RHkraS9uRStrY1VvSEpHbEEKLS0tIFN2UzZYZy9IbWRXU0prVmh3TE1N
            YWM3VW9HbFUrVEQ3NUs4ZVp0VktCMzgKWI+2f/B5+/MFOxFggCMjQkEdYcJv2sOs
            0uBpP9+N+nftwnD39s3+bVT+bzujzzbujqeqKPOJk6KU9oOsY3einA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T05:07:23Z"
    mac: ENC[AES256_GCM,data:Osx55i6YdNfpBy8UuXp4J6Lp2f3LXFnBUKjDxuQvldsQ92UlHL0RjJd4cI6qd7OPhcKts236HJoKoY2zfW+qmK0CCgVKt3b0vB/fwRSBYWeGhckHxfobLR01dBQQVlXe95vts+qYsOLqnc2RH+j0BMJGhHP5mfoCBQd+KCXlVxM=,iv:BeYG0nCCG1h1RbS6E5+7gpKhsTiKkOcM+8ojZeyk6HQ=,tag:5lFIMadZmdDfiKsdidMKwA==,type:str]
    version: 3.13.1
