apiVersion: v1
kind: Secret
metadata:
    name: librechat-private
    namespace: ollama
type: Opaque
stringData:
    MONGODB_USERNAME: ENC[AES256_GCM,data:FP6hC4DSR3Ei,iv:C7YtGxnqtA0pgowbFTTvzoaXI4LWw/wJzvGOYCjhbPU=,tag:kXlLQNHi13uIMgZjalSx8g==,type:str]
    MONGODB_PASSWORD: ENC[AES256_GCM,data:CHD+N0Qum9lPjCnTUFYMwapW6m0vT3OqV97vbzgkaI0=,iv:6eKiiPC/qc16kKb5O2UdMIt7vUevgNk5Hle+QO8lAC0=,tag:ItrtlGHgI4EL6sI6dWhesA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:1/QQQ66dn3zTnHwtarPJikgScGYwN+dv4WuPkAWlNxc=,iv:FAk+7EH+y7k35VaHzcjLXIqLU3hmDwtqvn6HMVUQMRs=,tag:iKSEzn0Jt7p4klh5mVMlwA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:DUs583ZXk2QS,iv:xl2zCq190k288FnH3aoiAMbnqWG4SCUod/ycSjTPqV0=,tag:JeY29NltOuO+NMfAIDUm3A==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UAyYAbfrLT1PU7FJu7w0kJQv6tjR/IXzmg2vxMp5lkw=,iv:I30lt9PlHh9vQCrtmB+2g6TJgwZbQiZDbTw+IGPecK0=,tag:YlkOrVf0MW2CzSvJ61AI6Q==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:miNOG4O7U8Dl,iv:8V0GyUw3j5f1vd60bQz5ShpY8c2/hrJpw/WGFluxpsA=,tag:r2od9jNszPZ36ttlwadZOQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:ocWvT+WoLZmwWfYi9xdIgKQBtXhclJEaz1ASsOxfewg=,iv:eCmh1OKBuHL6PZLVF3bUd0XaUac3zdYMaD/asl8N0mg=,tag:PfOUFERqgcHNeHl3h6xN1Q==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:lJRbTjohURxmQppo1Z+h2kEeiw215JtdlJYFdwrnzQdKQv6uIVi4PwtmauReG0uKC7qMZp4Yoe/7I0rC8XlAyVC1e0Ys+B/snphDLKqgr0o0I+HiXFTJDrp8ZQ==,iv:u1W48vf0cYxome0VwzJKRWKQC1JYOpOTTSCF7RTPqpw=,tag:cvABorThIdejxBQd5mreJA==,type:str]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:ZE69nFcTlesVFN0wfhMkmbgB3mXsXOf84awJYFZKaWwhKT2NP6BTZQ==,iv:UbED/qdcJJO3C4JyznN7EqKRV8sUuq2xnPn3YvRHtKs=,tag:H6h4pRrx2uj2DGLUNdkH5w==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:/h8TTZymit2H+l7ic/DM5Zqki7u/0XLslwnwMz86zyZRzuV4yj8mgYCESufHWyS0BSBYRbnvHPvd0paEdabUf5at2fOGOW7jII6Y9L16/VA/n6pLkJjnHS0OOqtBNqcn2MB0xZywaS6AYsYIo4XRFXd/IAecSw5rltwW3ttuNTU=,iv:n/mSTJBG6YILXxndIkMd7KduBF72vn2AnbLC2i21Yn0=,tag:nzhVICuXtyX+yA6z48VqIQ==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:aFpbp5vlx0kiPjDlBag515q89nPFHrQ/82TTEd7ydfg=,iv:TZQEWNcOWIP/smllicxiP+D2YLp5Qh2ER/sWYsp612I=,tag:efRXGlOJF8XDu8agrciNbg==,type:str]
    OPENID_CALLBACK_URL: ENC[AES256_GCM,data:7mSwgvK43adWUSfbefmmGCGng17GlA==,iv:Jz80iFM7aM7l62x+2lba6CkWbcAMCYzbRJFujbs1sCA=,tag:eqDLYh7ozExh98Fnx+w7Pg==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:yPUXeAbjM0So/zZ4Tsr1GOKqvQ0=,iv:e96mmOgUhXguQlno5wOdVfaiPpihgoWzNZzQEfAkGyo=,tag:XZDHJYaC5ONg0f4vuUpeIg==,type:str]
    OPENID_BUTTON_LABEL: ENC[AES256_GCM,data:If/j9UrQsK0P,iv:FAqOq/aF0XebY14QD8t7kRAjilX/hfC/3aufOu+oi40=,tag:3GmWv6U3qaSsaPiYlHbpZg==,type:str]
    OPENID_IMAGE_URL: ENC[AES256_GCM,data:FTnmQcBW+FC0eeFl5eINvEMW5dmmUqGAsv13XHSjpYHG+5zecCYHna53a3Qs9Qm8KehQjGIaAjJUDeQ=,iv:Hw/LKHI+EHNNSlz/9bYZONrncFbs+cUIJcZtQnSIrDQ=,tag:iiw8pAcIIH5EeXNwchZZJQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaC95RGRqZjkxV2grU2hN
            Q210aHAzdmFZLy9Pam8xWHZDYnBFSVNadGtJCmZWWVY5K3A4bUQ3a0tuT3N2Q0Uy
            cUJMT1V4OW02bHRiTm1IQTVtVDhDbmsKLS0tIHRkMy9MMlhPaVYvNXM3a3hybXVG
            eWx5SFVrcGJSNmpiclEwdkJYTEozTFkKutS4X5TyLCx0l9JDMmURcnz82aqDFjM2
            YkPQsDWQ0BXG10aFrhaQg0BBJ6DEe54QaJxRMhi09FA5MuSZdTK6rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T23:39:18Z"
    mac: ENC[AES256_GCM,data:l9CCdwhQYYNeG9XRAS+Z/RHvcc0OHEzPn8D+w2Vahk+RcPId3RX5wSeFd3VmcYu9uXsap+ldq3xyxaiUQB4I3fxxkk3dQc0pSxaMVk7WxoPB9HrgLQJMUcZSMMFgoK9RXf0PyXbTvSaQo5waERSrnPR5J0gqK9hyByJKxCJeFxk=,iv:Io90b7xkaN5dsrXZi7JtmpdIJoFvQphl9ysiuOJFyQk=,tag:S+xh2uoPDZiz5GiFqfUEUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
