apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx
    namespace: paperless
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HPdlTQZc4y0fFXzIwGDCkZoxedTssng21w==,iv:7trYXzk2d6YF2M1wpVO6PKCilGCTC3xfVGtODbJIiZc=,tag:vgGvHbdTYR54HGmQjf7a/Q==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:/1TeWLT35amwa8dA/L4AGeZVTGVPKKrpHw==,iv:+ZS1grNuD8CHsj6GpZq9UdcGZKFTvhesvXA9XpmDfcA=,tag:dHYbza3C5vxM4KnaHQsiiA==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN3hZdk9Dd0dYMG44RmdD
            dUE3aitYSVdMQkNDcXR1dk9MUXRGVnZhRW1ZCnRrT3hWdHVkZytTTVBaWW1LK1o2
            dmR1RTBwZnBYQk1ibHpoY1R3QWxFelkKLS0tIDhETTVvMkFtbXRUTkE2aE9LWDBN
            QnQrSzJicDluekxuZWc4aGNnYnlxTmcKOgqaFw21ufvqrKa42B+TGxMEbw+jkhey
            0ogwSmbhTAgqNu6fd+5jYvHfX6yzLjJb6+cKVHiK0k9YjAj5ruZXrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T19:03:15Z"
    mac: ENC[AES256_GCM,data:4X0eBaEzSPzmCvuRk5ay/wqzV+7HLmiXFxEcVBw1ImFHb9krU35EkHZr0PzZNgI0k8zjQfsnnvxuu+A0DMCgCpetR7aVeUc4lEdUbxhE5m4BRGtXDEdTWaZ4Ie5oixwPiv68eSY+3npL67+gsrPxLwDMZ7nLkeb3/28GCAY7iB0=,iv:SdyoI+cKQ4xYkhIUFOPlnJJ8DBto4IKUIe1FFZd0hRA=,tag:T/MqISRRGLWy+TR6EhzFpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
