apiVersion: v1
kind: Secret
metadata:
    name: librechat-private
    namespace: ollama
type: Opaque
stringData:
    MONGODB_USERNAME: ENC[AES256_GCM,data:FVgpge9GSmJ7,iv:dlkEcRnahhyc8sHJlwRybB+UZQizM96vzBxn396OVvA=,tag:Ni7bbaPyL1qeLZdpoCxk9g==,type:str]
    MONGODB_PASSWORD: ENC[AES256_GCM,data:Dmniwh7qmq+/WAMXF1S+A1eiY2U1I5S2pUi/Hvnj7aE=,iv:xHw7oErKIxcOJ3IVlgG+PsyH1w/zyM+gQcv9rwthKJM=,tag:UDtlpgraiYfPpEDSu0RnFQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:qDkMBiVcvo7iwH1X6UDES1CMRnTmoRzMp1GAT6fw+0s=,iv:FFk+OpjZEOtTLbzxYU537ov74OeUN1X8kWQwa85XRWo=,tag:mI4wZfHjJTDpbd3zoycQVg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:dYpZQT3PyvO/,iv:1eLPxkt+fHCWSxqBd94t6ULnwHpvSJgQDj0ldfT9qxQ=,tag:znAGUsY4pnQ8o06d9f9dDQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fVr+4SRGO8q+MuBXvN4CjXU/YhVB6dgYigoLmY/EPw4=,iv:ZiiILwrfYJCuTA32rq+2OSYYLdYsq4ys49qG6KxQxbQ=,tag:Anq17ewN8JXU5hrWDGc52g==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:02rMQi8zhjx/,iv:mh3DAfHsMSaLt73Dt5x8vmAg9LJeidLYOHv018cN2HU=,tag:LQ9G+MqrBEXEqXaYgebOCA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:cjZRuPxLBNmd1braplyWE46tDIMtwCSp2DRkG/5Xj/w=,iv:P5LOVauI/fGbIZZYGUxnr3A7Pzc4jo/sDUCKcXsVgOU=,tag:kL7YfEfi0uP7u18TbmjQSw==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:xZeZyHoHbXt25akQc7ZOB5eScACMSbmtNAlYEutsaODWVUSXvEaH+/xDJMaDZ9kk+ypPrDX/pK2FYc0Ncfa6XYP1sdLYjut0Sky6VjrFcQT8bERlCX4BiF4QI/c=,iv:++glUz2BLccUykJ4G7ykGt2WuTZbNDLVAzEXTQJOTVg=,tag:ysUvnxZ2DvIF/C2SCVCDSA==,type:str]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:FVHK7xIfYiMq7vc8G2cDB65nSgyWt0Pz7/PoxrnnwuQXn9PCSYyGVA==,iv:HvXLSLYoYOVOBYbe/mBNUOC6/y6DJ6x/bNPMWF9IdRc=,tag:DN6GR7XYx86ykyzdqbnbpg==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:TPx3k5fJ8cZekM0tDwQicQiDurSh9CuljZKcIQM2gbmKQ8h4Qv/O3CFl7pEgoeUhOVvKCwVBKzSo+SGl3ORm0tcOlN9jjiBs82x436qCF2F8whi2K06lG3HkeJlo8ymY0wdfq+++whMs9qnTc/zwTj3j+EQE1gZZJFQ7Go3az8s=,iv:1g5Bj0MBCZWtkJ08H2ygMuPXxm1eK5qrAPBxc/cve5k=,tag:uTDL2ecDyHMZfpXWKKRo1w==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:JR4TLSvFWVTsnuXlHFY5OYlwDyBkWmdUpxen1EDPrik=,iv:5Uydrq7hRRQndfwPKtQj7ooPkmbab0rpmi5QaZu1530=,tag:HH2ohc8gOOmPv9eVAAdMtg==,type:str]
    OPENID_CALLBACK_URL: ENC[AES256_GCM,data:grvNBE3C/2Gw1V02oUBGyPNQyZtgew==,iv:z5rbCizxzbHeW9ZCelbT8Mz6XltHcD8zpnIEt8snAqs=,tag:zJucxmpBWg6cazKOOI05qA==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:JWk3R839BL/BVi0guVjIzTTKuaA=,iv:JGCBc8VuTXKN6W63c9VF9gm90wo0eQB8wmBFnepEO2Q=,tag:+Sz0F5Dejh2SHJldA/aE9g==,type:str]
    OPENID_BUTTON_LABEL: ENC[AES256_GCM,data:ytvuDzaZ2FDQ,iv:j1GNffkGAwTveqhcHIEVbw/bCmve8dbyMA0vQ5Pkmrw=,tag:6dFwfiYYeub0GVKQjYuxBg==,type:str]
    OPENID_IMAGE_URL: ENC[AES256_GCM,data:JOxTabEZM4y4tqWZR/shJ9OUT9wyKwtdsCn9GipCwTkSzijQmoZZy9TJtJvbzmniaA/AnH3kCTSJHIo=,iv:VLHiLrVSoaiX/es2IIbQIZRMFZN6ueUASac8jwQIfHo=,tag:aoTRSpJ/WvpDtBSjfmeZpA==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y2RXTnhaMzNiM2FBZnFr
            Ui8waWQwYmJyMlhyQko4aVViRlFwNDF6Z1Q0CjgwSXE5ckplRUpORUM4ckhLalpU
            RWJSMXdlOEkreDVmL3YwWjhUQm1rR2MKLS0tIGcvbVlueGg1RGNjVGgvL29pdVBs
            R01PbUllR3ErZ21tSE9XTCtqTHhuMmsKHE2Pmn6sVyIe4/1rugVz9x7dYmuFl+bB
            6Yk0c5aOoaL44UG9l2IvofItvdqJaJB74MTM4LK5n2frxWesUILLaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T05:16:21Z"
    mac: ENC[AES256_GCM,data:qYM//htSTdcbEm7guNyoY6/+IrGVv8ReZCzbkpltu7A35JrRVRyOxdFRBhl5Y5rb1LSb6V/2sv1DYhIWmzYDs3OVFtOykdASYDYY2ZpL9PPHyWaULucT2je70pWuyJdBLFJJlVrCqn5nGeDS9s8hhWtUe+uNg74UV7vTTObbVwI=,iv:oeQyCSywNj+fpCThJ2VAeB6Yk8XVXN8sbjAxO5kyJs8=,tag:3qA0NOFeMGBC0Uj6BMGuCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
