apiVersion: v1
kind: Secret
metadata:
    name: tunarr-scheduler-secrets
    namespace: arr
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:RnIRAB+IkZJQONp2E8F3ScOa0lSQlZNTdPYaKg==,iv:jQ0+GOH33C0kuvITHL0IMbNB5ot7uwXXikgjNZW4htk=,tag:A5ApbtZMl9eOOPCUfJVnfg==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:JjjWlAzbMv3eJb8FCNdzqVHmWllbDttf95SYr6ASgHrzC2By/HmesDOAW+s=,iv:UfNOxxw2d9x89Gfk8JHIlWFa2dZTRxvNqPBe7sT8dlE=,tag:+qa6B5i2EbqpJDI95cYydA==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WE1rbWMzdmx1T2dzbGcr
            dmt0WDljZjdCdGtRcUdiQVJlbDkySHlmWndFCkF2NThXRzA4Wm4yTHByb0lDdmRH
            Z21rOSs5OTJlMVduem1lazBKUnFmc0kKLS0tIEp5Q2RHOTVoWE1wbklQWjhDUDdt
            RnRCeVk2MkovSE5rYVY5QU81aUFyelkKVu1WU0WDROCuotVd70rO+ByA6F7bI0ug
            HqDR2Ki2LWIo54Zm6gV+QkgyXw6md8paTidg4VsCB5n+pORpjog5zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T03:41:03Z"
    mac: ENC[AES256_GCM,data:6nCO2+JVlFMHIuzIl0XP6PMhY/nc91BrKGykSjmT9u2KbEEjtjUZAIWBc0T8mPX+frzhxRk3TE8hlQx9wWu2/VuUtZUGOOnAS+/echDpJWFPq3P6crx1R3tDGQTU2cc8Y1nzxrvvSHfbU+m8iQITj8CBXouWl79xY64Qd5cZP9w=,iv:jrfneomMvqux67M1QZY7kl0gZRTQ2f/TTNBooVnCyac=,tag:iH5miDQjkZWmeF9BmYxsxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
