apiVersion: v1
kind: Secret
metadata:
    name: stash-migration-rsync
    namespace: stash
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ZpI3j0RqCLOz1v0E5Or6AP+hN4BH6hAOa8W6PxcW7XM=,iv:HGH2LfRZ0WIPFBB4rx0VkndR1wX/6sbxNZ6U1i/SuUQ=,tag:62yNqBRSHi/al+XXhK6SYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobW9TYUpPNFZaRGVzR210
            Y3h4cmxCRHFmcVJXN2NzRS9xVUV1WElsdkU4CmVUZ0ZtcEZwb3dVN215b1g0V01w
            SFdKU3FOWTM3ZWhRWHlzYmtQS3M4Rm8KLS0tIHFUQm9UVTROd0dKT0NMcGhTU2xR
            VU00bnNGN1k0TUljeFBVVXhEU1IyZVEKHrnC3aU/nFTEqDFOy9dKk1ipYtVoZbPX
            LSMqVMLIYadTHkdKMptoAjdFpW4zhD240kARABLy8mCp033/M4e4EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T05:59:08Z"
    mac: ENC[AES256_GCM,data:np/ZLBQpgrhX0gMfBgKxBrhauVj7DoejV6+vdIjkLE4AhDFG7rvuWSTvZelLqgnmpHkeYgXDDt33LnXnpTkezv1rq1XPhNAErtaFduvELmC6xUGgH0wg84KqiIFONDnFjZfOJxa1gj92t4JpASt53kVK8NiAsFtx6yle4HU7NwQ=,iv:9MygX6FsA0UOVZl4LGP6SS6CIswL57111Vrdve1wv2w=,tag:8QaGF1NpL4mnikpxNqbjSQ==,type:str]
    version: 3.13.3
