apiVersion: v1
kind: Secret
metadata:
    name: stash-migration-tailscale
    namespace: arr
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:9viyPQlYxzR30GADFVswf+S9xk5b1A/6WsW1sL84DBeSRes6LAgQdvvRAKc0qEA+07lBZbzTtYnZh++cgQ==,iv:uT53vo8Gkkss1tVhwFhZedYFPf250Nbt4Hvw7pu3UYY=,tag:NCygI8sLz1o7piCiHrzAFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWFZuMEs2V0JLS3BBbERN
            RHlyRGlGaDA5bVJ5aDBnNTVGUWRaQzBxUkR3CmE1azJqTUk1b3NlYXdzS3V1cFVj
            d2dUTTBkSjc2K2FUUTJCYjFsU3VpVUEKLS0tIE90TjJLdmZ4VGVneExmZzRlaEl6
            VmRrOVg2Yng3alF6d2FHQUtiS1ZaSmsKXkQcO1YwfH6M7VBbFL/Eah6/DEP7YJRU
            K6dxrG/XzcBo07x5hNlnEUie6TVjJqOEmJ11cAJk/XebWdW7xVBCvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T06:05:57Z"
    mac: ENC[AES256_GCM,data:f5huYDQdDcRBPQ4j8XfVO+4QVe3tPnKA3c+n2M6UPmCuqOcMp+slnuSuDrEqhxECPVmeXLaFlf4+3Ex5kzpwHTlU3GhmOqDAaQWaIRMrcO9pfv6XL8fi5PrfNtqVomYEnUynLZRqRvuuwr/PF0abaNrSKumyBY/SD5lNEvRfisw=,iv:iOc/CtwK8ToogmaYUl5d64wI1zB36wMLplLzpkCvqzw=,tag:9zR+lh8PwSjtjCzAu9e1EA==,type:str]
    version: 3.13.3
