apiVersion: v1
kind: Secret
metadata:
    name: stash-migration-tailscale
    namespace: stash
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:aTl3LUyg+KySPwkSvR8SBXg8p/SQeqBMfEZMTBm8S93GOQOsQGDi/GLGISGYmKa5JjiBW2obnWZSn4k0dQ==,iv:mmt6KNHyOOJ3zvwsxhqi6wYSlrTcU6fiPgf6+jXQ02w=,tag:AGBjzOZ3sPSqZE0CqX7BZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaUdHNTZBd25ZbkpGSGpY
            SzN2Q29iZlhPVm9MUGlIQjBpUFVMMmg0OHo0CmNtRzJNU2t3Z2xIUEZXbE55cWFj
            czdJU29UWEZ6RkJhZHluOVM2SlBTbmsKLS0tIFlKRkNiazZLMWRxQW5mblQyck1a
            Nml4bGF1ZjVYZk9JS2Q1MGVyVndVRkkKTmOUedTI9+RecYQTXEU6Onsn9AGuf7Az
            osLG+Nzn2sxniixr6LtFKGIVfhwCRFUyyi45Y5J8e+eBlRbECAYAJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T06:02:59Z"
    mac: ENC[AES256_GCM,data:9sxWSWh4vm6g/7F0Dh52loLFp5pVd5gVC7jrUz1j5RCeiGLmnoNZN1ArmOwqT3UkC+ZiK1qJ3fAq3BKSQcluaEu4aGXNLKR8rwAxm2/bZcTolh8kDoQai95/Qi/J8oIBlPlh1rF7+Tv2p56VXCYRhI361T6M2a3FwF/SD/Jah9g=,iv:NzzzNDPxoYtYVbby3aibdkR+6iHUOvvrjlA/Ciy0TtM=,tag:FJyIDRHfaagBZ0h5aihIFA==,type:str]
    version: 3.13.3
