apiVersion: v1
kind: Secret
metadata:
    name: stash-migration-rsync
    namespace: arr
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:rD667TZrt3wWzn2210Y2oPo7nkrNYQf1uGWpdiUKLAo=,iv:fAX/6wj9Y8/bilnDAfSxpkJIMzaMhJyuNCnBhayjihg=,tag:TDWbNcoKxtd6RmXYjHPRJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQWJ2aVFYeVhTQ1ZFc3Y3
            aFNFNGIwZ0hNYThpdlY5MDFHQlRIaUoxY1RRCkkwRVkwL0YxTlo2Vkd4cE8rUkds
            bEJEaUwyL2EvZ0trSklidGNXZG1JbHcKLS0tIEVBN2VveVRRdVMzcjZpT3Rnc2tK
            bjl1WnREaUJNMlR3RXJvRC9LdWF3K1UKG78BDqTxIuz5XwuyLotJOg09gu4VF/fr
            Xz9nnHKlmRy1g1L7189kKMlC5lyFOzhHlFFvyifv6chWKCoq1Gg0tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T06:06:07Z"
    mac: ENC[AES256_GCM,data:q4hYvy9KOl9G6M9oMDCza4YMYZsBiZmKOZ44Sih49GV6NBlIz8iIXrBK7sZ5fEIcabJkCSZjqw7Tp6EEF6zPgC9/lyUQ/YJbhDBVfeCRnp40F+84909PEl9Joi4YOgTQY900qbKT/uzn6heWs3zlgs6fTjtk+/mtFu4F2ugCEWM=,iv:1HIYUsBRGThJgMTH0itiDm1j+p5LHCRTvRk4zHobwgg=,tag:J/GOVdu62KEWSPbqI/j67A==,type:str]
    version: 3.13.3
