apiVersion: v1
kind: Secret
metadata:
    name: teslamate-secrets
    namespace: teslamate
stringData:
    DATABASE_USER: ENC[AES256_GCM,data:8vaBgzFSRE6a,iv:MGr+eZc2sZeX4SdGO+pUU/7iPxamhNxuIMakc1VZd0o=,tag:9uIEZDdezQHyJs/4zkyD7g==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:JQGJiIWdoTV6bwQAvxDIYctIwQs=,iv:EujhcLIhZqbuSFKB6qoqJXIGJvIAVO9gh17pLfOf3Ek=,tag:CsyT/SkI+uNH0Cug5GMxoQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:zBEPiyh3SNlB,iv:M4uw5hOwdgBQIoV0LhaBge8/lEoUKAP21t3HNIAXXZ8=,tag:qr/mU5VpgWjPax/ToML47A==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:bY8t9x6xLfvY9m9ZsyoikCYgg43GKUvAlja5qnyCJbZ13a7AekMVsGTnosqX5d0=,iv:1Z38ckRXO4N4H+X4+drzhzzMFRhe2UJ2SxA8qdpOIIk=,tag:r+G2ifN0B0cKnMaz+Q4r4A==,type:str]
    MQTT_HOST: ENC[AES256_GCM,data:YUoc1UpzHLKswCSqjX9FVOc=,iv:HCXbhXqWhGQORAd75aouqDQ57swTrzgPfibnkZPfW50=,tag:vq6eft4rXBa0r1umPwHSJQ==,type:str]
    MQTT_PORT: ENC[AES256_GCM,data:Zi1JOA==,iv:/YgWxh/gUX7LTv/PYBm+xggX4Z5Lr/0n1JJ9OOfnQWI=,tag:1ZExsEWJOCVriHF4EO9NNw==,type:int]
    MQTT_USERNAME: ENC[AES256_GCM,data:vqxA/qSVWDlP,iv:LieG4KecTURScRThMpzuCitOTxwkKLLsSDVIjdBOV9o=,tag:e/M52uRj7vacOr0uuU7S9g==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:C43WC8fEJgH9Xp0cl+NziNRvX8Y=,iv:50YljE77AS6XxWt1i4Wnhg3uJpwr+NLuok3kFNNFRSU=,tag:plVxzFB8oW6l2dDODwE/8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdit5UzZDb09LQnh2Qzd0
            aFVKVEJUQzRPWFFtODNqM1dmd1lZU1NXVVRJCjArMVh4WDVnTlNKaHFYSnlRRWtZ
            RE5qR2VjcnFDWlRXMi9rc1BhRERIbmMKLS0tIHpCalNkYmdPTk1UZFM3OEYvQkJi
            b21jeXp4MEJocEM0bXdWeDZMVVhaT0EKszV4Ilv7Hkp+9gfmzSfkMcc/pwBnJRVb
            dbwfDvPGPTI1cZ3XAg+2fY+J9uFJamFllXTX/XDa3+sQVAJILRzsPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T21:20:31Z"
    mac: ENC[AES256_GCM,data:yHRavmoza0CQSCVtquEZ9GF+6vW/0ASWjNWxG8IeodTpBPknKUxa89wCJCkp0rTyhdsIplf5yPv4ZfKKOvOsoWPZGyI478Y/Oxfz926pO/J0Uqs5tPImn33T103qCQ/Lldepj3CNi7EcvR7nxXDvVlS3zu9nTUIYa21Sfjc0GCQ=,iv:RKAZj4+aRL4EF5P4oDm0vwIni/bFBmdEkbyKmuQDBvM=,tag:F1PjawogooVk1P6CG7/Rhw==,type:str]
    version: 3.13.1
