apiVersion: v1
kind: Secret
metadata:
    name: teslamate-secrets
    namespace: teslamate
stringData:
    DATABASE_USER: ENC[AES256_GCM,data:kyk+iG5kqd6H,iv:h1w3lJ10goIJswBnxRiKlVDbdRw4iDZJpBVFP32Gqyk=,tag:0keT+HpdDpRvp0+/E6jSZQ==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:diReKDk5rbM3S6WuQD6TaVdpk3w=,iv:3+vJYi09wApv4861LMtbOFXjDzvJRnC/XRRUKvfiUow=,tag:0w5rP07hfrWi/NxCZZzc5g==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:ee/av0Y8NeNM,iv:w+7KCCcD6eOG5gtNVCKQ31N+TRhVID8xI4lMRcumsFI=,tag:XE3Yk4djP7i7DFg0vonwWA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:djN7BFPRcwSYHHhVVlgqEgIbq9cfm3s6Fta/YpcIytkm4/cGYK5WPdD5+I5FwmM=,iv:wh8Ux+NJknhaQsnVYxZ6WEisvwhsOoVX+PqcPggk9UI=,tag:NLcSI7Hx7jtIa9uHSrda/Q==,type:str]
    MQTT_HOST: ENC[AES256_GCM,data:Hu+++2fc4zm4pl32HT0bT7I=,iv:embwHHjsKoFTvFEqg3eyr/175r7brC+p2FG8WJl1Dgg=,tag:3CJZhcxFq2/AXYEUTNqQSg==,type:str]
    MQTT_PORT: ENC[AES256_GCM,data:8QIBhA==,iv:X/sNN+LlN3ztqHtLMDmXUvlAIVDkJCKPc822ir0Nd+I=,tag:NiRtY1AOuMt9TLG3PukTJw==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:bAsCr+VQcVQw,iv:RtCOkxfZRkKMgkaRszIH8mfPqpc5wYPJo51cwd1Y6Tk=,tag:1Da7eJ6Lad7CRjDl2QZkNQ==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:WE3E5PKUM5UbPqt+mlAIIbsSFoU=,iv:mQfupzMpdKrH/7q4dHyxGjjZbJduj0IdAWDkAiSh0Qc=,tag:L/o6frigRjtcTmb7F6Oavw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNjRBeTVOamVRQ0pwMXRo
            bnVxV3lvR3d1Vm5CZi8xRUtoZm5mSXVFYUVBCmJwamduMEpvM3ZiQ2pLOFViSStF
            bTZPNS9ma29hYVBYYUxrcTlrdmljcWMKLS0tIGF2MWRHOWZ3Yk9jZHAvQ2RIMGcz
            bVBEVEp1L09NQ3lzRkwwUHB3bGNtSmsKfpquh/k2v2YEtoDxD4KAqCIymlZnGyA7
            b0kE9WBF9siD3O0oOA9u9FyCu8jeH2q8TlfjM3JHdtKCJESv8i21WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T21:30:16Z"
    mac: ENC[AES256_GCM,data:oxiYwA439+0sn2fzfPxbtjmOE2S2PvJydCe7Kw3kR4rEG/L5DgNMW983S5dWsZnBBlsKVOmGqEzsVWhcXdWADnIv6MN1x0vu941fVIL8ngTnPVY3yYN1XGaD5NJMhytqVGNblT2sB5xoFlNa8PfgzCVcpUi8fRAK5aglLWcpSZo=,iv:9NwKYHJaP87PTFVn7KMOLjkg3mLYjwQXQWa3Mno9Irg=,tag:hThuk3bnj2u1Jskok0a97w==,type:str]
    version: 3.13.1
