apiVersion: v1
kind: Secret
metadata:
    name: tunabrain-secrets
    namespace: arr
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:VlH8TXDVqZ7aLHxFXR6WpyuI5L2wSaBFHEJnRXlioMmJuodcIhmIO42y3olywioENWZwFgtOQZAYHnEVFrWwkOpQdkEeRa1+OUkfpYM1JpZ/PE4Z6sIxgTBFbg94PgbaNpvz8ZowSsLDcu62zcqkwkkXdiZiAHenMVN6WX+T93KjhUDNVHFbHNkavalfJ6dUu7lkDvdS2K1JAOgu3lv26IC0FM8=,iv:oNnMg71dwin/shsv1nwn6d9BD1LJkTBCdWvyvd3EOQU=,tag:IDFNLzDyBQSjb46xFv68+g==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:UhEZkEj4HL1IOTXIRzPrajR7k9OOExZasor6hj/eQA5XNYeakJixQtL+QcdA6zVqq01bi5LJ+m/EglBH+fftWNUI3Chde+5cqA==,iv:3prK/ZWzLoHMq7BovpODFVOzSdBe/ojA0E4J9d2xFVc=,tag:4NcNurIS5E1gAuvCZiGy+Q==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaGNCSHF6R1dRaXNlQjRM
            K0Z0dHpFT2RFb2JEbUYzTUhpU1o0TnRWMG5BCkZoTFFWQisyVlB3U3ExdjVyWUFo
            aFNUVGFRNEhrOXhTRGNaalQzalk3ZlUKLS0tIEE1UFdRZUhQcDBvRXRmMlE2OTJX
            STZvemdUTWlKZlE2QlhZaCtlRFRpWVEKOD6cm5CrTn16coggjXzGo6MiO4ypmJ67
            1cRb8pWitwNy2B9n5Q+VEnPmxJ/V1E/Ugf8lWlR6sWu/wBv+rU2xbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T05:39:16Z"
    mac: ENC[AES256_GCM,data:Hn+ROUeJjuXvaLxk57/doigaQ6/jfg5JZiQ3ds6JRjJVv3tatLo7MhcV1/+P6U7medyWueQoS51/pQwm12ObBRZRl28e25e58oaOKFzWrK2jMuhXJenEvy90EK3XVhPrbS0i8vnYS/nGM1P+xoN1NmyldjtLwpMsrxjodLH8UIE=,iv:0I6vECr1hR7SUsODWOnt4uYsYntb8ZE+OoI9mICabeo=,tag:l85sZxCWtz5zD6P6MYG3Jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
