apiVersion: v1
kind: Secret
metadata:
    name: yundi-secrets
    namespace: hermes
type: Opaque
stringData:
    HA_URL: ENC[AES256_GCM,data:a4sHZ+CbwHLPqiTXWC7EqRnsLABzgAhkGD56LjSrjuI=,iv:mRExYYyzkt/l4oACBwPKP6Nvxbp6IXUTgrPdosSdK68=,tag:erhXwyzeww+IgX0TRFpsxw==,type:str]
    HA_TOKEN: ""
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:LxK/De3mPWXYb/sTr+x2AOVWxiB1ZkaeLXy/KGI1rHSkkxWxNo/5,iv:AQ/5F+IaklNCZhciuBK252GqlI+aHLbsf9DSXl+8sYE=,tag:UvD/p3eHHoSy6lI7NX/A2Q==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:SxDHjC23GqQ8xVMe7kYoqUaPPr/EO4tnkBJdMimhcEA=,iv:3cS56zgyh8U9+C4NFEHnpepg1w8yqq4RHcRclBm687A=,tag:CraqNXPkgZLhRzZPf34FyQ==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:UA5TVuKIoD37PU2ABecZ,iv:57qPSGqVHYezi3287MJyqjLZLYJ3LnD4iPHxYgTQ7iQ=,tag:LbaZ3fwG54yWbpHGRwjG+Q==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:jEb/qN5WpVz9C5mHHXg=,iv:cLnTjyhGwpY9L8bwzmreay6Rv9tu0GvIQ1qwUXlZC+M=,tag:vPIXwP9t06FEFfn5amFLVw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:rJAbw4NoZZne3X5How3JaNOdl7B3vySw9d6XPr65FV7ZIO1QiQQKRxCNi23lUkTUltZXrfR9sTAgpJK2k/g+AE+kI2jjAH4sMg==,iv:16P5PTLZM+0hn5BOaSVCrusfneTwjcGdNHxTK5C2ilo=,tag:rAgtRBh4brkCgoYHKi0dwQ==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:O8nHyn3sdmqyDbHprd2f37bgWGdO81Datuvk4XHXTnW9IYHHeRYDzY1RwPd85Z3f6I6NtrHf1rZiUC9QDzN/tbPKLeWVnCIUllwk/4srq5qwH/0bZTuaQie86QXMF8ovS5q4SjB87S5nnD6O,iv:dg7Q80bIST5dFn+nplJAjYhGz2pVE19tyReIq6ZuaiU=,tag:YubWg5sBQAxHPBE6Y/WTFw==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUk42enZLL2VLYUNyY0E1
            aHRONzBDQ1pFcy9HM1k3eE9oYXBKREowem1jCjU4U2FyUWRsMkpoUnNXM3N4MUl3
            bGtOQlliN1VDYnM2czBQaTBaeWMzUnMKLS0tIDNOMldUM3c3QmhVeVNCSGJUbFVs
            MDVtdVR6YVU4RlEwWEdkWGZ3cjU2VWMKEJJO/BGrGkRJ3Sb/0tYL+O8ENAkjI7zB
            i4Npm57Z02IXL6k9OEfnXC0zf1o8BzBAHjnnayKvIFH86TSCbAvqKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T20:57:13Z"
    mac: ENC[AES256_GCM,data:/OVWhmQVpC3gEmUoY0SgMv2zdh0tKNhrsqQE5/JXGR+iqfcWbkShBD7ZdkXA5MHiRsBAwHx8Q3Dkl3aXUnnuS7kicZNSRs4BPgLB0t91squiy6uimu8W9JCXyn7W66YVdMsPfByYgY08pc3ru8S41+tdUkPNPMQm4tG5SfQbO/8=,iv:wZHs/9Wc/g8KDU5XICngBekpjia/CQA0se4omKPX6BU=,tag:q8m1rPVRvQz1gUwBqUUOVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
