apiVersion: v1
kind: Secret
metadata:
    name: yundi-secrets
    namespace: hermes
type: Opaque
stringData:
    HA_URL: ENC[AES256_GCM,data:sP/V2Evkffwf7l2cBeSMKZ6aSA6+KuhL8kO7wzc/KZQ=,iv:gC6lPeNMAAtlQUr7lfbjXLRK/GyK7zxB7zyJu80CUcc=,tag:Jbk+M+a4OI4Rj2d1mhGEjg==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:+SwV2aB2BjDC0ED/TBA9So3Zw5UKoCxZwhN6qmwGG1UlPXLeQYHFOXcl5NBageMomI35K56L1JajTSRQsU0bJ8dVXKbs3s3U77veh3RsyuZBEI+Xo0xVoqiMbZjQpwCaqFp9LhFdq5EKL4dD3QKWSG0Xse6O7lKTgu+esSlxdEnRhA3AoWikPOAAtiKIXN7qHxOsdz4VJNKGjK8EofC5UPTOml7fQNgsNJ2cKcFuIewXl4fc0a5A,iv:TISByNBMQmVpfZ6ttMahVo2mA0eiTpOq0pn6LNlZRWA=,tag:RHV0Yh+golQE+us5ImS9ww==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:zZHx4wcpvog3oJvoxd3jbLZ7DTI9Xeo1tvNoM3tkJD1k9q3NJiMF,iv:61eIWJe/a20SrndO+RyloT9vwzG/iMxLvbnT+dPowBI=,tag:Vq63TSa+ee8LU91XW0d7vA==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:SCiUgOFWWsVavhpDYgp4C74lqiRVR8yavCPI6KOON4c=,iv:gMMmHSGvsnKmLIVduTCKN2NfDYmJ9HFp/uiry10C/Kk=,tag:OcPB7QNFieSE3tT1BWQsRQ==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:2UzlBtFm+NKyuANYZizwQgkFhJJ4Jg==,iv:3bYzNr49PIH9NMu7EdfIRyQFfWheJDYtl41llYYl36g=,tag:Cocv2ZqEizwHXu+PkNcz0A==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:2OTF3Mi6W2VpdGC6JVc=,iv:6mfI5xQyz4QhuFFcNHckcHfADzo8krpLRi/VbOh0H08=,tag:NoL8EDV5unXpmDiXIuV+6Q==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:Qh13akFORWm8CEcYqx6HV0WC6fLly3wChKHJ/7evRYnoiSlkibJ4loJAkwHtSf8M+CW7dUxFyHtTpjfCgpyZkUuNvofW1QnYhQ==,iv:UAylxRiRYFi4TonRXniCY4bBuBri5oxMuB78ruD1e+0=,tag:NuzX2wZzg3rmTaIbi6P04g==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:WcpsE8L26sc0DQUbntVRQ55h/raC4js/irubk7/OjC9i4SymA8uFnwrlMla0TreYa2NZH6spe0n20fEckYUSSW3rpTf3TXVmqYtO4bIJdtFLje2jGKT981/I5KXofHrczqGX3gdEe/qM5xpe,iv:Nx6iqNNaSGWcEZPOWwcb6YcwWILanWvAIhmGyCNp44Y=,tag:eya3hxhDOBXdWKv3x+T9pw==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:QDN5XM4ACLNTuYD0XxicHzfjhSC1GbJJzbNEwt8BC3BJ4Lf6fBlC2FFO3Vc1mF+z7tgyn8JsLrAGioboeBDkSA==,iv:BFwgN6SeCqN+UoYyCjnYHhWl49goshGSoMGWbBhKtz0=,tag:TLIvImtbEE0IMHDqv4C2zQ==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUWJLczhvcm91WG1jemlw
            a0RtNEhldUI3T0J5VnkzeUV0MTlEeGFOSGtzCitLbFd2aldwUVZiY2k4QWt3eW5R
            YkxsK0xaQThsd3g5dUlhUnpta3I4V00KLS0tIGxBYWFOTG1qNlZnL0RTblFRcHdM
            ZDMvcjNYeU5CWjlzMVB1UUh4N1JJMUkKSc1dPfTvw46Wtl4arhvuopBoPMogOCIK
            Wo+LjdCVCUq99Ue87WpVUyrVnCAKGWW7hurGoNHvvXZFbpspYp7SHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:16:22Z"
    mac: ENC[AES256_GCM,data:iU43Ky4oGBBesIBiZiBjx5o7qd5IXdCLZjjaieKR17e03uhyTWpzrFIlgymuty/4rw/rg8OviG6ZRfTbpbUmUM/LiafDCMVfTUAFOT253Tg00X6e41xc5nTjSOK5vUTc81hSf/oqCrOQhIfYZ9LC7seONmcPguBB41JMw1UhcGc=,iv:qKSor2I1JZHrPXyzgzOoL0cxxLyrVz8hb8ivwpf9rYw=,tag:7iDVDQcffRUGtbvFSFyq/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
