apiVersion: v1
kind: Secret
metadata:
    name: yundi
    namespace: hermes
type: Opaque
stringData:
    HA_URL: ENC[AES256_GCM,data:iH2YkZf2I2a/26GNm2WhxPT2mIht89kpP5tp4dZXj04=,iv:5yINwEd4mrF/EsgbstYpIncRb+QbRWtBRj+oMZ6Yfxw=,tag:oo5So3HdwX7gSrahVZvE4w==,type:str]
    HA_TOKEN: ""
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:yNbSuUYU1NcU5ExLfX7fEJ8wtPiEQs0wD2KuCQMb41kO0xGnigrw,iv:KszxdSC9yDVVrT5ZNFRGFGZaICUkncXohADQjFbrhs4=,tag:W4DWeLmhlz5rseSr13isLQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:F7TvuTYW4zScgpz8zFqL9e7qe6HmAtHF/AzzStpk+eM=,iv:tn/orvln8CK6arPkCq6PSDXgELNtJ29lJWNBDjfkDKc=,tag:tlLiw5w9gYehUiYsRSwmEA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:PJ8RYfq7SfW2Hrb6VUK6,iv:lySx/RVE5WJAD5SObHkBSC5jVqkbEZjqYDbj1LuOJjM=,tag:dARotciMFlbynlyqKgvFHQ==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:+T9SU1OZ0Ccl+qFHc78=,iv:XmnYBdWe/dOaDjTdDh7i9FL+HNhGauTO9m1SvDin1a0=,tag:ulcQa3eH4Ehe3UmBvo3znA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:/ZsMO9eRZIqqHEJp6yoXHyPp+Bt4x6gJZwd1ZM9QLVwvdv2XfhPUcEgfgRRhyXNJUG8hY+6oWr/wGTppEAqMJHUEvfPpoTIymQ==,iv:OFoQoEGC9FbicvRw56vuR4bW7REDbgfKv827lR9cSh4=,tag:6u7edvLIZ88NtaFg5vES4g==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:cvChbFhrFZNoUmeCkjOAkApiULmoMkECR41CAwI0/jAmGQcs3ZvjtzUcHIvVTxe6a6dc2TixTfe2FniRDmjZinX9lFmKlJ18s0DGogCRZ06erzfbmx4IpCsBUTWTp35uhjVMxwu5Iz28X0M4,iv:lQy3HrsuR13tloNY+nq0nwA5a7nCAHBDCA8NoBP57ok=,tag:T7MULXz1jbfjtIQCJUKMlg==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UTE4K053SEFTbEhnZFJF
            OVJRa25IVnJVNWsxeDdmN3hlbXhoR1lXU1FZClE0L1o1OWdCUjQ2T2ZqQUloSmky
            SDhLbjZqbFBrbHR2UDgyd0lRZktZUkUKLS0tIEpBNVN2U3RrSlJmTWRaanQzeXYx
            Sy9oc0NTL01aUUVIZWtLdjdlbmFLc1UKHFIDn8FZAvZdXnUvyEolw2ZJqRYGhxz/
            mzgWDnLfx0wchqUpm1b0/8YAmPJMWt6fGVhioJfPibP1OK1SUwGW6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T20:43:45Z"
    mac: ENC[AES256_GCM,data:kCxQUcI2aUd5s7vIQsVaKQGMH+SZrsMfj/UzHsdJyBRl3TdVpsi/LSTjHbVgicH4IKzFjMQx+vpWWdVgLslvYjhKOtE6vzUIqYl/CEfwtL60+5/KHrnHsLTWmKQjj4KfRjwYCjI5b9xPYe6Si8JOYaqJ7XOAScJorkc5TexiSbw=,iv:k234VsMq/tfWvYT2mRhiFIfVdy7ZFAobHz+jKboJJPk=,tag:HkgiWDWj2wjEgP7wkeQmVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
