apiVersion: v1
kind: Secret
metadata:
    name: yundi-himalaya-config
    namespace: hermes
type: Opaque
data:
    config.toml: ENC[AES256_GCM,data:nfVlZhX4xlvoAW9aBbiBYUeXwJuc2xdFR2Ziya5sfOUM40A2G7R+hyvIs+qe5UdNOLjoIWtdQYWdyKSyKpYlvmB1q5HfRgkl7JwSGyJnCpZ9AZ38DiqQwXPenouYMUbTmn0f4Rro+jrnhL1ZChTlTDul3ojhZYaxFL2y2GI8+ZorZFGkVYl5gDK1eJ73VThnEwfNTGD0NwxzdO9e89PyziuBAcnYNxfpvUnkVD5V+W92lcoCrsSDD0SIIVtZQtzPkHoCagGTYPv+RGlCIeISrwv8syqmVUlTIdbywMrtfmFxDVVY8JEr71pR1QKRtgeBk2b4t2224ftCwrjVTiqTQFrzOfs48xAGiIN3lF8FP7qfgZXoxXfW7YUIH5SPYypfclu2IXL/4lYEMaDJqrhzSExmVHK8wqqoY/A5lOKiyG0b5P6fQGE6pp/0w1YcJn4SOdzlAWdFKaVt/3rsWfq67zQU6dZRv8j27GrEEOyIUudwkstg4bxnBF/dK+bzd9aKeI3cbAu/dB6lhL7yRjlTOQpkvc4vz7rt1QBHotI1F9qs2Yiooti6XcOpVYPuB4p+/70e9ganAs6swsK7yhumxaEUwlq5a+rXlvklTUqyn7JduhR5M5nSnzdft5uSb2Nd5DHwigqsH2aBaAx93j4nbsrIeC2Rvvg4M5uZiEWE5tFR0JJ2K6m/7XVQSz/ml/VN8qG/XY5f80eCGWJZEqXg8aEgH7r/L32/EvUW6cwTIXTq3y7No28fqhkXMOMGN83sieLYtjzC04Gez24Zt60mGpQUrqssqilHx06tKvQjv6CAfHMDHGvz790PV7c=,iv:3Jexd86jmC0HKBaobYNjNvWABOrgEnrGmvp/uASdFLo=,tag:sCxx5Qn+ZEe0AUiB27Oirg==,type:str]
sops:
    age:
        - recipient: age1rn4hhhfgpu8dak5pm4qckpya7xlzpj3zz4ed5q533rmyry55s5rqwjdcj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOHlRL3dRWDhtQUduaGtw
            cVFlMXRuMG9xR0xkdS92V1FBVkg5dEJFblRrCk51OEhzdkxQQmxiZkE3V3VISWJk
            dDlnWTF1ZXBkc3VxNTRnUlZPcWR4OUUKLS0tIGxnR3JRZDk0am9QWTBZMGlxbGVt
            bXFCbVV6bkQwVzVWcFZobFU3U040aUUKh99nZ3okLTKNN1v2HuxDENrYqEJdmZ3I
            RV4B8GsmJ5gGmuz2EmT3lWek+jvK2uGfSHIq2tlAnRQsNWaE5fkJRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T02:55:41Z"
    mac: ENC[AES256_GCM,data:tm1+0ViJB/jaNcFzDANB3HW4mFH61oikAB14CgAr+W+1ExZ9Uw4dVO1aVaHuB/APXwqcv0IgvSLB1kaDHo9Nk6iAdrAtfL7Vnkv9nzDToGL5xbkQ3r7kO/G9KHGnwioljxotYjIqFEXGGIg62Kae5B9CysLqmhYV0knRwfrp4Ng=,iv:JI5geao+fC0rhYNUDQ6C5W8Q2YE91rLUzYGHk7ZdMH4=,tag:595GljjaUl2Ht7JiMspkUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
